<div class="boxTab height-3">
    <div class="float-l span-6">
        <h3><?php echo $this->escape($this->translate('L_VIEW_DATA_HORA')) ?></h3>
        <?php echo date('d/m/Y H:i:s', strtotime($this->pedido->dt_solicitacao_pedido))?>
    </div>
    <div>
        <h3><?php echo $this->escape($this->translate('L_VIEW_SITUACAO')) ?></h3>
        <?php echo $this->pedido->st_situacao_pedido_desc?>
    </div>
</div>
<br />

<h2 class="span-12"><?php echo $this->escape($this->translate('L_VIEW_QUESTIONARIO')) ?></h2>
<div style="overflow-x: auto; padding: 5px; height: 250px;" class="border">
    <?php
        $pergunta = 0;
        foreach($this->formulario as $rs) {
            if($pergunta != $rs->cd_pergunta_pedido) {
                if($pergunta)
                    echo '</div>';
                $pergunta = $rs->cd_pergunta_pedido;
                echo '<div class="span-20 clear-l float-l">';
                echo "<label class=\"bold float-l clear-l\"><span>{$rs->tx_titulo_pergunta}</span></label>";
            }
            if($rs->st_resposta_texto == 'T')
                echo '<label class="span-12 float-l clear-l"><span>' . nl2br($rs->tx_descricao_resposta) . '</span></label>';
            else {
                echo '<label class="float-l clear-l"><span>';
                echo $rs->tx_titulo_resposta;
                if($rs->st_resposta_texto == 'S')
                    echo ' - ' . $rs->tx_descricao_resposta;
                echo '</span></label>';
            }
        }
        if($pergunta)
            echo '</div>';
    ?>
</div>

<?php
    if(count($this->historico)):?>
        <br />
        <h2 class="span-12"><?php echo $this->escape($this->translate('L_VIEW_HISTORICO')) ?></h2>
        <div class="float-l clear-l">
            <script type="text/javascript">
            $(document).ready(function() {
                $("#pedidoAutorizadoEncaminhar").tablesorter({widthFixed: true, widgets: ['zebra']});
                $("#pedidoAutorizadoEncaminhar").tablesorterPager({container: $("#pedidoAutorizadoEncaminharPager")});
            });
            </script>
            <table cellspacing="1" id="pedidoAutorizadoEncaminhar" class="tablesorter" style="border-collapse:collapse">
                <thead>
                    <tr>
                        <th class="span-3" ><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_HORA' )) ?></th>
                        <th class="span-4" ><?php echo $this->escape($this->translate('L_VIEW_GRID_SITUACAO'  )) ?></th>
                        <th class="span-14"><?php echo $this->escape($this->translate('L_VIEW_GRID_OBSERVACAO')) ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($this->historico as $rs): ?>
                    <tr>
                        <td><?php echo date('d/m/Y H:i:s', strtotime($rs->dt_registro_historico))?></td>
                        <td><?php echo $rs->st_acao_historico_desc?></td>
                        <td><?php echo nl2br($rs->tx_descricao_historico)?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div id="pedidoAutorizadoEncaminharPager" class="pager">
                <form>
                    <img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
                    <img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
                    <input type="text" class="pagedisplay"/>
                    <img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
                    <img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
                    <select class="pagesize">
                        <option selected="selected"  value="10">10</option>
                        <option value="20">20</option>
                    </select>
                </form>
            </div>
        </div>
<?php endif; ?>

<br />
<br />
<h2 class="span-12 float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_ENCAMINHAMENTO')) ?></h2>
<div id="div_encaminhar_pedido_comite" class="float-l clear-l">
    <?php echo $this->formHidden('cd_solicitacao_pedido', $this->pedido['cd_solicitacao_pedido'])?>
    
    <label class="float-l span-3 bold required" for="tx_descricao_historico"><?php echo $this->escape($this->translate('L_VIEW_ANALISE')) ?>:</label>
    <?php echo $this->formTextarea('tx_descricao_historico', '', array('class'=>'float-l', 'style' => 'width:555px; height:150px;'))?>

    <?php echo $this->formButton('btn_encaminhar_comite',$this->escape($this->translate('L_BTN_ENCAMINHAR_COMITE')), array('class'=>'float-l clear-l verde push-3 span-4','onclick'=>'enviarPedidoComite()')); ?>
    <?php echo $this->formButton('btn_cancelar_encaminhar_comite',$this->escape($this->translate('L_BTN_CANCELAR')), array('class'=>'float-l  vermelho push-3','onclick'=>'desabilitaAbaPedido()')); ?>
</div>
