<?php
    $this->script('scriptFile',array('/gerenciamento-mudanca/analise-mudanca-requisito.js'));
?>
<div class="clear boxTab">
	<label class="float-l bold" style="margin-top:2px; font-size:16px;" id="mesAnoAnaliseMudancaRequisito"><?php echo $this->mesAno ?></label>
	<label class="float-r" style="margin-top:2px;"><?php echo $this->anoCombo('anoAnaliseMudancaRequisito', $this->anoComboValue,null,1) ?></label>
	<label class="float-r" style="margin-top:2px;"><?php echo $this->mesCombo('mesAnaliseMudancaRequisito', $this->mesComboValue) ?></label>
</div>
<div id="gridGerenciamentoMudancaRequisito"></div>