<form method="post" id="formObjetivoProposta">
	<div>
	<div style="overflow:hidden; padding-left: 5px;">
        <label class="span-3 float-l"><?php echo $this->escape($this->translate('L_VIEW_NOME_PROJETO')) ?>:</label>
            <p class="span-17 float-l bold"><?php echo $this->nomeProjeto ?></p>
		<label class="span-3 float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_PROPOSTA')) ?>:</label>
            <p class="span-3 float-l bold"><?php echo $this->cd_proposta ?></p>
	</div>
	<div  style="padding-top:8px; padding-left:5px;">
		<label class="span-3 float-l"><?php echo $this->escape($this->translate('L_VIEW_OBJETIVO')) ?>:</label>
            <p class="span-17 float-l" style="text-align: justify;"><?php echo $this->tx_objetivo_proposta ?></p>
	</div>
	<hr />
	</div>
</form>