<li id="box-saldo-horas" class="boxList float-l boxMedio">
	<div class="portlet">
		<div class="portlet-header"><?php //echo $this->titulo_box_mapa_site; ?>
			<a href="#" class="ui-dialog-titlebar-close ui-corner-all" role="button" unselectable="on" style="-moz-user-select: none;">
				<span class="ui-icon ui-icon-closethick imgCloseBox" unselectable="on" style="-moz-user-select: none;">close</span>
			</a>
		</div>
		<div class="portlet-content">
			<div class="gap-3">
				<!--<object id="barChart" style ="width:350px; height:150px" data="http://localhost/oasis/public/img/tutorial_bar_chart_3d.svg" type="image/svg+xml" />-->
				<img src="<?php echo $this->baseUrl() ?>/public/img/tutorial_bar_chart_3d.png" />
				<label><?php echo $this->escape(Base_Util::getTranslator('L_VIEW_TOTAL_SIGLA_METRICA_VARIAVEL_CONTRATO', $this->tx_sigla_metrica_padrao)) ?>: <?php echo $this->qtd_horas_contrato; ?></label>
			</div>
		</div>
	</div>
</li>