<li id="box-total-propostas-novas-evolutivas" class="boxList float-l boxPequeno">
	<div class="portlet">
		<div class="portlet-header"><?php echo $this->titulo_box_total_propostas_novas_evolutivas; ?>
			<a href="#" class="ui-dialog-titlebar-close ui-corner-all" role="button" unselectable="on" style="-moz-user-select: none;">
				<span class="ui-icon ui-icon-closethick imgCloseBox" unselectable="on" style="-moz-user-select: none;">close</span>
			</a>
		</div>
		<div class="portlet-content">
			<div class="gap-3 span-15">
				<object data="<?php echo $this->imagem_box_total_propostas_novas_evolutivas ?>" type="image/svg+xml">
					<!-- You need a browser capeable of SVG to display this image. -->
                    <div class="span-13">
                        <?php echo $this->escape($this->translate('L_MSG_ALERT_BROWSER_INCOMPATIVEL_IMAGEM_SGV_SEM_DADOS_GERACAO_GRAFICO')) ?>
                    </div>
				</object>
			</div>
		</div>
	</div>
</li>