<li id="box-solicitacoes" class="boxList float-l boxPequeno">
	<div class="portlet">
		<div class="portlet-header"><?php echo $this->titulo_box_solicitacoes; ?>
			<a href="#" class="ui-dialog-titlebar-close ui-corner-all" role="button" unselectable="on" style="-moz-user-select: none;">
				<span class="ui-icon ui-icon-closethick imgCloseBox" unselectable="on" style="-moz-user-select: none;">close</span>
			</a>
		</div>
		<div class="portlet-content">
			<div class="gap-3" style="padding-top:5px">
                <label class="bold span-7 center"><?php echo $this->escape($this->translate('L_VIEW_SOLICITACOES_PARA_LEITURA')) ?></label>
				<span class="highlight span-4 float-l clear-l" style="margin:0 0 0 61px;text-align: center; color:white;font-size:3em;cursor:default;-moz-border-radius:10px">
					<?php echo $this->solicitacoes_para_leitura; ?>
				</span>
				<label class="bold span-7 center"><?php echo $this->escape($this->translate('L_VIEW_SOLICITACOES_EM_EXECUCAO')) ?></label>
				<span class="highlight span-4 float-l clear-l" style="margin:0 0 0 61px; text-align: center;color:white;font-size:3em;cursor:default;-moz-border-radius:10px">
					<?php echo $this->solicitacoes_em_execucao; ?>
				</span>
				<label class="bold span-7 center"><?php echo $this->escape($this->translate('L_VIEW_SOLICITACOES_CONCLUIDAS')) ?></label>
				<span class="highlight span-4 float-l clear-l" style="margin:0 0 0 61px; text-align: center;color:white;font-size:3em;cursor:default;-moz-border-radius:10px">
					<?php echo $this->solicitacoes_concluidas; ?>
				</span>
			</div>
		</div>
	</div>
</div>