<li id="box-execucao-contrato" class="boxList float-l boxGrande">
	<div class="portlet">
		<div class="portlet-header"><?php echo $this->titulo_box_execucao_contrato; ?>
			<a href="#" class="ui-dialog-titlebar-close ui-corner-all" role="button" unselectable="on" style="-moz-user-select: none;">
				<span class="ui-icon ui-icon-closethick imgCloseBox" unselectable="on" style="-moz-user-select: none;">close</span>
			</a>
		</div>
		<div class="portlet-content">
				<div class="gap-3 span-14">
					<object data="<?php echo $this->imagem_box_execucao_contrato?>" type="image/svg+xml">
						<!-- You need a browser capeable of SVG to display this image. -->
						<?php echo $this->escape($this->translate('L_MSG_ALERT_BROWSER_INCOMPATIVEL_IMAGEM_SGV')) ?>
					</object>
                    <label><?php echo $this->escape(Base_Util::getTranslator('L_VIEW_TOTAL_SIGLA_METRICA_VARIAVEL_CONTRATO', $this->tx_sigla_metrica_padrao)) ?>: <span class="bold"><?php echo $this->qde_box_saldo_horas_contrato?></span></label>
				</div>
				<div class="gap-3" style="padding-top:5px">
					<label class="bold span-5"><?php echo $this->escape(Base_Util::getTranslator('L_VIEW_SIGLA_METRICA_VARIAVEL_RESTANTE_CONTRATO', $this->tx_sigla_metrica_padrao)) ?></label>
					<span class="highlight span-5 float-l" style="text-align: center;color:white;font-size:3em;cursor:default;-moz-border-radius:10px"><?php echo $this->horas_restante_box_execucao_contrato; ?></span>
					<label class="bold span-5"><?php echo $this->escape(Base_Util::getTranslator('L_VIEW_SIGLA_METRICA_VARIAVEL_EXECUTAR_MES', $this->tx_sigla_metrica_padrao)) ?></label>
					<span class="highlight span-5 float-l" style="text-align: center;color:white;font-size:3em;cursor:default;-moz-border-radius:10px"><?php echo $this->horas_mes_box_execucao_contrato; ?></span>
					<label class="bold span-5"><?php echo $this->escape(Base_Util::getTranslator('L_VIEW_SIGLA_METRICA_VARIAVEL_PREVISTA_MES', $this->tx_sigla_metrica_padrao)) ?></label>
					<span class="highlight span-5 float-l" style="text-align: center;color:white;font-size:3em;cursor:default;-moz-border-radius:10px"><?php echo $this->horas_previstas_box_execucao_contrato; ?></span>
				</div>
		</div>
	</div>
</li>