<li id="box-quantidade-processo" class="boxList float-l boxPequeno">
	<div class="portlet">
		<div class="portlet-header"><?php //echo $this->titulo_box_mapa_site; ?>
			<a href="#" class="ui-dialog-titlebar-close ui-corner-all" role="button" unselectable="on" style="-moz-user-select: none;">
				<span class="ui-icon ui-icon-closethick imgCloseBox" unselectable="on" style="-moz-user-select: none;">close</span>
			</a>
		</div>
		<div class="portlet-content">
            <p><?php echo $this->escape($this->translate('L_VIEW_QTD_PROJETO')) ?>: <?php echo $this->qtd_projeto; ?></p>
		</div>
	</div>
</li>