<!--
	o 'ID' da 'li' deve ser o nome da pagina phtml que deve ser o mesmo definido no cadastro do box
	Ex: id="box-mapa-site"

	a unica alteração dos atributos da li é o tamanho do box dado pelas classes 'boxPequeno', 'boxMedio' e 'boxGrande'
-->
<li id="______________" class="boxList float-l boxMedio">
	<div class="portlet">
		<div class="portlet-header"><?php echo $this->titulo_box_demanda_por_tecnico; ?>
			<a href="#" class="ui-dialog-titlebar-close ui-corner-all" role="button" unselectable="on" style="-moz-user-select: none;">
				<span class="ui-icon ui-icon-closethick imgCloseBox" unselectable="on" style="-moz-user-select: none;">close</span>
			</a>
		</div>
		<div class="portlet-content">

			<!-- Aqui vem todo o html do conteudo do box-->

		</div>
	</div>
</li>