<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableProjetoLegado").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableProjetoLegado").tablesorterPager({container: $("#tableProjetoLegadoPager")});
});
</script>
<table id="tableProjetoLegado" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th>&nbsp;</th>
            <th><?php echo $this->escape($this->translate('L_VIEW_GRID_CODIGO')) ?></th>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_SIGLA')) ?></th>
			<th width="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_PROJETO')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
        $cont = 1;
		foreach ($this->res as $res):
	?>
    <tr>
        <td onclick="recuperaProjetoLegado(<?php echo $res['cd_projeto'] ?>)" style="cursor:pointer;"><?php echo $cont ?></td>
        <td onclick="recuperaProjetoLegado(<?php echo $res['cd_projeto'] ?>)" style="cursor:pointer;"><?php echo $res['cd_projeto'] ?></td>
        <td onclick="recuperaProjetoLegado(<?php echo $res['cd_projeto'] ?>)" style="cursor:pointer;"><?php echo $res['tx_sigla_projeto'] ?></td>
        <td onclick="recuperaProjetoLegado(<?php echo $res['cd_projeto'] ?>)" style="cursor:pointer;"><?php echo $res['tx_projeto'] ?></td>
	</tr>	
	<?php
        $cont++;
		endforeach;
	} else {
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
			   </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableProjetoLegadoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
