<form id="formJustificativaDemanda" style="margin-left: 10px;">
	<?php echo $this->formHidden('cd_demanda_justificativa_demanda', $this->cd_demanda ); ?>
	<?php echo $this->formHidden('cd_nivel_servico_justificativa_demanda', $this->cd_nivel_servico ); ?>
	
	<label class="float-l span-5 bold"><?php echo $this->escape($this->translate('L_VIEW_DATA_HORA_DEMANDA')) ?>:</label>
	<span class="float-l span-9 bold"><?php echo $this->dt_demanda; ?></span>

    <label class="float-l clear-l span-5 bold"><?php echo $this->escape($this->translate('L_VIEW_JUSTIFICATIVA')) ?>:</label>
	<div class="float-l span-9">
		<?php echo $this->formTextarea('tx_justificativa_demanda', null, array('style' => 'width:350px; height:120px;')) ?>
	</div>
</form>