<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableRequisitos").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableRequisitos").tablesorterPager({container: $("#tableRequisitosPager"),size: 05}); 
});
</script>
<table id="tableRequisitos" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-2" ><?php echo $this->escape($this->translate('L_VIEW_GRID_NR'        )) ?></th>
			<th class="span-12"><?php echo $this->escape($this->translate('L_VIEW_GRID_REQUISITO' )) ?></th>
			<th class="span-4" ><?php echo $this->escape($this->translate('L_VIEW_GRID_SITUACAO'  )) ?></th>
			<th class="span-3" ><?php echo $this->escape($this->translate('L_VIEW_GRID_STATUS'    )) ?></th>
			<th class="span-5" ><?php echo $this->escape($this->translate('L_VIEW_GRID_TIPO'      )) ?></th>
			<th class="span-3" ><?php echo $this->escape($this->translate('L_VIEW_GRID_PRIORIDADE')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
			if( $res['st_fechamento_requisito'] == 'Aberto'):
			
						//cria a linha da grid com o link para ser alterado quando requisito encontra-se aberto
					    $fim = "";
						if(strlen($res['tx_requisito']) >= 65){
							$fim = "...";
						}
						$tx_requisito = substr($res['tx_requisito'],0,65) 
					?>
				<tr>
					<td style="cursor: pointer;" onClick="recuperaDadosDoRequisito(<?php echo $res['cd_requisito'] ?>,<?php echo $res['ni_versao_requisito'] ?> )"><?php echo $res['ni_ordem']?></td>
					<td style="cursor: pointer;" onClick="recuperaDadosDoRequisito(<?php echo $res['cd_requisito'] ?>,<?php echo $res['ni_versao_requisito'] ?> )"><?php echo $tx_requisito.$fim; 			  ?></td>
					<td style="cursor: pointer;" onClick="recuperaDadosDoRequisito(<?php echo $res['cd_requisito'] ?>,<?php echo $res['ni_versao_requisito'] ?> )"><?php echo $res['st_fechamento_requisito'];?></td>
					<td style="cursor: pointer;" onClick="recuperaDadosDoRequisito(<?php echo $res['cd_requisito'] ?>,<?php echo $res['ni_versao_requisito'] ?> )"><?php echo $res['st_requisito'];			  ?></td>
					<td style="cursor: pointer;" onClick="recuperaDadosDoRequisito(<?php echo $res['cd_requisito'] ?>,<?php echo $res['ni_versao_requisito'] ?> )"><?php echo $res['st_tipo_requisito'];	  ?></td>
					<td style="cursor: pointer;" onClick="recuperaDadosDoRequisito(<?php echo $res['cd_requisito'] ?>,<?php echo $res['ni_versao_requisito'] ?> )"><?php echo $res['st_prioridade_requisito'];?></td>
				</tr>
	<?php
			else:
			
				//cria a linha da grid com sem o link para alteração quando requisito encontra-se fechado
	?>
				<tr>
					<?php 
					    $fim = "";
						if(strlen($res['tx_requisito']) >= 65){
							$fim = "...";
						}
						$tx_requisito = substr($res['tx_requisito'],0,65);

                        $msgAlert = $this->escape($this->translate('L_MSG_ALERT_REQUISITO_FECHADO_NAO_ALTERAR'));
					?>
					<td title="<?php echo $msgAlert ?>"><?php echo $res['ni_ordem']?></td>
					<td title="<?php echo $msgAlert ?>"><?php echo $tx_requisito.$fim; ?></td>
					<td title="<?php echo $msgAlert ?>"><?php echo $res['st_fechamento_requisito']; ?></td>
					<td title="<?php echo $msgAlert ?>"><?php echo $res['st_requisito']; ?></td>
					<td title="<?php echo $msgAlert ?>"><?php echo $res['st_tipo_requisito']; ?></td>
					<td title="<?php echo $msgAlert ?>"><?php echo $res['st_prioridade_requisito']; ?></td>
				</tr>
	
	<?php endif;
		endforeach;
	} else {
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableRequisitosPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="5">05</option>
			<option value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
		</select>
	</form>
</div>
