<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableFechamentoVersao").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableFechamentoVersao").tablesorterPager({container: $("#tableFechamentoVersaoPager"),size: 05}); 
});
</script>
<table id="tableFechamentoVersao" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-10"><?php echo $this->escape($this->translate('L_VIEW_GRID_REQUISITO')) ?></th>
			<th class="span-2" ><?php echo $this->escape($this->translate('L_VIEW_GRID_VERSAO'   )) ?></th>
			<th class="span-2" ><?php echo $this->escape($this->translate('L_VIEW_GRID_STATUS'   )) ?></th>
			<th class="span-3" ><?php echo $this->escape($this->translate('L_VIEW_GRID_ACAO'     )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr>
			<?php 
			    $fim = "";
				if(strlen($res['tx_requisito']) >= 100){
					$fim = "...";
				}
				$tx_requisito = substr($res['tx_requisito'],0,100) 
			?>
			<td><?php echo $tx_requisito.$fim; ?></td>
			<td style="text-align: center;"><?php echo $res['ni_versao_requisito'    ]; ?></td>
			<td style="text-align: center;"><?php echo $res['st_fechamento_requisito']; ?></td>
			
			<?php if($res['st_fechamento_requisito'] === 'Aberto'): ?>
				<td style="text-align: center;">
					<?php
						$click = "fecharVersaoRequisito({$res['cd_requisito']},'{$res['dt_versao_requisito']}');";
						echo $this->formButton('btn_fechar_versao_requisito', $this->escape($this->translate('L_BTN_FECHAR_VERSAO')), array('class'=>'verde','onclick'=>"{$click}"));
					?>
				</td>
			<?php else: ?>
				<td></td>
			<?php endif; ?>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableFechamentoVersaoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="5">05</option>
			<option value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
		</select>
	</form>
</div>
