<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tablePainelProfissional").tablesorter({widthFixed: true, widgets: ['zebra']}) 
    $("#tablePainelProfissional").tablesorterPager({container: $("#tablePainelProfissionalPager")}); 
});
</script>
<table id="tablePainelProfissional" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th><?php echo $this->escape($this->translate('L_VIEW_GRID_PROFISSIONAL')) ?></th>
			<th><?php echo $this->escape($this->translate('L_VIEW_GRID_EMPRESA'     )) ?></th>
			<th><?php echo $this->escape($this->translate('L_VIEW_GRID_SITUACAO'    )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr onclick="recuperaProfissional(<?php echo $res['cd_profissional'] ?>)" style="cursor: pointer;">
			<td><?php echo $res['tx_nome_conhecido'] ?></td>
			<td><?php echo $res['tx_empresa'] ?></td>
			<td><?php echo $res['desc_ativo'] ?></td>
		</tr>
	<?php
		endforeach;
	} else {
		echo "  <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	}
	?>
	</tbody>
</table>
<div id="tablePainelProfissionalPager" class="pager">
<form><img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png"
	class="first" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png"
	class="prev" /> <input type="text" class="pagedisplay" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png"
	class="next" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png"
	class="last" /> 
	<select class="pagesize">
		<option selected="selected" value="10">10</option>
		<option value="20">20</option>
		<option value="30">30</option>
		<option value="40">40</option>
		</select>
	</form>
</div>
