<?php
	$this->script("grid");
	$this->script("calendario");
	$this->script("mascara");
	$this->script("validaData");
    $this->script('scriptFile',array('/solicitacao-servico-consulta-objeto-projeto/index.js'));
?>
<div id="tabSolicitacaoServicoConsulta" class="divTab">
	<div class="clear boxTab" >
        <label class="span-2 float-l"><?php echo $this->escape($this->translate('L_VIEW_NUMERO')) ?>:</label>
		<p class="float-l span-6">
			<?php echo $this->formText('solicitacao', null, array('class' => 'span-3 float-l', 'style' => 'margin-right: 10px;'), null) ?>
			<label class="span-2 float-l" style="font-size: 8px;">(XX/AAAA)</label>
		</p>
		<label class="span-2 float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_SOLICITANTE')) ?>:</label>
            <p class="float-l span-6"><?php echo $this->formText('tx_solicitante', null, array('class' => 'span-5 float-l', 'style' => 'margin-right: 10px;'), null) ?></p>
		<label class="span-2 float-l"><?php echo $this->escape($this->translate('L_VIEW_UNIDADE')) ?>:</label>
            <p class="float-l span-6"><?php echo $this->formSelect('cd_unidade', null, array('class' => 'span-5 float-l', 'style' => 'margin-right: 10px;'), $this->cd_unidade_combo) ?></p>
		<label class="span-2 float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_DATA_INICIAL')) ?>:</label>
            <p class="float-l span-6"><?php echo $this->Data('dt_inicio', null, array('class' => 'float-l'), null) ?></p>
		<label class="span-2 float-l"><?php echo $this->escape($this->translate('L_VIEW_DATA_FINAL')) ?>:</label>
            <p class="float-l span-6"><?php echo $this->Data('dt_fim', null, array('class' => 'float-l'), null) ?></p>
		<label class="span-2 float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_TEXTO')) ?>:</label>
            <p class="float-l"><?php echo $this->formText('tx_solicitacao', null, array('class' => 'span-14 float-l'), null) ?></p>
		<label class="span-2 float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_TIPO')) ?>:</label>
            <p class="float-l"><input type="radio" name="tipo_consulta" id="tipo_consulta_and" value="and" checked="checked" />And</p>
            <p class="float-l "><input type="radio" name="tipo_consulta" id="tipo_consulta_or" value="or" />Or</p>
		<label class="span-2 float-r clear-l">
            <?php echo $this->formButton('bt_consultar_solicitacao_projeto', $this->escape($this->translate('L_BTN_CONSULTAR')), array('class' => 'float-r azul'), null)?>
        </label>
	</div>
	<div id="gridSolicitacaoServicoConsulta" class="float-l clear-l span-21"></div>
</div>