<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl() ?>/public/js/modules/default/proposta/index.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl() ?>/public/js/lib/utils/semCaracterEspecial.js"></script>

<form id="formCriarProposta">
	<?php echo $this->formHidden('cd_objeto'			, $this->cd_objeto);?>
	<?php echo $this->formHidden('ni_solicitacao'		, $this->ni_solicitacao);?>
	<?php echo $this->formHidden('ni_ano_solicitacao'	, $this->ni_ano_solicitacao);?>

	<div style="padding-top:5px; padding-left:10px;">
        <label class="float-l span-3 bold"><?php echo $this->escape($this->translate('L_VIEW_SOLICITACAO')) ?>:</label>
			<span class="float-l bold" id="dados_solicitacao"><?php echo $this->ni_solicitacao."/".$this->ni_ano_solicitacao?></span>

		<div class="span-7 clear-l float-l" style="width:230px; height: 100px; border-right:1px solid rgb(84, 189, 205);">
			<input type="radio" id="tipo_proposta_n" name="tipo_proposta" value="N" class="float-l"/>
				<label class="float-l" for="tipo_proposta_n"><?php echo $this->escape($this->translate('L_VIEW_NOVA_PROPOSTA')) ?></label>
			<?php echo $this->formSelect('cd_pre_projeto', null, array('class' => 'span-5 float-l','disabled' => 'disabled'), $this->preProjetoCombo);?>

			<div id="dados_projeto" class="float-l clear-l" style="display: none; margin-top: 15px">
				<label class="span-4 float-l" for="tx_projeto"><?php echo $this->escape($this->translate('L_VIEW_NOME_PROJETO')) ?>:</label>
				<?php echo $this->formText('tx_projeto', null, array('class' => 'span-4 float-l', 'disabled' => 'disabled'));?>
				<label class="span-3 float-l" for="tx_sigla_projeto"><?php echo $this->escape($this->translate('L_VIEW_SIGLA')) ?>:</label>
				<?php echo $this->formText('tx_sigla_projeto', null, array('class' => 'span-4 float-l', 'disabled' => 'disabled', 'onKeyPress'=>'return semCaracterEspecial(event)'));?>
                <span class="float-l" style="color:red"><small><?php echo $this->escape($this->translate('L_VIEW_CARACTERES_NAO_ACEITOS')) ?>: <b>\&nbsp;/&nbsp;:&nbsp;*&nbsp;?&nbsp;"&nbsp;&lt;&nbsp;&gt;&nbsp;|</b></small></span>
			</div>
		</div>
			
		<div class="span-7 float-l" style="width:230px; margin-right:0; margin-left: 25px;">
			<input type="radio" id="tipo_proposta_e" class="float-l" name="tipo_proposta" value="E" class="float-l"/>
			<label class="float-l" for="tipo_proposta_e"><?php echo $this->escape($this->translate('L_VIEW_PROPOSTA_EVOLUTIVA')) ?>:</label>
			<?php echo $this->formSelect('cd_projeto', null, array('class' => 'span-5 float-l clear-l', 'disabled' => 'disabled'), $this->projetoCombo);?>
			<div id="pre_projeto_evolutivo">
				<label class="span-4 float-l" for="tx_projeto">
                    <?php echo $this->escape($this->translate('L_VIEW_PRE_PROJETO_EVOLUTIVO')) ?>:
                </label>
				<?php echo $this->formSelect('cd_pre_projeto_evolutivo', null, array('class' => 'span-5 float-l clear-l', 'disabled' => 'disabled'), array('0'=>$this->escape($this->translate('L_VIEW_COMBO_SELECIONE'))));?>
			</div>
		</div>
	</div>
</form>