<div class="divTab">
    <div class="clear boxTab">
        <label class="float-l" style="margin-top:2px;">
            <?php echo $this->escape($this->translate('L_VIEW_PROJETO')) ?>:
            <span class="SigProjeto bold"></span>
        </label>
        <hr />
        <label class="float-l" style="margin-top:2px;">
            <?php echo $this->escape($this->translate('L_VIEW_REQUISITO')) ?>:
            <span class="Descricao bold"></span>
            <?php echo $this->formHidden('cd_requisito_solucao',null,array('class'=>'codTabela')); ?>
        </label>
    </div>
    <div id="grid_requisito_solucao_gerenciamentoTeste"></div>
</div>
