<?php 
$this->script('grid');
$this->script('scriptFile',array('/produto-parcela/index.js'));
?>
<div style="margin-left:5px;"> 

    <div style="overflow:hidden; margin-bottom:25px; padding-bottom:15px;">
        <label class="span-3 float-l"><?php echo $this->escape($this->translate('L_VIEW_NOME_PROJETO')) ?>:</label>
            <p class="span-3 float-l bold"><?php echo $this->nomeProjeto ?></p>
        <label class="span-3 float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_PROPOSTA')) ?>:</label>
            <p class="span-3 float-l bold"><?php echo $this->proposta ?></p>
    </div>

    <div class="span-5 float-l clear-l" style="border-right:1px solid rgb(84, 189, 205);">
        <label class="bold span-5" style="padding-right:0;">
            <?php echo $this->escape($this->translate('L_VIEW_LISTA_PARCELAS')) ?>:<br />
            <span class="small"><?php echo $this->escape($this->translate('L_MSG_ALERT_SELECIONE_PARCELA_INCLUSAO_ALTERACAO_PRODUTO')) ?></span>
        </label>
        <?php
        echo $this->mesCombo('mes',"",array('select'=>'select','style'=>'margin-left:18px; margin-right:5px;','class'=>'span-2 float-l'));
        echo $this->anoCombo('ano',"",array('select'=>'select','class'=>'span-2 float-l'));
        ?>

        <label class="clear-l bold span-5" style="padding-right:0;"><?php echo $this->escape($this->translate('L_VIEW_COM_PRODUTO_CADASTRADO')) ?>:</label>
        <a class="span-1 float-l" href="">01</a>
        <a class="span-1 float-l" href="">02</a>
        <a class="span-1 float-l" href="">03</a>
        <a class="span-1 float-l" href="">04</a>
        <a class="span-1 float-l" href="">05</a>
        <a class="span-1 float-l" href="">06</a>
        <a class="span-1 float-l" href="">07</a>
        <a class="span-1 float-l" href="">08</a>
        <label class="span-5 clear" style="padding-right:0;"><?php echo $this->escape($this->translate('L_VIEW_SEM_PRODUTO_CADASTRADO')) ?>:</label>
        <a class="span-1 float-l" href="">09</a>
        <a class="span-1 float-l" href="">10</a>
        <a class="span-1 float-l" href="">11</a>
        <a class="span-1 float-l" href="">12</a>
    </div>

    <div class="span-15 float-l">
        <label class="span-4 bold float-l"><?php echo $this->escape($this->translate('L_VIEW_PARCELAS')) ?>:</label>
        <p class="bold span-8 float-l">XX</p>

        <label class="span-4 bold float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_INSIRA_PRODUTO')) ?>:</label>
        <input class="span-10 float-l" id="" name="" type="text" value="<?php echo $this->escape($this->translate('L_MSG_ALERT_DIGITE_NOME_PRODUTO_TECLE_ENTER')) ?>" />


       <table style="margin-left:162px;" class="span-10">
            <caption><?php echo $this->translate('L_MSG_ALERT_CLIQUE_MODULO_EDITAR_OU_EXCLUIR') ?></caption>
            <tbody>
                <tr><td><img src="<?php echo $this->baseUrl(); ?>/public/img/del.png"></td><td><a href="">Produto Lorem  0001 Lorem Ipsum Dolor</a></td></tr>
                <tr><td><img src="<?php echo $this->baseUrl(); ?>/public/img/del.png"></td><td><a href="">Produto Lorem  0001 Lorem Ipsum Dolor</a></td></tr>
                <tr><td><img src="<?php echo $this->baseUrl(); ?>/public/img/del.png"></td><td><a href="">Produto Lorem  0001 Lorem Ipsum Dolor</a></td></tr>
                <tr><td><img src="<?php echo $this->baseUrl(); ?>/public/img/del.png"></td><td><a href="">Produto Lorem  0001 Lorem Ipsum Dolor</a></td></tr>
                <tr><td><img src="<?php echo $this->baseUrl(); ?>/public/img/del.png"></td><td><a href="">Produto Lorem  0001 Lorem Ipsum Dolor</a></td></tr>
                <tr><td><img src="<?php echo $this->baseUrl(); ?>/public/img/del.png"></td><td><a href="">Produto Lorem  0001 Lorem Ipsum Dolor</a></td></tr>
                <tr><td><img src="<?php echo $this->baseUrl(); ?>/public/img/del.png"></td><td><a href="">Produto Lorem  0001 Lorem Ipsum Dolor</a></td></tr>
            </tbody>
        </table>
    </div>
    <div class="accordionBottom">
        <button type="button" class="verde"><?php echo $this->escape($this->translate('L_BTN_SALVAR')) ?></button>
    </div>
</div>