<script type="text/javascript">
	$(document).ready(function() {
		// call the tablesorter plugin
	    $("#tableStatusAtendimento").tablesorter({widthFixed: true, widgets: ['zebra']});
	    $("#tableStatusAtendimento").tablesorterPager({container: $("#tableStatusAtendimentoPager")});
	});
</script>
<table id="tableStatusAtendimento" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="{sorter: false}" width="15">&nbsp;</th>
            <th class="span-7"><?php echo $this->escape($this->translate('L_VIEW_GRID_STATUS_ATENDIMENTO')) ?></th>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_TIPO')) ?></th>
			<th class="span-2 {sorter: false}"><?php echo $this->escape($this->translate('L_VIEW_GRID_COR')) ?></th>
		</tr>
  </thead>
	<tbody>
	<?php
	if($this->res->valid()){
		foreach ($this->res as $res):
	?>
		<tr>
            <td>
				<img id="imgExcluir"
                     height="13"
                     width="13"
                     style="cursor:pointer;"
                     onclick="excluirStatusAtendimento('<?php echo $res->cd_status_atendimento ?>');"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/>
			</td>
			<td style="cursor:pointer;" onclick="recuperarStatusAtendimento(<?php echo $res->cd_status_atendimento?>)">
				<?php echo $res->tx_status_atendimento ?>
			</td>
			<td style="cursor:pointer;" onclick="recuperarStatusAtendimento(<?php echo $res->cd_status_atendimento?>)">
				<?php echo $res->status_atendimento ?>
			</td>
			<td style="cursor:pointer;" onclick="recuperarStatusAtendimento(<?php echo $res->cd_status_atendimento ?>)">
                <div style="background-color: #<?php echo $res->tx_rgb_status_atendimento ?>; text-align: center" class="span-2">
                    <?php echo $res->tx_rgb_status_atendimento ?>
                </div>
			</td>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	}
	?>
	</tbody>
</table>
<div id="tableStatusAtendimentoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>