<?php $this->script('grid'); ?>
<script type="text/javascript">
	$(document).ready(function() { 
		// call the tablesorter plugin 
	    $("#tableAtividade").tablesorter({widthFixed: true, widgets: ['zebra']});
	    $("#tableAtividade").tablesorterPager({container: $("#tableAtividadePager")}); 
	});
</script>
<table id="tableAtividade" cellspacing="1" class="tablesorter" style="border-collapse:collapse">
	<thead>
		<tr>
            <th class="{sorter: false}" width="15">&nbsp;</th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_NR_ORDEM')); ?></th>
			<th class="span-13"><?php echo $this->escape($this->translate('L_VIEW_GRID_ATIVIDADE')); ?></th>
		</tr>
  </thead>
	<tbody>
	<?php
	if(count($this->res) > 0):
		foreach ($this->res as $res):
	?>
		<tr>
            <td>
                <img id="imgExcluir"
                     height="13"
                     width="13"
                     style="cursor:pointer;"
                     onclick="excluiAtividade(<?php echo $res['cd_atividade'] ?>);"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->escape($this->translate('L_VIEW_EXCLUIR')); ?>"/>
            </td>
			<td style="cursor:pointer;" class="center" onclick="recuperaAtividade(<?php echo $res['cd_atividade'] ?>)">
				<?php echo $this->escape($res['ni_ordem_atividade']) ?>
			</td>
			<td style="cursor:pointer;" onclick="recuperaAtividade(<?php echo $res['cd_atividade'] ?>)">
				<?php echo $this->escape($res['tx_atividade']) ?>
			</td>
		</tr>
	<?php
		endforeach;
	else:
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	endif;
	?>
	</tbody>
</table>
<div id="tableAtividadePager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>