<script type="text/javascript">
	$(document).ready(function() { 
		// call the tablesorter plugin 
	    $("#tableConhecimento").tablesorter({widthFixed: true, widgets: ['zebra']});
	    $("#tableConhecimento").tablesorterPager({container: $("#tableConhecimentoPager")});
	});
</script>
<table id="tableConhecimento" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-4"><?php echo $this->escape($this->translate('L_VIEW_GRID_TIPO_CONHECIMENTO')) ?></th>
			<th class="span-4"><?php echo $this->escape($this->translate('L_VIEW_GRID_CONHECIMENTO')) ?></th>
			<th class="span-1"><?php echo $this->escape($this->translate('L_VIEW_GRID_PADRAO')) ?></th>
		</tr>
  </thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr>
			<td style="cursor:pointer;" onclick="alterarConhecimento(<?php echo $res['cd_conhecimento'] ?>)">
				<?php echo $res['tx_tipo_conhecimento'] ?>
			</td>
			<td style="cursor:pointer;" onclick="alterarConhecimento(<?php echo $res['cd_conhecimento'] ?>)">
				<?php echo $res['tx_conhecimento'] ?>
			</td>
			<td style="cursor:pointer;" onclick="alterarConhecimento(<?php echo $res['cd_conhecimento'] ?>)">
				<?php echo $res['st_padrao_desc'] ?>
			</td>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	}
	?>
	</tbody>
</table>
<div id="tableConhecimentoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>