<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableItemParecerTecnico").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableItemParecerTecnico").tablesorterPager({container: $("#tableItemParecerTecnicoPager")}); 
});
</script>
<table id="tableItemParecerTecnico" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_ITEM_PARECER_TECNICO')) ?></th>
			<th class="span-1 center"><?php echo $this->escape($this->translate('L_VIEW_GRID_PROPOSTA'     )) ?></th>
			<th class="span-1 center"><?php echo $this->escape($this->translate('L_VIEW_GRID_PARCELA'      )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr>
			<td onClick="redirecionaItemParecerTecnico(<?php echo $res['cd_item_parecer_tecnico'] ?>)" style="cursor:pointer;">
				<?php echo $res['tx_item_parecer_tecnico'] ?>
			</td>
			<td class="center" onClick="redirecionaItemParecerTecnico(<?php echo $res['cd_item_parecer_tecnico'] ?>)" style="cursor:pointer;">
				<?php echo ($res['st_proposta'])?"<img src=\"{$this->baseUrl()}/public/img/u42.png\">":""; ?>
			</td>
			<td class="center" onClick="redirecionaItemParecerTecnico(<?php echo $res['cd_item_parecer_tecnico'] ?>)" style="cursor:pointer;">
				<?php echo ($res['st_parcela'])?"<img src=\"{$this->baseUrl()}/public/img/u42.png\">":""; ?>
			</td>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableItemParecerTecnicoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
