<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableNivelServico").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableNivelServico").tablesorterPager({container: $("#tableNivelServicoPager")}); 
});
</script>
<table id="tableNivelServico" cellspacing="1" class="tablesorter" style="border-collapse:collapse">
	<thead>
		<tr>
			<th class="{sorter: false}" style="width: 10px;">&nbsp;</th>
            <th class="span-16"><?php echo $this->escape($this->translate('L_VIEW_GRID_NIVEL_SERVICO')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr>
			<td><img id="imgExcluir" height="13" width="13" style="cursor:pointer; text-align: center;" onclick="excluiNivelServico('<?php echo $res['cd_nivel_servico'] ?>');" src="<?php echo $this->baseUrl()?>/public/img/del.png" alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/></td>
			<td onClick="recuperaNivelServico(<?php echo $res['cd_nivel_servico'] ?>)" style="cursor:pointer;"><?php echo $res['tx_nivel_servico'] ?></td>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
			  </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableNivelServicoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
