<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableGerenciaQualidade").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableGerenciaQualidade").tablesorterPager({container: $("#tableGerenciaQualidadePager")});
});
</script>
<table id="tableGerenciaQualidade" cellspacing="1" class="tablesorter" style="border-collapse: collapse;">
	<thead>
		<tr>
			<th class="{sorter:false}" style="width: 10px;">&nbsp;</th>
            <th class="span-6"><?php echo $this->escape($this->translate('L_VIEW_GRID_FASE')) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA')) ?></th>
			<th class="span-6"><?php echo $this->escape($this->translate('L_VIEW_GRID_QUEM_FAZ')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res->valid()){
		foreach ($this->res as $res):
	?>
		<tr>
			<td><img id="imgExcluir"
                     height="13"
                     width="13"
                     style="cursor:pointer; text-align: center;"
                     onclick="excluirGerenciamentoQualidade('<?php echo $res->cd_gerencia_qualidade ?>');"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/>
            </td>
			<td onClick="recuperaGerenciamentoQualidade(<?php echo $res->cd_gerencia_qualidade ?>)" style="cursor:pointer;"><?php echo $res->tx_fase_projeto ?></td>
            <td onClick="recuperaGerenciamentoQualidade(<?php echo $res->cd_gerencia_qualidade ?>)" style="cursor:pointer;"><?php echo date('d/m/Y',strtotime($res->dt_auditoria_qualidade)) ?></td>
			<td onClick="recuperaGerenciamentoQualidade(<?php echo $res->cd_gerencia_qualidade ?>)" style="cursor:pointer;"><?php echo $res->tx_profissional ?></td>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableGerenciaQualidadePager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
