<?php
    $this->script('uploadAjax');
    $this->script('scriptFile',array('/documentacao-projeto-continuo/index.js'));
?>
<div style="margin-left: 20px;" id="formDocumentoProjetoContinuo">
	<label class="span-3 float-l clear-l required"><?php echo $this->escape($this->translate('L_VIEW_OBJETO')) ?>:</label>
    	<p class="span-3 float-l bold"><?php echo $this->formSelect('cd_objeto_projeto_continuo_doc', null, null, $this->objetoCombo); ?></p>
	<label class="span-3 float-l clear-l required"><?php echo $this->escape($this->translate('L_VIEW_PROJETO_CONTINUO')) ?>:</label>
    	<p class="span-3 float-l bold"><?php echo $this->formSelect('cd_projeto_continuo_doc', null, null, $this->arrContratoCombo); ?></p>
	<label class="span-3 float-l clear-l required" for="cd_tipo_documentacao" ><?php echo $this->escape($this->translate('L_VIEW_DOCUMENTACAO')) ?>:</label>
		<?php echo $this->formSelect('cd_tipo_documentacao', null, array('class' => 'float-l'), $this->tipoDocumentacaoCombo); ?>
    <div id="divExtensao" style="display: none;">
		<label class="span-3 float-l clear-l "><?php echo $this->escape($this->translate('L_VIEW_EXTENSOES')) ?>:</label>
	    	<span class="span-6 float-l bold" id="extensoes"></span>
	</div>
	<label class="span-3 float-l clear-l required" for="tx_arq_doc_projeto_continuo"><?php echo $this->escape($this->translate('L_VIEW_ARQUIVO')) ?>:</label>
		<?php echo $this->formFile('tx_arq_doc_projeto_continuo',array('class'=>'float-l span-3','size'=>'50')); ?>
	<img id="imgLoadDocumentacaoProjetoContinuo" name="imgLoadDocumentacaoProjetoContinuo" alt="<?php echo $this->escape($this->translate('L_VIEW_AGUARDE')) ?>"
         src="<?php echo $this->baseUrl()?>/public/img/ajax-loader.gif" width="220px" height="19px"
         class="float-l clear-l push-3" style="display:none;" />
    <button class="float-l verde clear-l push-3" onclick="return _fnUploadDocumentacaoProjetoContinuo();"><?php echo $this->escape($this->translate('L_BTN_ANEXAR_ARQUIVO')) ?></button>
	<div id="gridDocumentacaoProjetoContinuo" class="float-l clear-l push-1 span-15"></div>
</div>