<script type="text/javascript" src="<?php echo $this->baseUrl()?>/public/js/planejamento/index.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/public/js/lib/utils/numeros.js"></script>

<div id="formPlanejamento" class="divTab">
	<label class="float-l span-2 right"><?php echo $this->translate('L_VIEW_PROJETO') ?>:</label>
		<?php echo $this->formSelect('cd_projeto_planejamento',null,array('class'=>'float-l'),$this->comboProjeto) ?>
	<label class="float-l clear-l span-2 right"><?php echo $this->escape($this->translate('L_VIEW_MODULO')) ?>:</label>
		<?php echo $this->formSelect('cd_modulo_planejamento',null,array('class'=>'float-l'),array(0=>$this->escape($this->translate('L_VIEW_COMBO_SELECIONE')))) ?>
	<label class="float-l clear-l span-2 right"><?php echo $this->escape($this->translate('L_VIEW_ETAPA')) ?>:</label>
		<?php echo $this->formSelect('cd_etapa_planejamento',null,array('class'=>'float-l'),array(0=>$this->escape($this->translate('L_VIEW_COMBO_SELECIONE')))) ?>
	<div id="gridPlanejamento" class="float-l clear-l span-21" style="display: none;"></div>
</div>