<div id="div_detalhe_aceite_proposta" style="margin-left: 10px;">
	<label class="float-l span-3 bold"><?php echo $this->translate('L_VIEW_PROJETO') ?>:</label>
		<span class="float-l span-11 bold"><?php echo $this->tx_sigla_projeto; ?></span>

	<label class="float-l clear-l span-3"><?php echo $this->escape($this->translate('L_VIEW_DATA_ACEITE')) ?>:</label>
		<span class="float-l span-11"><?php echo $this->dt_aceite_proposta; ?></span>

	<label class="float-l clear-l span-3"><?php echo $this->escape($this->translate('L_VIEW_PROFISSIONAL')) ?>:</label>
		<span class="float-l span-11"><?php echo $this->profissional_aceite_proposta; ?></span>

	<label class="float-l clear-l span-3"><?php echo $this->escape($this->translate('L_VIEW_OBSERVACOES')) ?>:</label>
		<span class="float-l span-11" style="text-align: justify;"><?php echo $this->tx_obs_aceite_proposta; ?></span>
</div>