<label class="float-l span-4 bold"><?php echo $this->translate('L_VIEW_PROJETO') ?>:</label>
	<span class="float-l bold"><?php echo $this->tx_sigla_projeto; ?></span>

<label class="float-l span-4 clear-l"><?php echo $this->escape($this->translate('L_VIEW_DATA_FECHAMENTO')) ?>:</label>
	<span class="float-l "><?php echo $this->dt_fechamento_proposta; ?></span>

<label class="float-l span-4 clear-l"><?php echo $this->escape($this->translate('L_VIEW_PROFISSIONAL')) ?>:</label>
	<span class="float-l "><?php echo $this->profissional_fechamento_proposta; ?></span>
