<?php
    $this->script('scriptFile',array('/objeto-contrato/index.js'));
    
    echo $this->formObjetoContrato;
?>
<button id="submitbuttonObjetoContrato" class="verde float-l push-5 clear-l" type="button" name="submit"><?php echo $this->escape($this->translate('L_BTN_SALVAR')) ?></button>
<button id="bt_excluir_objeto_contrato" class="vermelho float-l push-5" type="button" name="bt_excluir"><?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?></button>
