<?php 
    $this->script('validaForm');
    $this->script('scriptFile',array('/alocacao-recurso/index.js'));
?>
<form id="formRelatorioProjetoAlocacaoRecurso">
		<label class="span-2 right float-l required" for="cd_contrato"><?php echo $this->translate('L_VIEW_CONTRATO') ?>:</label>
			<p class="float-l"><?php echo $this->formSelect('cd_contrato',null,null,$this->arrContrato) ?></p>

		<label class="span-2 right float-l required clear-l" for="cd_projeto"><?php echo $this->translate('L_VIEW_PROJETO') ?>:</label>
        <p class="float-l"><?php echo $this->formSelect('cd_projeto',null,null, array(0=>Base_Util::getTranslator('L_VIEW_COMBO_SELECIONE'))) ?></p>
		<label class="span-2 right float-l required clear-l" for="cd_proposta"><?php echo $this->translate('L_VIEW_PROPOSTA') ?>:</label>
			<p class="float-l"><?php echo $this->formSelect('cd_proposta',null, null, array(0=>Base_Util::getTranslator('L_VIEW_COMBO_SELECIONE'))) ?></p>

    <button class="buttonBar verde" id="btn_gerar" name="btn_gerar" type="button"><?php echo $this->translate('L_BTN_GERAR') ?></button>
</form>