<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableTreinamentoProfissional").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableTreinamentoProfissional").tablesorterPager({container: $("#tableTreinamentoProfissionalPager")}); 
});
</script>
<table id="tableTreinamentoProfissional" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
			<th class="span-9"><?php echo $this->escape($this->translate('L_VIEW_GRID_PROFISSIONAL')) ?></th>
			<th class="span-7"><?php echo $this->escape($this->translate('L_VIEW_GRID_TREINAMENTO')) ?></th>
			<th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA')) ?></th>
			<th class="{sorter: false}" style="width: 30px;">&nbsp;</th>
		</tr>
	</thead>
	<tbody>
	<?php
	if(count($this->res)>0):
		foreach ($this->res as $res):
            $dataTreinamento = null;
            if($res['dt_treinamento_profissional'])
                $dataTreinamento = date('d/m/Y', strtotime($res['dt_treinamento_profissional']));
	?>
		<tr>
			<td><?php echo $res['tx_profissional']?></td>
			<td><?php echo $res['tx_treinamento'] ?></td>
			<td><?php echo $this->data("{$res['cd_treinamento']}_{$res['cd_profissional']}",$dataTreinamento,array('class'=>'span-3 float-l')) ?></td>
			<td onClick="salvarDataTreinamento('<?php echo "{$res['cd_treinamento']}_{$res['cd_profissional']}" ?>')">
                <?php echo $this->formButton('btn_salvar_data', $this->escape($this->translate('L_BTN_SALVAR')), array('class'=>'verde')) ?>
            </td>
		</tr>
	<?php
		endforeach;
	else:
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	endif;
	?>
	</tbody>
</table>
<div id="tableTreinamentoProfissionalPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
