<?php 
    $this->script('validaForm');
    $this->script('grid');
    $this->script('scriptFile',array('/documentacao-projeto/index.js'));
?>
<form id="formRelatorio">
	<label class="span-2 float-l required" for="cd_contrato"><?php echo $this->translate('L_VIEW_CONTRATO') ?>:</label>
		<?php echo $this->formSelect('cd_contrato',null,array('class'=>'float-l'),$this->arrContrato); ?>
    <label class="span-2 float-l clear-l required" for="cd_projeto"><?php echo $this->translate('L_VIEW_PROJETO') ?>:</label>
    	<?php echo $this->formSelect("cd_projeto",null,array('class'=>'float-l'),array(0=>Base_Util::getTranslator('L_VIEW_COMBO_SELECIONE'))); ?>
</form>
<div id="gridDocumentacaoProjeto" class="float-l clear-l span-18"></div>