<script type="text/javascript">
$(document).ready(function() {
	// call the tablesorter plugin
    $("#tableProfissionalPapelProfissional").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableProfissionalPapelProfissional").tablesorterPager({container: $("#tableProfissionalPapelProfissionalPager")});
});
</script>
<table id="tableProfissionalPapelProfissional" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-12"><?php echo $this->escape($this->translate('L_VIEW_GRID_PROFISSIONAL')) ?></th>
			<th class="span-7"><?php echo $this->escape($this->translate('L_VIEW_GRID_PAPEL_PROFISSIONAL')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res->valid()):
		foreach ($this->res as $prof):
	?>
    <tr>
        <td><?php echo $this->escape($prof->tx_profissional); ?></td>
        <td><?php echo $this->escape($prof->tx_papel_profissional);?></td>
	</tr>
	<?php
		endforeach;
	else:
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
			   </tr>";
	endif;
	?>
	</tbody>
</table>
<div id="tableProfissionalPapelProfissionalPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>