<?php 
	$this->script('validaForm');
	$this->script('mascara');
	$this->script('calendario');
    $this->script('validaData');
    $this->script('scriptFile',array('/demanda/index.js'));
 ?>
<form id="formRelatorioDemanda">

     <label class="float-l span-4 right required" for="cd_objeto_contrato"><?php echo $this->escape($this->translate('L_VIEW_OBJETO_CONTRATO')) ?>:</label>
    <?php echo $this->formSelect("cd_objeto_contrato",null,array('class'=>'float-l'),$this->arrObjetoContrato); ?>

    <label class="float-l clear-l span-4  right required" for="dt_inicio"><?php echo $this->escape($this->translate('L_VIEW_DATA_INICIAL')) ?>:</label>
		<span class="float-l"><?php echo $this->data("dt_inicio",null,array('class'=>'float-l span-3 ')); ?></span>

    <label class="float-l clear-l span-4 right required" for="dt_fim"><?php echo $this->escape($this->translate('L_VIEW_DATA_FINAL')) ?>:</label>
		<span class="float-l"><?php echo $this->data("dt_fim",null,array('class'=>'float-l span-3')); ?></span>

    <label class="float-l clear-l span-4 right" for="tx_demanda"><?php echo $this->escape($this->translate('L_VIEW_PROBLEMA')) ?>:</label>
		<span class="float-l"><?php echo $this->formText("tx_demanda",null,array('class'=>'span-10 float-l'),$this->arrObjetoContrato); ?></span>
		  
    <label class="float-l clear-l span-4 right" for="cd_profissional"><?php echo $this->escape($this->translate('L_VIEW_ANALISTA')) ?>:</label>
		<span class="float-l"><?php echo $this->formSelect("cd_profissional",null,null,$this->arrProfissional); ?></span>
	  
    <label class="float-l clear-l span-4 right" for="tx_solicitante"><?php echo $this->escape($this->translate('L_VIEW_SOLICITANTE')) ?>:</label>
		<span class="float-l"><?php echo $this->formText("tx_solicitante",null,array('class'=>'span-10')); ?></span>
		  
    <label class="float-l clear-l span-4 right" for="cd_unidade"><?php echo $this->escape($this->translate('L_VIEW_UNIDADE')) ?>:</label>
		<span class="float-l"><?php echo $this->formSelect("cd_unidade",null,null,$this->arrUnidade); ?></span>
		  
    <button class="buttonBar verde" id="btn_gerar" name="btn_gerar" type="button"><?php echo $this->escape($this->translate('L_BTN_GERAR')) ?></button>
</form>