<div class="divTab">
	<div id="form_cadastro_pedido_mudanca">

		<?php echo $this->formHidden('acao_mudanca'); ?>
			
        <label class="span-3 float-l"><?php echo $this->escape($this->translate('L_VIEW_NOME_PROJETO')) ?>:</label>
		<span id="desc_projeto" class="float-l clear-r bold" style="margin-top: 3px;"></span>
	
		<label id="lb_proposta" class="span-3 float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_PROPOSTA')) ?>:</label>
		<span id="desc_proposta" class="float-l clear-r bold" style="margin-top: 3px;"></span>
	
		<label id="lb_requisito" class="span-3 float-l clear-l" style="display: none;"><?php echo $this->escape($this->translate('L_VIEW_REQUISITO')) ?>:</label>
		<span id="desc_requisito" class="float-l clear-r bold" style="margin-top: 3px; display: none;"></span>
		
		<label id="lb_regra_negocio" class="span-3 float-l clear-l" style="display: none;"><?php echo $this->escape($this->translate('L_VIEW_REGRA_DE_NEGOCIO')) ?>:</label>
		<span id="desc_regra_negocio" class="float-l clear-r bold" style="margin-top: 3px; display: none;"></span>
		
		<label id="lb_caso_de_uso" class="span-3 float-l clear-l" style="display: none;"><?php echo $this->escape($this->translate('L_VIEW_CASO_DE_USO')) ?>:</label>
		<span id="desc_caso_de_uso" class="float-l clear-r bold" style="margin-top: 3px; display: none;"></span>
	
		<hr class="span-21" style="border-top: 1px solid rgb(84, 189, 205); visibility: visible; height: 6px;"/>
	
		<label class=" bold span-4 float-l clear-l "><?php echo $this->escape($this->translate('L_VIEW_MOTIVO_MUDANCA')) ?>:</label>
		<?php echo $this->formTextarea('tx_motivo_mudanca', '', array('style' => 'width:550px; height:100px;','class'=>'clear-l float-l')) ?>
	
		<label class=" bold span-9 float-l clear-l"><?php echo $this->escape($this->translate('L_MSG_MUDANCA_AFETA_METRICA')) ?></label>
		<input type="radio" class="float-l" name="rd_mudanca_metrica" id="afeta_metrica" value="S"/>
		<span class="float-l span-2" style="margin-top: 3px;"><?php echo $this->escape($this->translate('L_VIEW_SIM')) ?></span>
		
		<input type="radio" class="float-l" style="margin-left: -15px;" name="rd_mudanca_metrica" id="nao_afeta_metrica" checked="checked" value="N"/>
		<span class="float-l span-2" style="margin-top: 3px;"><?php echo $this->escape($this->translate('L_VIEW_NAO')) ?></span>
		
		<label class=" bold span-9 float-l clear-l"><?php echo $this->escape($this->translate('L_MSG_CUSTO_PROVAVEL_MUDANCA')) ?>:</label>
		<?php echo $this->formText('qtd_horas','',array('class'=>'float-l span-3','style'=>'margin-left: 5px', 'maxlength'=>'10', 'disabled'=>'disabled', 'onKeyPress'=>'return soNumeros(event);')); ?>
	
		<label class=" bold span-9 float-l clear-l"><?php echo $this->escape($this->translate('L_MSG_FOI_REALIZADA_REUNIAO_PEDIDO_MUDANCA')) ?></label>
		<input type="radio" class="float-l" name="rd_reuniao_mudanca" id="reuniao_realizada" value="S" />
		<span class="float-l span-2" style="margin-top: 3px;"><?php echo $this->escape($this->translate('L_VIEW_SIM')) ?></span>
		
		<input type="radio" class="float-l" style="margin-left: -15px;" name="rd_reuniao_mudanca" id="reuniao_nao_realizada" checked="checked" value="N"/>
		<span class="float-l span-2" style="margin-top: 3px;"><?php echo $this->escape($this->translate('L_VIEW_NAO')) ?></span>
	
		<label class=" bold span-3 float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_DATA_REUNIAO')) ?>:</label>
		<?php echo $this->formSelect('cd_reuniao_pedido_mudanca','',array('class'=>'float-l span-3','disabled'=>'disabled')); ?>

	</div>
    <div style="margin-top: 15px;" class="float-l clear-l">
        <?php
            echo $this->formButton('btn_salvar_mudanca',$this->escape($this->translate('L_BTN_SALVAR')),array('class'=>'verde clear-l float-l'));
            echo $this->formButton('btn_cancelar_mudanca',$this->escape($this->translate('L_BTN_CANCELAR')),array('class'=>'vermelho float-l'));
        ?>
    </div>
</div>