<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableCondicaoSubItemMetrica").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableCondicaoSubItemMetrica").tablesorterPager({container: $("#tableCondicaoSubItemMetricaPager")});
});
</script>
<table id="tableCondicaoSubItemMetrica" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
			<th class="{sorter:false}" style="width: 20px;">&nbsp;</th>
			<th class="span-11"><?php echo $this->escape($this->translate('L_VIEW_GRID_CONDICAO')) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_VALOR'    )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):

    ?>
		<tr>
			<td><img id="imgExcluir"
                     height="13"
                     width="13"
                     style="cursor:pointer; text-align: center;"
                     onclick="excluirCondicaoSubItemMetrica(<?php echo $res['cd_condicao_sub_item_metrica']; ?>,
                                                            <?php echo $res['cd_sub_item_metrica']; ?>,
                                                            <?php echo $res['cd_item_metrica']; ?>,
                                                            <?php echo $res['cd_definicao_metrica']; ?>);"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/>
            </td>

            <?php
			    $fim = "";
				if(strlen($res['tx_condicao_sub_item_metrica']) >= 45){
					$fim = "...";
				}
				$tx_condicao_sub_item_metrica = substr($res['tx_condicao_sub_item_metrica'],0,45)
			?>

			<td onClick="recuperaCondicaoSubItemMetrica(<?php echo $res['cd_condicao_sub_item_metrica']; ?>,
                                                        <?php echo $res['cd_sub_item_metrica']; ?>,
                                                        <?php echo $res['cd_item_metrica']; ?>,
                                                        <?php echo $res['cd_definicao_metrica']; ?>)"
                style="cursor:pointer;"><?php echo $tx_condicao_sub_item_metrica.$fim; ?>
            </td>
            <td onClick="recuperaCondicaoSubItemMetrica(<?php echo $res['cd_condicao_sub_item_metrica']; ?>,
                                                        <?php echo $res['cd_sub_item_metrica']; ?>,
                                                        <?php echo $res['cd_item_metrica']; ?>,
                                                        <?php echo $res['cd_definicao_metrica'] ?>)"
                style="cursor:pointer;"><?php echo $res['ni_valor_condicao_satisfeita']; ?>
            </td>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableCondicaoSubItemMetricaPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>