<script type="text/javascript">
    $(document).ready(function() {
        $("#autoridades").tablesorter({widthFixed: true, widgets: ['zebra']});
        $("#autoridades").tablesorterPager({container: $("#autoridadesPager")});

    });
</script>
<table cellspacing="1" id="autoridades" class="tablesorter">
    <thead>
        <tr>
            <th class="span-4"><?php echo $this->escape($this->translate('L_VIEW_GRID_DESIGNACAO')) ?></th>
            <th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_NOME')) ?></th>
            <th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_EMAIL')) ?></th>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_UNIDADE')) ?></th>
        </tr>
    </thead>
    <tbody>
	<?php if($this->autoridades->valid()): ?>
			<?php foreach($this->autoridades as $rs): ?>
				<tr>
					<td style="text-align: center"><?php echo $this->formSelect("cmb_{$rs->cd_usuario_pedido}", $rs->st_autoridade, array('class'=>'span-4', 'onchange'=>"gravaDesignacao(this.value,{$rs->cd_usuario_pedido})"), $this->comboDesignacao); ?></td>
					<td style="cursor: pointer;" onClick="recuperaDadosAutoridade(<?php echo $rs->cd_usuario_pedido; ?>)"><?php echo $rs->tx_nome_usuario?></td>
					<td style="cursor: pointer;" onClick="recuperaDadosAutoridade(<?php echo $rs->cd_usuario_pedido; ?>)"><?php echo $rs->tx_email_institucional?></td>
					<td style="cursor: pointer;" onClick="recuperaDadosAutoridade(<?php echo $rs->cd_usuario_pedido; ?>)"><?php echo $rs->tx_sigla_unidade?></td>
				</tr>
			<?php endforeach; ?>
	<?php else:
            echo "<tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                  </tr>";
        endif; ?>
    </tbody>
</table>
<div id="autoridadesPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
		</select>
	</form>
</div>