<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableTipoDadoTecnico").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableTipoDadoTecnico").tablesorterPager({container: $("#tableTipoDadoTecnicoPager")}); 
});
</script>
<table id="tableTipoDadoTecnico" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_TIPO_DADO_TECNICO')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res):
		foreach ($this->res as $res):
	?>
		<tr><td onClick="redirecionaTipoDadoTecnico(<?php echo $res['cd_tipo_dado_tecnico'] ?>)" style="cursor:pointer;"><?php echo $res['tx_tipo_dado_tecnico'] ?></td></tr>
	<?php
		endforeach;
	else:
		echo "<tr><td>&nbsp;</td></tr>";
	endif;
	?>
	</tbody>
</table>
<div id="tableTipoDadoTecnicoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>