<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableSolicitacaoServicoConsulta").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableSolicitacaoServicoConsulta").tablesorterPager({container: $("#pager-solicitacao-servico-consulta")}); 
});
</script>
<table id="tableSolicitacaoServicoConsulta" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-1"><?php echo $this->escape($this->translate('L_VIEW_GRID_SOLICITACAO'          )) ?></th>
			<th class="span-1"><?php echo $this->escape($this->translate('L_VIEW_GRID_UNIDADE'              )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_DESCRICAO_SOLICITACAO')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
		$numero = (!is_null($res['solicitacao'])) ? $res['solicitacao'] : $res['cd_demanda'];
	?>
		<tr>
			<td>
				<a href="#" onclick="abreTabDetalheSolicitacao(<?php echo $res['cd_objeto']?>, <?php echo $res['ni_solicitacao']?>, <?php echo $res['ni_ano_solicitacao']?>, 5)"><?php echo $res['solicitacao'] ?></a>
			</td>
			<td><?php echo $res['tx_sigla_unidade'] ?></td>
			<td><?php echo substr(strip_tags($res['tx_solicitacao']),0,45)."..." ?></td>
		</tr>
	<?php
		endforeach;
	} else {
		echo "  <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	}
	?>
	</tbody>
</table>
<div id="pager-solicitacao-servico-consulta" class="pager">
<form><img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png"
	class="first" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png"
	class="prev" /> <input type="text" class="pagedisplay" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png"
	class="next" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png"
	class="last" /> <select class="pagesize">
	<option selected="selected" value="10">10</option>
	<option value="20">20</option>
	<option value="30">30</option>
	<option value="40">40</option>
</select></form>
</div>
