<?php
    $this->script('scriptFile',array('/gerenciamento-mudanca/analise-mudanca-caso-de-uso.js'));
?>
<div class="clear boxTab">
	<label class="float-l bold" style="margin-top:2px; font-size:16px;" id="mesAnoAnaliseMudancaCasoDeUso"><?php echo $this->mesAno ?></label>
	<label class="float-r" style="margin-top:2px;"><?php echo $this->anoCombo('anoAnaliseMudancaCasoDeUso', $this->anoComboValue,null,1) ?></label>
	<label class="float-r" style="margin-top:2px;"><?php echo $this->mesCombo('mesAnaliseMudancaCasoDeUso', $this->mesComboValue) ?></label>
</div>
<div id="gridGerenciamentoMudancaCasoDeUso"></div>