<?php 
    $this->script('validaForm');
    $this->script('scriptFile',array('/previsao-mensal-produtos-parcelas/index.js'));
?>
<form id="formRelatorioProjetoPrevisaoMensalProdutoParcela">

    <label class="span-2 float-l clear-l right required" for="cd_contrato"><?php echo $this->translate('L_VIEW_CONTRATO') ?>:</label>
		<?php echo $this->formSelect('cd_contrato',null,array('class'=>'float-l'),$this->arrContrato); ?>
    
    <label class="span-2 float-l clear-l right required" for="mes"><?php echo $this->translate('L_VIEW_MES') ?>:</label>
    	<?php echo $this->mesCombo("mes",null,array('class'=>'float-l')); ?>
    	
    <label class="span-2 float-l right clear-l required" for="ano"><?php echo $this->translate('L_VIEW_ANO') ?>:</label>
    	<?php echo $this->anoCombo("ano",null,array('class'=>'float-l')); ?>

    <label class="span-2 float-l right clear-l" for="cd_profissional_gerente"><?php echo $this->translate('L_VIEW_GERENTE') ?>:</label>
    	<?php echo $this->formSelect("cd_profissional_gerente", null, array('class'=>'float-l'), array('0'=>Base_Util::getTranslator('L_VIEW_COMBO_SELECIONE'))); ?>
    	
    <label class="span-2 float-l right clear-l" for="cd_projeto"><?php echo $this->translate('L_VIEW_PROJETO') ?>:</label>
    	<?php echo $this->formSelect("cd_projeto", null, array('class'=>'float-l'), array('0'=>Base_Util::getTranslator('L_VIEW_COMBO_SELECIONE'))); ?>
    	
    <label class="span-2 float-l right clear-l" for="cd_proposta"><?php echo $this->translate('L_VIEW_PROPOSTA') ?>:</label>
    	<?php echo $this->formSelect("cd_proposta", null, array('class'=>'float-l'),array('0'=>Base_Util::getTranslator('L_VIEW_COMBO_SELECIONE'))); ?>
    	
    <label class="span-2 float-l right clear-l" for="cd_parcela"><?php echo $this->translate('L_VIEW_PARCELA') ?>:</label>
    	<?php echo $this->formSelect("cd_parcela", null, array('class'=>'float-l'),array('0'=>Base_Util::getTranslator('L_VIEW_COMBO_SELECIONE'))); ?>
    
    <label class="span-2 float-l right clear-l" for="cd_unidade"><?php echo $this->translate('L_VIEW_UNIDADE') ?>:</label>
    	<?php echo $this->formSelect("cd_unidade", null, array('class'=>'float-l'),$this->arrUnidade); ?>

    <button class="buttonBar verde" id="btn_gerar" name="btn_gerar" type="button"><?php echo $this->translate('L_BTN_GERAR') ?></button>
</form>