<?php
    $this->script('validaForm');
    $this->script('scriptFile',array('/ata-de-reuniao/index.js'));
 ?>
<form id="formRelatorioAtaReuniao">

	<label class="span-2 right float-l required" for="cd_contrato"><?php echo $this->translate('L_VIEW_CONTRATO') ?>:</label>
		<?php echo $this->formSelect('cd_contrato',null,array('class'=>'float-l'),$this->arrContrato); ?>

    <label class="span-2 required clear-l float-l right" for="cd_projeto"><?php echo $this->translate('L_VIEW_PROJETO') ?>:</label>
    	<?php echo $this->formSelect("cd_projeto",null,array('class'=>'float-l'), array(0=>Base_Util::getTranslator('L_VIEW_COMBO_SELECIONE'))); ?>
	    <button class="verde float-l clear-l push-2" id="btn_gerar_ata_branco" name="btn_gerar_ata_branco" type="button" onclick="window.open('<?php echo $this->baseUrl();?>/relatorioProjeto/ata-de-reuniao/generate2')"><?php echo $this->translate('L_VIEW_GERAR_ATA_BRANCO') ?></button>
    <div id="relAtaReuniao" class="float-l clear-l bold push-2"></div>	
    	
</form>