<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableHistoricoExecucaoDemanda").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableHistoricoExecucaoDemanda").tablesorterPager({container: $("#pager_demanda_executada"), size: 5}); 
});
</script>
<?php  echo $this->formHidden('mesAnoDemandaExecutada',$this->mesAno) ?>
<table id="tableHistoricoExecucaoDemanda" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
			<th class="{sorter:false} span-1">&nbsp;</th>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_HORA_INICIO')) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_HORA_FIM'   )) ?></th>
			<th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_DESCRICAO'       )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr>
			<td>
				<img id="imgExcluir" 
                     height="13"
                     width="13"
                     style="cursor:pointer;"
                     onclick="excluirHistorico('<?php echo $res['cd_historico_execucao_demanda'] ?>');"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/>
			</td>
			<td style="cursor:pointer;" onclick="recuperaHistoricoDemanda('<?php echo $res['cd_historico_execucao_demanda'] ?>');">
				<?php echo date('d/m/Y H:i:s', strtotime($res['dt_inicio'])) ?>
			</td>
			<td style="cursor:pointer;" onclick="recuperaHistoricoDemanda('<?php echo $res['cd_historico_execucao_demanda'] ?>');">
				<?php echo date('d/m/Y H:i:s', strtotime($res['dt_fim']))?>
			</td>
			<td style="cursor:pointer;" onclick="recuperaHistoricoDemanda('<?php echo $res['cd_historico_execucao_demanda'] ?>');">
				<?php echo substr($res['tx_historico'],0,50)."..." ?>
			</td>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	}
	?>
	</tbody>
</table>
<div id="pager_demanda_executada" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="05">05</option>
			<option value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
		</select>
	</form>
</div>
