<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableDemandaSolicitada").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableDemandaSolicitada").tablesorterPager({container: $("#pager_demanda_solicitada")}); 
});
</script>
<?php  echo $this->formHidden('mesAnoDemandaSolicitada',$this->mesAno) ?>
<table id="tableDemandaSolicitada" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_HORA'        )) ?></th>
            <th class="span-1 {sorter:false}">
                <div class="float-l">P</div>
                <div class="float-l" style="margin-left: 18px;">T</div>
            </th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_NUMERO'           )) ?></th>
			<th class="span-4"><?php echo $this->escape($this->translate('L_VIEW_GRID_DESCRICAO_DEMANDA')) ?></th>
			<th class="span-4"><?php echo $this->escape($this->translate('L_VIEW_GRID_NIVEL_SERVICO'    )) ?></th>
			<th class="span-1 {sorter:false}"><?php echo $this->escape($this->translate('L_VIEW_GRID_SITUACAO')) ?></th>
			<th class="span-1 {sorter:false}"><?php echo $this->escape($this->translate('L_VIEW_GRID_REGISTRAR')) ?></th>
			<th class="span-1 {sorter:false}"><?php echo $this->escape($this->translate('L_VIEW_GRID_FINALIZAR')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	$dataHoraAgora = date("Y-m-d H:i:s");
	if($this->res):
		foreach ($this->res as $res):
			$minutosParaLeitura = $this->datediff($res['dt_demanda_nivel_servico'], $dataHoraAgora);
			$numero = (!is_null($res['ni_solicitacao'])) ? "{$res['ni_solicitacao']}/{$res['ni_ano_solicitacao']}" : $res['cd_demanda'];
	?>
		<tr <?php if (is_null($res['dt_leitura_nivel_servico'])) {?> class="negrito" <?php }?>>
			<td>
				<?php if(is_null($res['dt_leitura_nivel_servico'])) : ?>
							<a class="float-l" href="<?php echo $this->baseUrl()?>/demanda-executor-demanda/demanda-detalhes/cd_demanda/<?php echo $res['cd_demanda']?>/cd_nivel_servico/<?php echo $res['cd_nivel_servico'] ?>">
                                <?php echo date('d/m/Y H:i:s', strtotime($res['dt_demanda'])) ?>
                            </a>
							<button class="icon imprimir" onclick="abrePopUp('<?php echo $this->baseUrl()?>/relatorioDemanda/demanda-detalhe/demanda-detalhe/cd_objeto/<?php echo $res['cd_objeto']?>/ni_solicitacao/<?php echo $res['ni_solicitacao']?>/ni_ano_solicitacao/<?php echo $res['ni_ano_solicitacao']?>/cd_demanda/<?php echo $res['cd_demanda']?>');" title="<?php echo $this->escape($this->translate('L_VIEW_IMPRIMIR_RELATORIO_DEMANDA'))?>"></button>
				<?php else : ?>
                            <a class="float-l" href="<?php echo $this->baseUrl()?>/demanda-executor-demanda/demanda-executada-detalhes/cd_demanda/<?php echo $res['cd_demanda'] ?>/cd_nivel_servico/<?php echo $res['cd_nivel_servico'] ?>/abaOrigem/demanda-solicitada">
                                <?php echo date('d/m/Y H:i:s', strtotime($res['dt_demanda'])) ?>
                            </a>
							<button class="icon imprimir" onclick="abrePopUp('<?php echo $this->baseUrl()?>/relatorioDemanda/demanda-detalhe/demanda-detalhe/cd_objeto/<?php echo $res['cd_objeto']?>/ni_solicitacao/<?php echo $res['ni_solicitacao']?>/ni_ano_solicitacao/<?php echo $res['ni_ano_solicitacao']?>/cd_demanda/<?php echo $res['cd_demanda']?>');" title="<?php echo $this->escape($this->translate('L_VIEW_IMPRIMIR_RELATORIO_DEMANDA'))?>"></button>
				<?php endif; ?>
			</td>
            <td>
                <!-- rotina para desenhar a bolhinha das prioridades -->
                <?php
                    $prioridade = $this->escape($this->translate('L_VIEW_PRIORIDADE'));
                    $paramsDivPrioridade = ($res['tx_rgb_status_atendimento']) ? " title=\"{$prioridade} {$res['tx_status_atendimento']}\" style=\"background-color: #{$res['tx_rgb_status_atendimento']}\"" : '';
                ?>
                <div class="circleColorPriority float-l" <?php echo $paramsDivPrioridade?>></div>

                <!-- rotina para desenhar a bolhinha do tempo de execução da demanda -->
                <?php if (!is_null($res['cd_demanda'])):
                    $tempo = $this->escape($this->translate('L_VIEW_TEMPO_RESPOSTA'));
                    $paramsDivTempoResposta = " title=\"{$tempo} {$this->arrTempoRespostaDemanda[$res['cd_demanda']][$res['cd_nivel_servico']]['tempo_resposta']}\" style=\"background-color: #{$this->arrTempoRespostaDemanda[$res['cd_demanda']][$res['cd_nivel_servico']]['cor']}\"";
                ?>
                <div class="circleColorTime float-l" <?php echo $paramsDivTempoResposta?>></div>
                <?php endif;?>

            </td>
			<td><?php echo $numero ?></td>
			<td><?php echo substr(strip_tags($res['tx_demanda']),0,30)."..." ?></td>
			<td><?php echo $res['tx_nivel_servico'] ?></td>
			<td class="center">
				<?php if (is_null($res['dt_leitura_nivel_servico'])): ?>
                        <?php if ($minutosParaLeitura > 30): ?>
                                    <button class="icon justificar"
                                            onClick="abreModalJustificar('<?php echo $res['cd_demanda']?>', '<?php echo date('d/m/Y H:i:s', strtotime($res['dt_demanda_nivel_servico']))?>', <?php echo $res['cd_nivel_servico'] ?>)"
                                            id="button_justificar_<?php echo $res['cd_demanda']?>"
                                            title="<?php echo $this->escape($this->translate('L_BTN_JUSTIFICAR')) ?>">
                                    </button>
                        <?php else: ?>
                                        <button class="icon tempo_leitura"
                                                onClick="abreModalJustificar('<?php echo $res['cd_demanda']?>', '<?php echo date('d/m/Y H:i:s', strtotime($res['dt_demanda']))?>', <?php echo $res['cd_nivel_servico'] ?>)"
                                                id="button_justificar_<?php echo $res['cd_demanda']?>"
                                                title="<?php echo (30-$minutosParaLeitura) . " ".$this->escape($this->translate('L_VIEW_MINUTOS_PARA_LEITURA')) ?>">
                                        </button>
                        <?php endif;
                    else:
                        $minutosAteLeitura = $this->datediff($res['dt_demanda_nivel_servico'], $res['dt_leitura_nivel_servico']);
                        if (is_null($res['tx_justificativa_nivel_servico'])):
                            if($minutosAteLeitura > 30): ?>
                                <button class="icon justificar"
                                        onClick="abreModalJustificar('<?php echo $res['cd_demanda']?>', '<?php echo date('d/m/Y H:i:s', strtotime($res['dt_demanda']))?>', <?php echo $res['cd_nivel_servico'] ?>)"
                                        id="button_justificar_<?php echo $res['cd_demanda']?>"
                                        title="<?php echo $this->escape($this->translate('L_BTN_JUSTIFICAR')) ?>">
                                </button>
					<?php							
                            endif;
                        else: 
                            echo $this->escape($this->translate('L_VIEW_JUSTIFICADA'));
                        endif;
					endif;  
                ?>
			</td>
			<td class="center">
                <?php if(!is_null($res['dt_leitura_nivel_servico'])): ?> 
                    <button class="icon registrar_exec"
                            onClick="registraExecucaoDemanda(<?php echo $res['cd_demanda']?>,<?php echo $res['cd_nivel_servico'] ?>)"
                            id="button_registrar_<?php echo $res['cd_demanda']?>"
                            title="<?php echo $this->escape($this->translate('L_BTN_REGISTRAR_EXECUCAO')) ?>">
                    </button>
				<?php else: ?>
					&nbsp; 
				<?php endif; ?>
			</td>
			<td class="center">
                <?php if(!is_null($res['dt_leitura_nivel_servico']) && $res['st_historico'] != 'N'): ?>
                    <button class="icon concluir_exec"
                            onClick="fecharExecucaoDemanda('<?php echo $res['cd_demanda']?>',<?php echo $_SESSION['oasis_logged'][0]['cd_profissional'] ?>,<?php echo $res['cd_nivel_servico'] ?>)"
                            id="button_salvar_<?php echo $res['cd_demanda']?>"
                            title="<?php echo $this->escape($this->translate('L_BTN_FINALIZAR_EXECUCAO')) ?>">
                    </button>
				<?php else: ?>
                            &nbsp;
				<?php endif; ?>
			</td>
		</tr>
	<?php
		endforeach;
	else:
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	endif;
	?>
	</tbody>
</table>
<div id="pager_demanda_solicitada" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
