<?php
    $this->script('scriptFile',array('/produto-parcela/index.js'));
?>
<div style="margin-left:5px;">
	<?php
		echo $this->formHidden('cd_parcela_produto_cad');
		echo $this->formHidden('cd_produto_parcela');
		echo $this->formHidden('escondeExclusao',$this->escondeExclusao);
	?>
	<div style="overflow:hidden; margin-bottom:25px; padding-bottom:15px;">
		<label class="span-3 float-l bold"><?php echo $this->translate('L_VIEW_PROJETO') ?>:</label>
            <p class="span-15 float-l"><?php echo $this->nomeProjeto ?></p>
            <label class="span-3 float-l clear-l bold"><?php echo $this->escape($this->translate('L_VIEW_PROPOSTA')) ?>:</label>
            <p class="span-3 float-l"><?php echo $this->cd_proposta ?></p>
	</div>

	<div class="span-5 float-l clear-l" style="border-right:1px solid rgb(84, 189, 205); margin-top: -30px;">
		<label class="span-5 bold" style="padding-right:0;"><?php echo $this->escape($this->translate('L_VIEW_LISTA_PARCELAS')) ?>:
			<br />
			<span class="small"><?php echo $this->escape($this->translate('L_MSG_SELECIONE_PARCELA_PARA_INCLUSAO_ALTERACAO_PRODUTO')) ?></span>
		</label>
		<div id="produtosParcelas">
			<label class="clear-l span-5" style="padding-right:0;"><?php echo $this->escape($this->translate('L_VIEW_COM_PRODUTO_CADASTRADO')) ?>:</label>
			<div id="parcelaComProduto" class="span-5" style="margin-top: -8px; margin-bottom: 5px;"></div>

			<label class="span-5 clear" style="padding-right:0;"><?php echo $this->escape($this->translate('L_VIEW_SEM_PRODUTO_CADASTRADO')) ?>:</label>
			<div id="parcelaSemProduto" class="span-5" style="margin-top: -8px;"></div>
		</div>
	</div>
	<div class="span-15 float-l" style="margin-top: -30px;">
		<label class="span-2 bold float-l"><?php echo $this->escape($this->translate('L_VIEW_PARCELA')) ?>:</label>
		<p class="bold span-3 float-l" id="numeroParcela"></p>
        <label class="span-4 bold float-l"><?php echo $this->escape(Base_Util::getTranslator('L_VIEW_QTD_VARIAVEL', $this->unidadePadraoMetrica)) ?>:</label>
		<p class="bold span-3 float-l" id="quantHoras"></p>

		<label class="span-2 bold float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_PRODUTO')) ?>:</label>
		<!-- <input class="float-l" id="descProdutoParcela" name="descProdutoParcela" type="text" value="" style="width:265px;"/> -->
		<textarea class="float-l" id="descProdutoParcela" name="descProdutoParcela" rows="3" style="width:506px;"/></textarea>
		<label class="span-2 bold float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_TIPO')) ?>:</label>
		<?php echo $this->formSelect('cd_tipo_produto',null,array('class'=>'float-l'), $this->arrTipoProduto) ?>
	
        <div class="float-l clear-l push-2 ">
            <button id="salvarProdutoParcela" type="button" class="verde float-r" onclick="salvarProdutoParcela();">
                <?php echo $this->escape($this->translate('L_BTN_SALVAR')) ?>
            </button>
            <button id="alterarProdutoParcela" type="button" class="verde float-r" onclick="alterarProdutoParcela();">
                <?php echo $this->escape($this->translate('L_BTN_SALVAR')) ?>
            </button>
            <button id="cancelarProdutoParcela" type="button" class="azul float-r" onclick="cancelarProdutoParcela();">
                <?php echo $this->escape($this->translate('L_BTN_CANCELAR')) ?>
            </button>
        </div>
        
		<div class="span-15" id="gridProdutoParcela" style="padding-left: 10px;"></div>
	</div>
</div>
<div class="accordionBottom">
	<label class="bold span-18 right float-l" style="color: red;"><?php echo Base_Util::getTranslator('L_MSG_ALERT_CLIQUE_PARA_REGISTRAR_OPERACAO', $this->escape($this->translate('L_BTN_CONFIRMAR'))) ?></label>
	<button type="button" class="verde" id="bt_confirmar_produtos" name="bt_confirmar_produtos"><?php echo $this->escape($this->translate('L_BTN_CONFIRMAR')) ?></button>
</div>