<?php 
 	$this->script('grid');
	$this->script('tab'); 
	$this->script('validaForm'); 
	$this->script('editorHtml');
    $this->script('numero');
    $this->script('scriptFile',array('/elaboracao-proposta/index.js',
                                     '/situacao-projeto/index.js'));
?>
<script type="text/javascript">
	var openAccordionElaboracao = '<?php echo $this->openAccordion; ?>';
</script>
<h2><?php echo $this->escape($this->translate('L_VIEW_ELABORACAO_PROPOSTA')) ?></h2>
<div class="box span-11 border gradient">
	<h3 class="highlight tarja-1"><?php echo $this->escape($this->translate('L_VIEW_RESUMO_SOLICITACAO')) ?></h3>
    <label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_NUMERO_SOLICITACAO')) ?>:</label>
        <p class="span-6">
            <a href="#" onclick="abrePopupResumoSolicitacaoServico()">
                <?php echo "{$this->solicitacao['ni_solicitacao']}/{$this->solicitacao['ni_ano_solicitacao']}" ?>
            </a>
        </p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_OBJETO_CONTRATO')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['tx_objeto'] ?></p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_DATA_SOLICITACAO')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['dt_solicitacao'] ?></p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_GESTOR_SOLICITANTE')) ?></label>
        <p class="span-6"></p>

	<hr style="width:420px;"/>
	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_NOME')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['tx_solicitante']; ?></p>
	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_UNIDADE')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['tx_sigla_unidade']; ?></p>
	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_SALA')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['tx_sala_solicitante']; ?></p>
	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_TELEFONE')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['tx_telefone_solicitante']; ?></p>
</div>
<?php 
	echo $this->formHidden('cd_proposta',$this->cd_proposta);
	echo $this->formHidden('cd_projeto', $this->cd_projeto);
	echo $this->formHidden('st_parcela_orcamento', $this->st_parcela_orcamento);
	echo $this->formHidden('ni_porcentagem_parc_orcamento', $this->ni_porcentagem_parc_orcamento);
?>
<!-- Situação do projeto -->
<?php if(ChecaPermissao::possuiPermissao('situacao-projeto') === true): ?>
	<div class="box border span-10 gradient" id="box_posicionamento"></div>
	<!-- Accordion da situação do projeto  -->
<?php endif; ?>
<hr />

<?php if(ChecaPermissao::possuiPermissao('projeto') === true && $_SESSION['oasis_logged'][0]['cd_perfil'] != K_CODIGO_PERFIL_TECNICO): ?>
	<?php if((int)$this->cd_proposta > 1): ?>
		<hr />
		<div id="objetivo_proposta" class="accordion-closed">
            <span><?php echo $this->escape($this->translate('L_VIEW_ACCORDION_OBJETIVO_PROPOSTA')) ?></span>
        </div>
		<div id="form_objetivo_proposta" accordion="accordion" class="hide accordion">
			<?php echo $this->render('elaboracao-proposta/objetivo-proposta.phtml') ?>
		</div>
	<?php endif; ?>
<div id="descricao_proposta" class="accordion-closed">
    <span><?php echo $this->escape($this->translate('L_VIEW_ACCORDION_DESCRICAO_PROJETO')) ?></span>
</div>
<div id="form_descricao_proposta" accordion="accordion" class="accordion hide">
		<?php echo $this->formDescricaoProjeto; ?>
<label class="bold span-19 right float-l" style="color: red;"><?php echo Base_Util::getTranslator('L_MSG_ALERT_CLIQUE_PARA_REGISTRAR_OPERACAO', $this->escape($this->translate('L_BTN_CONFIRMAR'))) ?></label>
<div id="btSalvarProposta"><?php echo $this->formButton('btn_salvar_descricao_projeto', $this->escape($this->translate('L_BTN_CONFIRMAR')), array('class' => 'verde float-r')) ?></div>
</div>
<?php endif; ?>

<?php echo $this->formHidden('config_hidden_alocar_profissional','N') ?>
<?php if(ChecaPermissao::possuiPermissao('associar-profissional-projeto') === true): ?>
	<div id="alocar_profissionais" class="accordion-closed" onclick="if(($(this).hasClass('accordion-closed'))){verificaStatusAccordionAlocarProfissional();}">
        <span><?php echo $this->escape($this->translate('L_VIEW_ACCORDION_ALOCAR_PROFISSIONAL')) ?></span>
    </div>
	<div id="form_alocar_profissionais" accordion="accordion" class="hide accordion">
		<?php echo $this->render('associar-profissional-projeto/index.phtml') ?>
		<div class="accordionBottom">
			<label class="bold span-18 right float-l" style="color: red; margin-left: 20px;"><?php echo Base_Util::getTranslator('L_MSG_ALERT_CLIQUE_PARA_REGISTRAR_OPERACAO', $this->escape($this->translate('L_BTN_CONFIRMAR'))) ?></label>
			<button type="button" class="verde" id="bt_confirmar_profissional" name="bt_confirmar_profissional"><?php echo $this->escape($this->translate('L_BTN_CONFIRMAR')) ?></button>
		</div>	
	</div>
<?php endif; ?>

<?php if($_SESSION['oasis_logged'][0]['cd_perfil'] != K_CODIGO_PERFIL_TECNICO): ?>
<?php echo $this->formHidden('config_hidden_metrica_dinamica','N') ?>
	<div id="metrica_dinamica" class="accordion-closed" onclick="if(($(this).hasClass('accordion-closed')) && ($('#config_hidden_metrica_dinamica').val() == 'N')){configMetricaDinamica();}" >
        <span><?php echo $this->escape($this->translate('L_VIEW_ACCORDION_METRICA')) ?></span>
    </div>
	<div id="form_aplicacao_metrica_dinamica" accordion="accordion" class="hide accordion">
		<?php echo $this->render('elaboracao-proposta/metrica-dinamica.phtml') ?>
	</div>
<?php endif; ?>

<?php echo $this->formHidden('config_hidden_modulo','N') ?>
<?php if(ChecaPermissao::possuiPermissao('modulo') === true && $_SESSION['oasis_logged'][0]['cd_perfil'] != K_CODIGO_PERFIL_TECNICO): ?>
	<div id="gerenciar_modulos" class="accordion-closed" onclick="if(($(this).hasClass('accordion-closed')) && ($('#config_hidden_modulo').val() == 'N')){configModulo();}">
        <span><?php echo $this->escape($this->translate('L_VIEW_ACCORDION_GERENCIAR_MODULO')) ?></span>
    </div>
	<div id="form_gerenciar_modulos" accordion="accordion" class="accordion hide">
		<?php echo $this->render('modulo/index.phtml') ?>
	</div>
<?php endif; ?>

<?php echo $this->formHidden('config_hidden_criacao_parcela','N') ?>
<?php  if(ChecaPermissao::possuiPermissao('criacao-parcelas') === true): ?>
	<div id="criar_parcelas" class="accordion-closed" onclick="if(($(this).hasClass('accordion-closed')) && ($('#config_hidden_criacao_parcela').val() == 'N')){configCriacaoParcela();}">
        <span><?php echo $this->escape($this->translate('L_VIEW_ACCORDION_CRIAR_PARCELA')) ?></span>
    </div>
	<div id="form_criar_parcelas" accordion="accordion" class="hide accordion">
	<?php echo $this->render('elaboracao-proposta/criar-parcelas.phtml') ?></div>
<?php endif; ?>

<?php echo $this->formHidden('config_hidden_acrescentar_produto','N'); ?>
<?php  if(ChecaPermissao::possuiPermissao('acrescentar-produtos') === true): ?>
	<div id="acrescentar_produtos" class="accordion-closed" onclick="if(($(this).hasClass('accordion-closed')) && ($('#config_hidden_acrescentar_produto').val() == 'N')){configAcrescentarProdutos();}">
        <span><?php echo $this->escape($this->translate('L_VIEW_ACCORDION_ACRESCENTAR_PRODUTO')) ?></span>
    </div>
	<div id="form_acrescentar_produtos" accordion="accordion" class="hide accordion">
	<?php echo $this->render('elaboracao-proposta/acrescentar-produtos.phtml') ?></div>
<?php endif; ?>

<?php echo $this->formHidden('config_hidden_requisito_proposta','N') ?>
<?php if(ChecaPermissao::possuiPermissao('requisito-proposta') === true): ?>
	<div id="requisitos_proposta" class="accordion-closed" onclick="if($(this).hasClass('accordion-closed') && ($('#config_hidden_requisito_proposta').val() == 'N')){configRequisitoProposta();}">
        <span><?php echo $this->escape($this->translate('L_VIEW_ACCORDION_REQUISITO')) ?></span>
    </div>
	<div id="form_requisitos_proposta" accordion="accordion" class="hide accordion">
        <?php echo $this->render('requisito-proposta/index.phtml') ?>
		<div class="accordionBottom">
			<label class="bold span-18 right float-l" style="color: red; margin-left: 20px;"><?php echo Base_Util::getTranslator('L_MSG_ALERT_CLIQUE_PARA_REGISTRAR_OPERACAO', $this->escape($this->translate('L_BTN_CONFIRMAR'))) ?></label>
			<button type="button" class="verde" id="bt_confirmar_requisito" name="bt_confirmar_requisito"><?php echo $this->escape($this->translate('L_BTN_CONFIRMAR')) ?></button>
		</div>
    </div>
<?php endif; ?>
	
<?php  if(ChecaPermissao::possuiPermissao('documentacao-projeto') === true): ?>
	<div id="arquivos_proposta" class="accordion-closed">
        <span><?php echo $this->escape($this->translate('L_VIEW_ACCORDION_ARQUIVO_PROPOSTA')) ?></span>
    </div>
	<div id="form_arquivos_proposta" accordion="accordion" class="hide accordion">
	<?php echo $this->render('documentacao-projeto/index.phtml') ?></div>
<?php endif; ?>

<?php echo $this->formButton('btn_relatorio', $this->escape($this->translate('L_BTN_RELATORIO_PLANO_PROJETO')),array('class'=>'buttonBar verde',"onclick"=>"window.open('{$this->baseUrl()}/relatorioProjeto/documento-proposta/documento-proposta/cd_projeto/{$this->cd_projeto}/cd_proposta/{$this->cd_proposta}/tipo_proposta/C')")) ?>

<!--
    Esta div é usada para renderizar o conteúdo do link do Nr da Solicitação
    para a visualização da solicitação de serviço
-->
<div class="float-l clear-l" id="div_desc_solicitacao_servico" style="display:none;">
    <div style="padding: 10px;">
        <div class="float-l">
            <label class="bold span-3 float-l"><?php echo $this->escape($this->translate('L_VIEW_SOLICITACAO')) ?>:</label>
            <span class="float-l span-11" style="text-align: justify;"><?php echo $this->solicitacao['tx_solicitacao']; ?></span>
        </div>
        <hr class="clear-l float-l push-3 span-11"/>
        <div class="float-l">
            <label class="bold span-3 float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_OBSERVACAO')) ?>:</label>
            <span class="float-l span-11" style="text-align: justify;"><?php echo $this->solicitacao['tx_obs_solicitacao']; ?></span>
        </div>
    </div>
</div>