<?php
    $this->script('scriptFile',array('/documentacao-projeto/index.js'));
    $this->script('uploadAjax');
?>
<div class="span-20" style="margin-left: 22px;" id="formDocumentoProposta">
	<?php
		echo $this->formHidden('cd_projeto', $this->cd_projeto);
		echo $this->formHidden('cd_proposta', $this->cd_proposta);
	?>
	<label class="span-3 float-l bold"><?php echo $this->translate('L_VIEW_PROJETO') ?>:</label>
    	<p class="span-15 float-l"><?php echo $this->nomeProjeto; ?></p>
        <label class="span-3 float-l clear-l bold"><?php echo $this->escape($this->translate('L_VIEW_PROPOSTA')) ?>:</label>
    	<span class="span-15 float-l"><?php echo $this->cd_proposta; ?></span>
    <label class="bold span-4 clear-l" style="margin-bottom: -7px;"><?php echo $this->escape($this->translate('L_VIEW_DOCUMENTOS')) ?></label>
    	<p class="span-6"/>
	<hr style="border-top:1px solid #54BDCD; visibility:visible; height: 6px;" class="span-20"/>
	<div id="divExtensao" style="display: none;">
		<label class="span-3 float-l clear-l right"><?php echo $this->escape($this->translate('L_VIEW_EXTENSOES')) ?>:</label>
	    	<span class="span-6 float-l bold" id="extensoes"></span>
	</div>
	<label class="span-3 float-l clear-l right required" for="cd_tipo_documentacao" ><?php echo $this->escape($this->translate('L_VIEW_DOCUMENTACAO')) ?>:</label>
		<?php echo $this->formSelect('cd_tipo_documentacao', null, array('class' => 'float-l'), $this->tipoDocumentacaoCombo); ?>

    <label class="span-3 float-l clear-l right required" for="tx_arq_documentacao_projeto"><?php echo $this->escape($this->translate('L_VIEW_ARQUIVO')) ?>:</label>
		<?php echo $this->formFile('tx_arq_documentacao_projeto', array('class'=>'float-l span-3','size'=>'50')); ?>
	<img id="imgLoad" name="imgLoad" alt="<?php echo $this->escape($this->translate('L_VIEW_AGUARDE')) ?>"
         src="<?php echo $this->baseUrl()?>/public/img/ajax-loader.gif" width="220px" height="19px"
         class="float-l clear-l push-3" style="display:none;" />
	<button class="float-l verde clear-l push-3" onclick="return _fnUploadDocumentacaoProjeto();"><?php echo $this->escape($this->translate('L_BTN_ANEXAR_ARQUIVO')) ?></button>
	<div id="gridDocumentacaoProjeto" class="float-l clear-l push-1 span-15"></div>
</div>
<div class="accordionBottom">
	<label class="bold span-18 right float-l" style="color: red;">
        <?php echo Base_Util::getTranslator('L_MSG_ALERT_CLIQUE_PARA_REGISTRAR_OPERACAO', $this->escape($this->translate('L_BTN_CONFIRMAR'))) ?>
    </label>
	<button type="button" class="verde" id="bt_confirmar_documento_proposta" name="bt_confirmar_documento_proposta">
        <?php echo $this->escape($this->translate('L_BTN_CONFIRMAR')) ?>
    </button>
</div>