<script type="text/javascript">
$(document).ready(function() {
    $("#respostas").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#respostas").tablesorterPager({container: $("#respostasPager")});
});
</script>
<table cellspacing="1" id="respostas" class="tablesorter">
    <thead>
        <tr>
            <th class="{sorter: false}" style="width:10px;">&nbsp;</th>
            <th class="span-20"><?php echo $this->escape($this->translate('L_VIEW_GRID_RESPOSTA')) ?></th>
        </tr>
    </thead>
    <tbody>
<?php if(count($this->respostas)): ?>
    <?php foreach($this->respostas as $resposta): ?>
        <tr>
            <td><img id="imgExcluir" height="13" width="13" style="cursor:pointer; text-align: center;" onclick="excluirRespostaPedido('<?php echo $resposta->cd_resposta_pedido ?>');" src="<?php echo $this->baseUrl()?>/public/img/del.png" alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/></td>
            <td style="cursor:pointer;" onclick="recuperaRespostaPedido(<?php echo $resposta->cd_resposta_pedido ?>)"><?php echo $resposta->tx_titulo_resposta ?></td>
        </tr>
    <?php endforeach; ?>
<?php else:
        echo " <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
              </tr>";
      endif; ?>
    </tbody>
</table>
<div id="respostasPager" class="pager">
    <form>
        <img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
        <img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
        <input type="text" class="pagedisplay"/>
        <img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
        <img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
        <select class="pagesize">
            <option selected="selected"  value="10">10</option>
            <option value="20">20</option>
            <option value="30">30</option>
            <option value="40">40</option>
        </select>
    </form>
</div>