<div class="divTab">
	<div class="clear boxTab">
        <input type="hidden" value="<?php echo $this->cd_projeto_regra_negocio; ?>" id="cd_projeto_regra_negocio" name="cd_projeto_regra_negocio" />
        <button id="btn_nova_regra_negocio" class="azul float-r" style="margin: 0 5px 5px 5px;" onclick="habilitaAbaRegraNegocio()"><?php echo mb_strtoupper($this->escape($this->translate('L_BTN_NOVA_REGRA_NEGOCIO')), 'utf-8') ?></button>
    </div>
	<div id="gridRegraNegocio"></div>
</div>