<div class="divTab">
	<?php echo $this->formHidden( 'cd_regra_negocio' ); ?>
    <label class="bold float-l right span-4 required" for="tx_regra_negocio" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_REGRA_DE_NEGOCIO')) ?>:</label>
	<?php echo $this->formText( 'tx_regra_negocio', null ,array('class'=>'span-10 float-l') ); ?>
	<label class="bold float-l right span-4 clear-l" for="st_regra_negocio" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_INATIVO')) ?>:</label>
    <input type="checkbox" class="float-l" value="I" id="st_regra_negocio" name="st_regra_negocio" />
    <label class="bold float-l right span-4 clear-l required" for="tx_descricao_regra_negocio" editor="editor" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_DESCRICAO')) ?>:</label>
	<?php 
	    echo $this->editorHtml( 'tx_descricao_regra_negocio', null, array('class'=>'float-l','cols'=>'60','rows'=>'13','editor'=>K_EDITOR));
		echo $this->formButton(
		         'btn_salvar_regra_negocio', 
		         $this->escape($this->translate('L_BTN_SALVAR')),
		         array(
		             'class' => 'verde float-l push-4 clear-l',
		             'onclick' => 'salvarRegraNegocio()'
		         ));
		echo $this->formButton(
		         'btn_cancelar_regra_negocio', 
		         $this->escape($this->translate('L_BTN_CANCELAR')),
		         array(
		             'class' => 'vermelho float-l push-4',
		             'onclick' => 'cancelarRegraNegocio()'
		         ));
	?>
</div>