<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableCOPreDemanda").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableCOPreDemanda").tablesorterPager({container: $("#pager_COPreDemanda")}); 
});
</script>
<?php  echo $this->formHidden('mesAnoCoodenador',$this->mesAno) ?>
<table id="tableCOPreDemanda" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_HORA'      )) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_SOLICITANTE'    )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_OBJETO_EXECUTOR')) ?></th>
			<th class="span-4"><?php echo $this->escape($this->translate('L_VIEW_GRID_DESCRICAO'      )) ?></th>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_SITUACAO'       )) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_SOLICITACAO'    )) ?></th>
			<th class="span-3">&nbsp;</th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
			if($res['ni_solicitacao'] == ""){
				$dt_solicitacao = "XX/XXXX";
				$button = "<button id='btn_encaminhar' class='verde span-3' onclick='encaminharPreDemanda({$res['cd_pre_demanda']});'>".$this->escape($this->translate('L_BTN_ENCAMINHAR'))."</button>";
			} else {
				$dt_solicitacao = $res['ni_solicitacao']."/".$res['ni_ano_solicitacao'];
				$button = "&nbsp;";
			}
	?>
			<tr>
				<td>
                    <a href="<?php echo $this->baseUrl()?>/coordenador-pre-demanda/pre-demanda-detalhes/cd_pre_demanda/<?php echo $res['cd_pre_demanda']?>/abaOrigem/pre-demandas">
                        <?php echo date('d/m/Y H:i:s', strtotime($res['dt_pre_demanda'])); ?>
                    </a>
                </td>
				<td><?php echo $res['tx_nome_conhecido'] ?></td>
				<td><?php echo $res['tx_objeto'] ?></td>
				<td><?php echo substr(strip_tags($res['tx_pre_demanda']),0,30)."..." ?></td>
				<td><?php echo $res['situacao'] ?></td>
                <td><?php echo $dt_solicitacao ?></td>
				<td><?php echo $button ?></td	 >
			</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
                    <td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	}
	?>
	</tbody>
</table>
<!--   precisar de botões para paginador --> 
<div id="pager_COPreDemanda" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
