<div style="background-color:#fbfbfb;">
	<div class="highlight" style="padding:5px">
		<h2><?php echo $this->translate('L_MSG_ALERT_TELA_AJUDA_INDISPONIVEL') ?></h2>
	</div>
	<div style="height:473px; overflow-x:hidden; overflow-y:scroll; padding:8px 10px;">
		<img src="<?php  echo $this->baseUrl();?>/public/img/logo.png" alt="<?php echo $this->translate('L_MSG_ALERT_TELA_AJUDA_INDISPONIVEL') ?>" />
		<p> <?php echo $this->translate('L_MSG_ALERT_TELA_AJUDA_INDISPONIVEL') ?> </p>
	</div>
</div>