<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableGrupoFatorItem").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableGrupoFatorItem").tablesorterPager({container: $("#tableGrupoFatorItemPager")}); 
});
</script>
<table id="tableGrupoFatorItem" cellspacing="1" class="tablesorter" style="border-collapse: collapse;">
	<thead>
		<tr>
			<th class="{sorter: false}" style="width: 15px;">&nbsp;</th>
            <th class="span-18"><?php echo $this->escape($this->translate('L_VIEW_GRID_ITEM_GRUPO_FATOR')) ?></th>
			<th class="span-3" ><?php echo $this->escape($this->translate('L_VIEW_GRID_NR_ORDEM'        )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr>
			<td><img id="imgExcluir"
                     height="13"
                     width="13"
                     style="cursor:pointer;"
                     onclick="excluirGrupoFatorItem('<?php echo $res['cd_item_grupo_fator'] ?>');"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/>
            </td>
			<td onClick="recuperaGrupoFatorItem(<?php echo $res['cd_item_grupo_fator'] ?>)" style="cursor:pointer;">
				<?php echo $res['tx_item_grupo_fator'] ?>
			</td>
			<td onClick="recuperaGrupoFatorItem(<?php echo $res['cd_item_grupo_fator'] ?>)" style="cursor:pointer;">
				<?php echo $res['ni_ordem_item_grupo_fator'] ?>
			</td>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableGrupoFatorItemPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
