<form id="formConclusaoSolicitacao" style="margin-left: 10px;">

	<?php echo $this->formHidden('cd_objeto_conclusao_solicitacao', $this->cd_objeto); ?>
	<?php echo $this->formHidden('ni_solicitacao_conclusao_solicitacao', $this->ni_solicitacao); ?>
	<?php echo $this->formHidden('ni_ano_solicitacao_conclusao_solicitacao', $this->ni_ano_solicitacao); ?>

	<label class="float-l span-5 bold"><?php echo $this->escape($this->translate('L_VIEW_SOLICITACAO')) ?>:</label>
	<span class="float-l span-9 bold"><?php echo $this->ni_solicitacao."/".$this->ni_ano_solicitacao ?></span>

	<label class="float-l clear-l span-5 required" for="tx_execucao_solicitacao"><?php echo $this->escape($this->translate('L_VIEW_OBSERVACOES_EXECUCAO')) ?>:</label>
	<?php echo $this->formTextarea('tx_execucao_solicitacao', '', array('class'=>'float-l span-9','style' => 'width:350px; height:120px;')) ?>

</form>