<?php
    $this->script('scriptFile',array('/solicitacao-tipo-demanda/index.js'));

    echo $this->formHidden('cd_objeto', $this->solicitacao['cd_objeto']);
    echo $this->formHidden('ni_solicitacao', $this->solicitacao['ni_solicitacao']);
    echo $this->formHidden('ni_ano_solicitacao', $this->solicitacao['ni_ano_solicitacao']);
    echo $this->formHidden('st_solicitacao', $this->solicitacao['tipo_solicitacao']);
?>

<div class="box span-21 border gradient">
    <h3 class="highlight tarja-1"><?php echo $this->escape($this->translate('L_VIEW_DETALHE_SOLICITACAO')) ?></h3>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_OBJETO_CONTRATO')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['tx_objeto'] ?></p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_DATA_SOLICITACAO')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['dt_solicitacao'] ?></p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_TIPO_SOLICITACAO')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['st_solicitacao'] ?></p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_GESTOR_SOLICITANTE')) ?></label>
        <p class="span-6"></p>
	
    <hr style="width:816px;"/>

	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_NOME')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['tx_solicitante'] ?></p>
	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_UNIDADE')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['tx_sigla_unidade'] ?></p>
	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_SALA')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['tx_sala_solicitante'] ?></p>
	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_TELEFONE')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['tx_telefone_solicitante'] ?></p>
	
    <hr style="width:816px;"/>

	<label class="bold span-5"><?php echo $this->escape($this->translate('L_VIEW_DESCRICAO_SOLICITACAO')) ?>:</label>
		<p class="span-15" style="text-align: justify;"><?php echo $this->solicitacao['tx_solicitacao'] ?></p>
    <label class="bold span-5"><?php echo $this->escape($this->translate('L_VIEW_PRAZO_ATENDIMENTO')) ?> (<?php echo mb_strtolower($this->escape($this->translate('L_VIEW_DIAS')), 'utf-8') ?>):</label>
		<p class="span-6"><?php echo $this->solicitacao['ni_prazo_atendimento'] ?></p>
	<label class="bold span-5"><?php echo $this->escape($this->translate('L_VIEW_OBSERVACOES')) ?>:</label>
		<p class="span-15" style="text-align: justify;"><?php echo $this->solicitacao['tx_obs_solicitacao'] ?></p>
	
    <hr style="width:816px;"/>

	<br>
	<button
        class="verde float-r"
		onClick="encaminhaSolicitacaoTipoDemanda('<?php echo $this->solicitacao['cd_objeto'] ?>', '<?php echo $this->solicitacao['ni_solicitacao'] ?>', '<?php echo $this->solicitacao['ni_ano_solicitacao'] ?>')"
		id="button_encaminhar_<?php echo $this->solicitacao['ni_solicitacao'] ?>_<?php echo $this->solicitacao['ni_ano_solicitacao'] ?>">
            <?php echo $this->escape($this->translate('L_BTN_ENCAMINHAR')) ?>
    </button>
	<br>
	<br>	
</div>