<?php
    $this->script('validaForm');
    $this->script('scriptFile',array('/solicitacao-tipo-demanda/index.js'));
?>
<script type="text/javascript">
<!--
$(document).ready(function(){
	$('#bt_retornar_solicitacao').click(function(){
		window.location.href = systemName+'/solicitacao-tipo-demanda\#<?php echo $this->abaorigem ?>';
	});
});
//-->
</script>
<div class="box span-21 border gradient">
	<h3 class="highlight tarja-1"><?php echo $this->escape($this->translate('L_VIEW_DETALHE_SOLICITACAO_EXECUTADA')) ?></h3>
	<?php if (count($this->arrDemanda) > 0): ?>
        <label class="bold span-5"><?php echo $this->escape($this->translate('L_VIEW_SOLICITACAO_SERVICO')) ?>:</label>
            <p class="span-6"><?php echo (!is_null($this->arrDemanda['ni_solicitacao']))?"{$this->arrDemanda['ni_solicitacao']}/{$this->arrDemanda['ni_ano_solicitacao']}":$this->arrDemanda['cd_demanda'] ?></p>
        <label class="bold span-5"><?php echo $this->escape($this->translate('L_VIEW_DATA_HORA_DEMANDA'  )) ?>:</label>
            <p class="span-6"><?php echo date('d/m/Y H:i:s', strtotime($this->arrDemanda['dt_demanda'])) ?></p>
        <label class="bold span-5"><?php echo $this->escape($this->translate('L_VIEW_SOLICITANTE'        )) ?>:</label>
            <p class="span-6"><?php echo $this->arrDemanda['tx_solicitante_demanda'] ?></p>
        <label class="bold span-5"><?php echo $this->escape($this->translate('L_VIEW_UNIDADE'            )) ?>:</label>
            <p class="span-6"><?php echo $this->arrDemanda['tx_sigla_unidade'] ?></p>
        <label class="bold span-5"><?php echo $this->escape($this->translate('L_VIEW_DESCRICAO'          )) ?>:</label>
            <div class="span-15" style="text-align: justify; margin-left: 10px;"><?php echo $this->arrDemanda['tx_demanda'] ?></div>
        <label class="bold span-5"><?php echo $this->escape($this->translate('L_VIEW_OBJETO_EXECUTOR'    )) ?>:</label>
            <p class="span-6"><?php echo $this->arrDemanda['tx_objeto'] ?></p>
	<?php else: ?>
        <label class="bold span-11" style="text-align: center;">
            *** <?php echo $this->escape($this->translate('L_MSG_ALERT_SOLICITACAO_SERVICO_AGUARDANDO_ENCAMINHAMENTO')) ?> ***
        </label>
	<?php endif; ?>
        
	<label class="bold clear-l float-l span-4">
        <?php echo $this->escape($this->translate('L_VIEW_HISTORICO_EXECUCAO')) ?>
    </label>
	<div class="span-20 float-l clear-l height-10 border" style="overflow-x: hidden; overflow-x: auto; margin-left:18px; margin-bottom: 5px;">
		<?php
			if(count($this->arrHistorico) > 0):
				$cd_nivel_servico = -1;
				foreach($this->arrHistorico as $historico): 
					if($historico['cd_nivel_servico'] != $cd_nivel_servico):
		?>
                        <label class="float-l"><?php echo "<b>".$historico['tx_nivel_servico']." (".$historico['ni_horas_prazo_execucao']." horas)</b>" ?></label>
            <?php   endif;
              ?>
				<ul class="clear-l span-18">
					<li class="clear-l float-l push-1 span-17" style="text-align: justify;">

                        <?php if (!is_null($historico['dt_inicio']) && !is_null($historico['dt_fim'])): ?>
                            <?php echo date('d/m/Y H:i:s', strtotime($historico['dt_inicio']))."&nbsp;a&nbsp;".date('d/m/Y H:i:s', strtotime($historico['dt_fim']))." &nbsp;&nbsp;(".$historico['tx_profissional'].")<br />".$historico['tx_historico'] ?>
                        <?php else: ?>
                            <?php echo "(".$historico['tx_profissional'].")<br />".$this->escape($this->translate('L_MSG_ALERT_SEM_HISTORICO_REGISTRADO_PROFISSIONAL')) ?>
                        <?php endif; ?>    
					</li>
				</ul>
		<?php  
				$cd_nivel_servico = $historico['cd_nivel_servico'];
				endforeach;
			else: ?>
			<label style="color: red; text-align: center;">
                <?php echo $this->escape($this->translate('L_MSG_ALERT_SEM_HISTORICO_REGISTRADO_PROFISSIONAL')) ?>
            </label>
		<?php endif; ?>
	</div>
	<br />	
	<hr style="width:815px;"/>
	<?php echo $this->formButton('bt_retornar_solicitacao', mb_strtoupper($this->escape($this->translate('L_BTN_VOLTAR')), 'utf-8'), array('class' => 'float-l azul'), null)?>
	<?php if ($this->abaorigem == "solicitacao-tipo-demanda-andamento"): ?>	
    <button class="verde float-r" onClick="abreModalConclusaoSolicitacaoTipoDemanda('<?php echo $this->arrDemanda['cd_objeto'] ?>', '<?php echo $this->arrDemanda['ni_solicitacao'] ?>', '<?php echo $this->arrDemanda['ni_ano_solicitacao'] ?>')" id="button_concluir_<?php echo $this->arrDemanda['cd_demanda'] ?>"><?php echo mb_strtoupper($this->escape($this->translate('L_BTN_CONCLUIR')), 'utf-8') ?></button>
	<?php endif; ?>
</div>