<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableAgendaImplantacao").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableAgendaImplantacao").tablesorterPager({container: $("#tableAgendaImplantacaoPager")}); 
});
</script>
<table id="tableAgendaImplantacao" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
			<th class="{sorter: false}" style="width: 10px;">&nbsp;</th>
            <th class="span-3" ><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA'        )) ?></th>
			<th class="span-11"><?php echo $this->escape($this->translate('L_VIEW_GRID_DETALHAMENTO')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr>
			<td><img id="imgExcluir" height="13" width="13" style="cursor:pointer; text-align: center;" onclick="excluirAgendaImplantacao('<?php echo $res['dt_agenda_plano_implantacao'] ?>');" src="<?php echo $this->baseUrl()?>/public/img/del.png" alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/></td>
			<td style="cursor: pointer;" onClick="recuperaDadosAgendaImplantacao('<?php echo $res['dt_agenda_plano_implantacao'] ?>')"><?php echo date('d/m/Y', strtotime($res['dt_agenda_plano_implantacao'])) ?></td>
			<?php 
			    $fim = "";
				if(strlen($res['tx_agenda_plano_implantacao']) >= 100){
					$fim = "...";
				}
				$tx_agenda_plano_implantacao = substr($res['tx_agenda_plano_implantacao'],0,100) 
			?>
			<td style="cursor: pointer;" onClick="recuperaDadosAgendaImplantacao('<?php echo $res['dt_agenda_plano_implantacao'] ?>')"><?php echo $tx_agenda_plano_implantacao.$fim ?></td>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableAgendaImplantacaoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
