<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableEtapa").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableEtapa").tablesorterPager({container: $("#tableEtapaPager")}); 
});
</script>
<table id="tableEtapa" cellspacing="1" class="tablesorter" style="border-collapse:collapse">
	<thead>
		<tr>
            <th class="{sorter: false}" width="15">&nbsp;</th>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_NR_ORDEM')); ?></th>
			<th class="span-11"><?php echo $this->escape($this->translate('L_VIEW_GRID_ETAPA')); ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->rowSetEtapa->valid()):
		foreach ($this->rowSetEtapa as $row):
	?>
		<tr>
			<td><img id="imgExcluir"
                     height="13"
                     width="13"
                     style="cursor:pointer;"
                     onclick="excluiEtapa(<?php echo $row->cd_etapa ?>);"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->escape($this->translate('L_VIEW_EXCLUIR')); ?>"/>
            </td>
            <td style="cursor:pointer;" onClick="recuperaEtapa(<?php echo $row->cd_etapa ?>)" ><?php echo $this->escape($row->ni_ordem_etapa) ?></td>
			<td style="cursor:pointer;" onClick="recuperaEtapa(<?php echo $row->cd_etapa ?>)" ><?php echo $this->escape($row->tx_etapa) ?></td>
		</tr>
	<?php
		endforeach;
	else:
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	endif;
	?>
	</tbody>
</table>
<div id="tableEtapaPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
