<script type="text/javascript">
    $(document).ready(function() {
        $("#tableSolicitacao").tablesorter({widthFixed: true, widgets: ['zebra']});
        $("#tableSolicitacao").tablesorterPager({container: $("#tableSolicitacaoPager")});
    });
</script>
<table cellspacing="1" id="tableSolicitacao" class="tablesorter" >
    <thead>
        <tr>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_SOLICITACAO')) ?></th>
            <th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_SITUACAO')) ?></th>
            <th class="span-8"><?php echo $this->escape($this->translate('L_VIEW_GRID_OBSERVACAO_PEDIDO')) ?></th>
            <th class="span-8"><?php echo $this->escape($this->translate('L_VIEW_GRID_EMITIR_SOLICITACAO_PROPOSTA')) ?></th>
        </tr>
    </thead>
    <tbody>
	<?php if($this->objSolicitacao->valid()): ?>
        <?php foreach($this->objSolicitacao as $rs): ?>
            <tr>
                <td><?php echo date('d/m/Y', strtotime($rs->dt_analise_area_ti_chefia_exec)) ?></td>
                <td><?php echo $rs->st_situacao_pedido_desc ?></td>
                <td><?php echo $rs->tx_analise_area_ti_chefia_exec ?></td>
                <td class="center">
                    <?php echo $this->formButton('btn_criar_proposta', $this->escape($this->translate('L_BTN_EMITIR_SOLICITACAO')),array('class'=>'azul','onclick'=>"emitirSolicitacao({$rs->cd_solicitacao_pedido})")) ?>
                </td>
            </tr>
        <?php endforeach; ?>
	<?php else:
            echo " <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                  </tr>";
        endif; ?>
    </tbody>
</table>
<div id="tableSolicitacaoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
		</select>
	</form>
</div>