<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableFuncionalidade").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableFuncionalidade").tablesorterPager({container: $("#tableFuncionalidadePager")});
});
</script>
<table id="tableFuncionalidade" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
			<th class="{sorter:false}" style="width: 10px;">&nbsp;</th>
            <th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_CODIGO')) ?></th>
			<th width="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_FUNCIONALIDADE')) ?></th>
			<th width="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_TIPO')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res->valid()){
		foreach ($this->res as $res):
	?>
    <tr>
		<td><img id="imgExcluir" 
                 height="13"
                 width="13"
                 style="cursor:pointer; text-align: center;"
                 onclick="excluirFuncionalidade('<?php echo $res['cd_funcionalidade'] ?>');"
                 src="<?php echo $this->baseUrl()?>/public/img/del.png"
                 alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/>
        </td>
        <td onclick="redirecionaFuncionalidade(<?php echo $res['cd_funcionalidade'] ?>)" style="cursor:pointer;"><?php echo $res['tx_codigo_funcionalidade'] ?></td>
        <td onclick="redirecionaFuncionalidade(<?php echo $res['cd_funcionalidade'] ?>)" style="cursor:pointer;"><?php echo $res['tx_funcionalidade'] ?></td>
        <td onclick="redirecionaFuncionalidade(<?php echo $res['cd_funcionalidade'] ?>)" style="cursor:pointer;">
            <?php 
                switch ($res["st_funcionalidade"]){
				case "I":
					echo $this->escape($this->translate('L_VIEW_COMBO_ITEM'));
					break;
				case "P":
					echo $this->escape($this->translate('L_VIEW_COMBO_PRINCIPAL'));
					break;
				default:
					break;
			}
            ?>
        </td>
	</tr>	
	<?php
		endforeach;
	} else {
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
			   </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableFuncionalidadePager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
