<script type="text/javascript">
$(document).ready(function() {
	// call the tablesorter plugin
    $("#tableInventario").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableInventario").tablesorterPager({container: $("#tableInventarioPager")});
});
</script>
<table id="tableInventario" cellspacing="1" class="tablesorter" >
	<thead>
		<tr>
			<th style="width: 10px;">&nbsp;</th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_AREA_ATUACAO_TI'      )) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_ULTIMA_ATUALIZACAO'     )) ?></th>
			<th class="span-6"><?php echo $this->escape($this->translate('L_VIEW_GRID_INVENTARIO'     )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res):
		foreach ($this->res as $res):
	?>
		<tr>
			<td><img id="imgExcluir" 
                     height="13"
                     width="13"
                     style="cursor:pointer; text-align: center;"
                     onclick="excluiInventario('<?php echo $res['cd_inventario']; ?>');"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/></td>
			<td title="<?php echo $res['tx_area_atuacao_ti'] ?>" style="cursor: pointer;" onClick="recuperaDadosInventario('<?php echo $res['cd_inventario']; ?>')"><?php echo $res['tx_area_atuacao_ti']; ?></td>
			<td title="<?php echo date('d/m/Y', strtotime($res['dt_ult_atual_inventario'])) ?>" style="cursor: pointer;" onClick="recuperaDadosInventario('<?php echo $res['cd_inventario']; ?>')"><?php echo date('d/m/Y', strtotime($res['dt_ult_atual_inventario'])); ?></td>
			<td title="<?php echo $res['tx_inventario'] ?>" style="cursor: pointer;" onClick="recuperaDadosInventario('<?php echo $res['cd_inventario']; ?>')"><?php echo $res['tx_inventario']; ?></td>
		</tr>
	<?php
		endforeach;
	else:
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	endif;
	?>
	</tbody>
</table>
<div id="tableInventarioPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>