<script type="text/javascript">
$(document).ready(function() {
    // call the tablesorter plugin
    $("#tableSubitemInvDescri").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableSubitemInvDescri").tablesorterPager({container: $("#tableSubitemInvDescriPager")});
});
</script>
<table id="tableSubitemInvDescri" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
			<th class="{sorter: false}" style="width: 20px;">&nbsp;</th>
            <th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_NR_ORDEM')) ?></th>
            <th class="span-11"><?php echo $this->escape($this->translate('L_VIEW_GRID_DESCRICAO')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res->valid()):
		foreach ($this->res as $res):
	?>
		<tr>
            <td style="text-align: center;">
                <img id="imgExcluir" height="13" width="13" style="cursor:pointer;" onclick="excluirSubitemInvDescri(<?php echo $res['cd_item_inventario'] ?>,<?php echo $res['cd_subitem_inventario'] ?>,<?php echo $res['cd_subitem_inv_descri'] ?>);" src="<?php echo $this->baseUrl()?>/public/img/del.png" alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/>
            </td>
			<td style="text-align: center; cursor:pointer;" onClick="recuperarSubitemInvDescri(<?php echo $res['cd_item_inventario'] ?>,<?php echo $res['cd_subitem_inventario'] ?>,<?php echo $res['cd_subitem_inv_descri'] ?>)" >
                <?php echo $res['ni_ordem'] ?>
            </td>
			<td style="cursor:pointer;" onClick="recuperarSubitemInvDescri(<?php echo $res['cd_item_inventario'] ?>,<?php echo $res['cd_subitem_inventario'] ?>,<?php echo $res['cd_subitem_inv_descri'] ?>)" >
                <?php echo $res['tx_subitem_inv_descri'] ?>
            </td>
        </tr>
	<?php
		endforeach;
	else:
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	endif ?>
	</tbody>
</table>
<div id="tableSubitemInvDescriPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
