<?php
    $this->script('scriptFile',array('/gerenciar-projetos-elaboracao/index.js',
                                     '/proposta/index.js'));
?>
<script type="text/javascript" defer="defer">
	$(document).ready(function() {
		// call the tablesorter plugin
	    $("#tabela_elaboracao").tablesorter({widthFixed: true, widgets: ['zebra']});
	    $("#tabela_elaboracao").tablesorterPager({container: $("#pager_elaboracao")});

	});
function redirecionaElaboracao(params) {
    var url = 'elaboracao-proposta/index/abaOrigem/elaboracaoProposta';
    redirect(url,params,'');
}
</script>
<div class="boxTab height-2"></div>

<table id="tabela_elaboracao" cellspacing="1" class="tablesorter">
	<thead>
	    <tr>
            <th width="18%"><?php echo $this->escape($this->translate('L_VIEW_GRID_SIGLA')) ?></th>
			<th width="12%"><?php echo $this->escape($this->translate('L_VIEW_GRID_PROPOSTA')) ?></th>
			<th colspan="7" width="55%"><?php echo $this->escape($this->translate('L_VIEW_GRID_ETAPA_ELABORACAO')) ?></th>
			<th class="{sorter:false}" width="15%">&nbsp;</th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res):
		foreach ($this->res as $res):
	?>
	<tr>
		<td><?php echo $res['tx_sigla_projeto']?></td>
        <td><span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>})" ><?php echo $this->escape($this->translate('L_VIEW_PROPOSTA_NR'))." ".$res['cd_proposta']?></span></td>
		<td style="text-align:center">
            <div><?php echo $this->escape($this->translate('L_VIEW_DESCRICAO')) ?></div>
			<div>
				<?php if(substr($res['indicador'],0,1) == "1"):?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_descricao_proposta'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u42.png">
                        </span>
				<?php else:?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_descricao_proposta'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u46.png">
                        </span>
				<?php endif; ?>
			</div>
		</td>
		<td style="text-align:center">
			<div><?php echo $this->escape($this->translate('L_VIEW_PROFISSIONAIS')) ?></div>
			<div>
				<?php if(substr($res['indicador'],1,1) == "1"):?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_alocar_profissionais'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u42.png">
                        </span>
				<?php else:?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_alocar_profissionais'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u46.png">
                        </span>
				<?php endif; ?>
			</div>
		</td>
		<td style="text-align:center">
			<div><?php echo $this->escape($this->translate('L_VIEW_METRICA')) ?></div>
			<div>
				<?php if(substr($res['indicador'],2,1) == "1"):?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_aplicacao_de_metrica'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u42.png">
                        </span>
				<?php else: ?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_aplicacao_de_metrica'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u46.png">
                        </span>
				<?php endif; ?>
			</div>
		</td>
		<td style="text-align:center">
			<div><?php echo $this->escape($this->translate('L_VIEW_MODULOS')) ?></div>
			<div>
				<?php if(substr($res['indicador'],4,1) == "1"): ?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_gerenciar_modulos'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u42.png">
                        </span>
				<?php else: ?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_gerenciar_modulos'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u46.png">
                        </span>
				<?php endif; ?>
			</div>
		</td>
		<td style="text-align:center">
			<div><?php echo $this->escape($this->translate('L_VIEW_PARCELAS')) ?></div>
			<div>
				<?php if(substr($res['indicador'],5,1) == "1"): ?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_criar_parcelas'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u42.png">
                        </span>
				<?php else: ?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_criar_parcelas'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u46.png">
                        </span>
				<?php endif; ?>
			</div>
		</td>
		<td style="text-align:center">
			<div><?php echo $this->escape($this->translate('L_VIEW_PRODUTOS')) ?></div>
			<div>
				<?php if(substr($res['indicador'],6,1) == "1"): ?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_acrescentar_produtos'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u42.png">
                        </span>
				<?php else: ?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_acrescentar_produtos'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u46.png">
                        </span>
				<?php endif; ?>
			</div>
		</td>
		<td style="text-align:center">
			<div><?php echo $this->escape($this->translate('L_VIEW_REQUISITOS')) ?></div>
			<div>
				<?php if(substr($res['indicador'],3,1) == "1"): ?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_requisitos_proposta'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u42.png">
                        </span>
				<?php else: ?>
                        <span class="link" onclick="redirecionaElaboracao({cd_projeto:<?php echo $res['cd_projeto']?>,cd_proposta:<?php echo $res['cd_proposta']?>,accordion:'form_requisitos_proposta'})" >
                            <img src="<?php echo $this->baseUrl()?>/public/img/u46.png">
                        </span>
				<?php endif; ?>
			</div>
		</td>
		<td style="text-align:center">
            <?php if($res['indicador'] == "1111111" && $_SESSION['oasis_logged'][0]['cd_perfil'] != K_CODIGO_PERFIL_TECNICO): ?>
                      <button onClick="fechaProposta('<?php echo $res['cd_projeto']?>', '<?php echo $res['cd_proposta']?>')" class="azul" id="bt_fechar_proposta_<?php echo $res['cd_projeto']?>_<?php echo $res['cd_proposta']?>"><?php echo $this->escape($this->translate('L_BTN_FECHAR_PROPOSTA')) ?></button>
			<?php else: ?>
                      &nbsp;
			<?php endif; ?>
		</td>
	</tr>
	<?php
		endforeach;
	else:
		echo "  <tr>
					<td width='18%'>&nbsp;</td>
					<td width='12%'>&nbsp;</td>
					<td colspan='7'' width='55%'>&nbsp;</td>
					<td width='15%'>&nbsp;</td>
				</tr>
		";
	endif;
	?>
	</tbody>
</table>
<div id="pager_elaboracao" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>