<div id="tabelaDefinicao" class="divTab">
	<?php 
		  echo $this->formHidden('cd_caso_de_uso'); 
		  echo $this->formHidden('dt_versao_caso_de_uso'); 
		  echo $this->formHidden('dt_fechamento_caso_de_uso'); 
	?>
    <label class="right float-l span-4 clear-l required" for="cd_modulo"><?php echo $this->escape($this->translate('L_VIEW_MODULO')) ?>:</label>
		<?php echo $this->formSelect('cd_modulo', null, array('class'=>'float-l'), $this->comboModulo);?>
	<label class="right float-l span-4 clear-l required" for="tx_caso_de_uso"><?php echo $this->escape($this->translate('L_VIEW_NOME_CASO_DE_USO')) ?>:</label>
		<?php echo $this->formText('tx_caso_de_uso','',array('size'=>75, 'class'=>'span-12 float-l')) ?>
    <label class="right float-l span-4 clear-l required" for="ni_ordem_caso_de_uso"><?php echo $this->escape($this->translate('L_VIEW_NR_ORDEM')) ?>:</label>
		<?php echo $this->formText('ni_ordem_caso_de_uso', '', array('size'=>75, 'class'=>'span-2 float-l', 'onKeyPress'=>'return soNumeros(event);')) ?>
	<label class="right float-l span-4 clear-l required" for="tx_descricao_caso_de_uso"><?php echo $this->escape($this->translate('L_VIEW_DESCRICAO')) ?>:</label>
        <?php echo $this->formTextarea('tx_descricao_caso_de_uso', '', array('class'=>'float-l span-12 height-4'));

			echo $this->formButton('adicionarDefinicao', $this->escape($this->translate('L_BTN_SALVAR')), array('class' => 'verde float-l clear-l push-4'));
			echo $this->formButton('alterarDefinicao', $this->escape($this->translate('L_BTN_ALTERAR')), array('class' => 'verde float-l clear-l push-4'));
			echo $this->formButton('cancelarDefinicao', $this->escape($this->translate('L_BTN_CANCELAR')), array('class' => 'vermelho float-l push-4'));
		 ?>
	<div id="gridDefinicao" class="float-l clear-l span-20"></div>
</div>