<?php
    $this->script('scriptFile',array('/questao-analise-risco/index.js'));
?>
<div id="questao_analise_risco">
    <?php echo $this->formHidden( 'cd_questao_analise_risco' ); ?>
    <label class="bold float-l span-5 clear-l required" for="cd_area_atuacao_ti_questao_analise_risco" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_AREA_ATUACAO_TI')); ?>:</label>
	    <?php echo $this->formSelect( 'cd_area_atuacao_ti_questao_analise_risco', null,array('class'=>'float-l'), null ); ?>

    <label class="bold float-l span-5 clear-l required" for="cd_etapa_questao_analise_risco" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_ETAPA')); ?>:</label>
	    <?php echo $this->formSelect( 'cd_etapa_questao_analise_risco', null,array('class'=>'float-l'),array('0'=>$this->escape($this->translate('L_VIEW_COMBO_SELECIONE'))) ); ?>

    <label class="bold float-l span-5 clear-l required" for="cd_atividade_questao_analise_risco" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_ATIVIDADE')); ?>:</label>
	    <?php echo $this->formSelect( 'cd_atividade_questao_analise_risco', null, array('class'=>'float-l'),array('0'=>$this->escape($this->translate('L_VIEW_COMBO_SELECIONE')))); ?>

    <label class="bold float-l span-5 clear-l required" for="cd_item_risco_questao_analise_risco" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_ITEM_RISCO')); ?>:</label>
	    <?php echo $this->formSelect( 'cd_item_risco_questao_analise_risco', null, array('class'=>'float-l'),array('0'=>$this->escape($this->translate('L_VIEW_COMBO_SELECIONE')))); ?>

    <label class="bold float-l span-5 clear-l required" for="tx_questao_analise_risco" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_QUESTAO_RISCO_ITEM')); ?>:</label>
    	<?php echo $this->formText( 'tx_questao_analise_risco', null, array('class' => 'float-l span-10')); ?>

    <label class="bold float-l span-5 clear-l required" for="ni_peso_questao_analise_risco" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_PESO')); ?>:</label>
    	<?php echo $this->formText( 'ni_peso_questao_analise_risco', null, array('class' => 'float-l span-2','onKeyPress'=>"return soNumeros(event)")); ?>

    <label class="bold float-l span-5 clear-l" for="tx_obj_questao_analise_risco" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_OBJETIVO')); ?>:</label>
    	<?php echo $this->formTextarea( 'tx_obj_questao_analise_risco', null, array('class' => 'float-l span-10 height-4')); ?>
    <?php
    	echo $this->formButton('btn_salvar_questao_analise_risco' , $this->escape($this->translate('L_BTN_SALVAR')),  array('class' => 'verde float-l clear-l push-5',    'style'   => 'display:none', 'onclick' => 'salvarQuestaoAnaliseRisco();'));
    	echo $this->formButton('btn_alterar_questao_analise_risco', $this->escape($this->translate('L_BTN_ALTERAR')), array('class' => 'azul float-l clear-l push-5',     'style'   => 'display:none', 'onclick' => 'salvarQuestaoAnaliseRisco();'));
    	echo $this->formButton('btn_excluir_questao_analise_risco', $this->escape($this->translate('L_BTN_EXCLUIR')), array('class' => 'vermelho float-l push-5', 'style'   => 'display:none', 'onclick' => 'excluirQuestaoAnaliseRisco();'));
    ?>
</div>
<hr />
<div id="gridQuestaoAnaliseRisco"></div>