<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableNivelServico").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableNivelServico").tablesorterPager({container: $("#tableNivelServicoPager")}); 
});
</script>
<table id="tableNivelServico" cellspacing="1" class="tablesorter" style="border-collapse:collapse">
	<thead>
		<tr>
            <th class="span-4"><?php echo $this->escape($this->translate('L_VIEW_GRID_PROFISSIONAL')) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA'        )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_MENSAGEM'    )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_CONTROLLER'  )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_TABELA'      )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_IP'          )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_HOST'        )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
            $res['dt_ocorrencia'] = date('d/m/Y H:i:s', strtotime($res['dt_ocorrencia']));
	?>
		<tr>
			<?php
				$fimProf = "";
				if(strlen($res['tx_profissional']) >= 18){
					$fimProf = "...";
				}
				$tx_profissional = substr($res['tx_profissional'],0,18)
			?>
			<td title="<?php echo $res['tx_profissional'] ?>"><?php echo $tx_profissional.$fimProf ?></td>
			<td title="<?php echo $res['dt_ocorrencia'  ] ?>"><?php echo substr($res['dt_ocorrencia'],0,10)?></td>

			<?php
				$fimMsg = "";
				if(strlen($res['tx_msg_log']) >= 15){
					$fimMsg = "...";
				}
				$tx_msg_log = substr($res['tx_msg_log'],0,15) 
			?>
			<td title="<?php echo $res['tx_msg_log'] ?>"	><?php echo $tx_msg_log.$fimMsg; ?></td>

			<?php
				$fimCtrl = "";
				if(strlen($res['tx_controller']) >= 15){
					$fimCtrl = "...";
				}
				$tx_controller = substr($res['tx_controller'],0,15) 
			?>
			<td title="<?php echo $res['tx_controller'] ?>"	><?php echo $tx_controller.$fimCtrl; ?></td>

			<?php
				$fimTbl = "";
				if(strlen($res['tx_tabela']) >= 15){
					$fimTbl = "...";
				}
				$tx_tabela = substr($res['tx_tabela'],0,15) 
			?>
			<td title="<?php echo $res['tx_tabela'] ?>"	><?php echo $tx_tabela.$fimTbl ?></td>
			<td title="<?php echo $res['tx_ip'] ?>"	><?php echo $res['tx_ip'] ?></td>

			<?php
				$fimHost = "";
				if(strlen($res['tx_host']) >= 15){
					$fimHost = "...";
				}
				$tx_host = substr($res['tx_host'],0,15) 
			?>
			<td title="<?php echo $res['tx_host'] ?>"><?php echo $tx_host.$fimHost; ?></td>
		</tr>
	<?php
		endforeach;
	} else {
		echo "<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableNivelServicoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
