<?php
    $this->script('scriptFile',array('/log/index.js'));
?>
<div>
	<label class="float-l span-2 right"><?php echo $this->escape($this->translate('L_VIEW_PROFISSIONAL')) ?>:</label>
	<?php echo $this->formSelect('cmb_profissional_log', null, array('class'=>'float-l span-11'), $this->arrProfissionalLog);?>
	
	<label class="float-l span-2 right clear-l required" for="dt_inicio_log"><?php echo $this->escape($this->translate('L_VIEW_DATA_INICIAL')) ?>:</label>
	<?php echo $this->Data('dt_inicio_log', null, array('class'=>'float-l span-3'));?>
	
	<label class="float-l span-4 right required" for="dt_fim_log" style="padding-left: 10px;"><?php echo $this->escape($this->translate('L_VIEW_DATA_FINAL')) ?>:</label>
	<?php echo $this->Data('dt_fim_log', null, array('class'=>'float-l span-3'));?>

	<label class="float-l span-2 right clear-l"><?php echo $this->escape($this->translate('L_VIEW_TABELA')) ?>:</label>
	<?php echo $this->formSelect('cmb_tabela_log', null, array('class'=>'float-l span-11'), $this->arrTabelasEsquema);?>

	<label class="float-l span-2 right clear-l" ><?php echo $this->escape($this->translate('L_VIEW_IP')) ?>:</label>
	<?php echo $this->formText('ip_log', null, array('class'=>'float-l span-11'));?>

	<?php echo $this->formButton('btn_pesquisar',$this->escape($this->translate('L_BTN_PESQUISAR')), array('class'=>'clear-l float-l push-2 verde'));?>
</div>
<hr />
<div id="grid_registro_log" class="clear-l float-l"></div>