<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl()?>/public/js/modules/default/contrato-definicao-metrica/grid-metrica-associada-contrato.js"></script>

<script type="text/javascript" defer="defer">
$(document).ready(function() {
	// call the tablesorter plugin
    $("#tableMetricaAssociadaContrato").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableMetricaAssociadaContrato").tablesorterPager({container: $("#pagerMetricaAssociadaContrato")});

});
</script>
<?php
    if($this->st_contrato !== "I"): ?>
        <label class="bold span-21 center float-l small" style="color: red;">
            <?php echo $this->escape($this->translate('L_MSG_ALERT_PREENCHIMENTO_DADOS_ABAIXO_OBRIGATORIO')) ?>
        </label>
<?php
    endif; ?>
<table id="tableMetricaAssociadaContrato" cellspacing="1" class="tablesorter" style="border-collapse:collapse">
	<thead>
	    <tr>
			<th class="span-9"><?php echo $this->escape($this->translate('L_VIEW_GRID_METRICA'      )) ?></th>
			<th class="span-2 center"><?php echo $this->escape($this->translate('L_VIEW_GRID_PADRAO')) ?></th>
			<th class="span-3 center"><?php echo $this->escape($this->translate('L_VIEW_GRID_FATOR' )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){

		$disabled = '';
		if($this->st_contrato === "I"){
			$disabled = 'disabled="disabled"';
		}

		foreach ($this->res as $res):
			$cd_contrato_cd_definicao_metrica = $res['cd_contrato']."_".$res['cd_definicao_metrica'];
	?>
			<tr>
				<td>
					<?php
						if($res['st_metrica_padrao'] === 'S'){
							echo $res['tx_nome_metrica']." ({$res['tx_sigla_metrica']}) *";
						}else{
							echo $res['tx_nome_metrica']." ({$res['tx_sigla_metrica']})";
						}
					?>
				</td>


			<?php if( $res['st_metrica_padrao'] === "S"):?>
				<td class="center">
					<input type="radio"		id="rd_<?php echo $cd_contrato_cd_definicao_metrica ?>"
						   name="st_padrao" value="<?php echo $cd_contrato_cd_definicao_metrica ?>"
						   onclick="habilitaCampoFator(this.value)" checked="checked" <?php if($disabled != ''){ echo $disabled; } ?> />
				</td>
				<td class="center">
					<?php echo $this->formText($cd_contrato_cd_definicao_metrica,'',array('class'=>'span-2', 'disabled'=>'disabled'))?>
				</td>
			<?php else: ?>

				<td class="center">
					<input type="radio"		id="rd_<?php echo $cd_contrato_cd_definicao_metrica ?>"
						   name="st_padrao" value="<?php echo $cd_contrato_cd_definicao_metrica ?>"
						   onclick="habilitaCampoFator(this.value)" <?php if($disabled != ''){ echo $disabled; } ?> />
				</td>
				<td class="center">
					<?php
						if($this->st_contrato === "I"){
							echo $this->formText($cd_contrato_cd_definicao_metrica,$res['nf_fator_relacao_metrica_pad'],array('class'=>'span-2','disabled'=>'disabled'));
						}else{
							echo $this->formText($cd_contrato_cd_definicao_metrica,$res['nf_fator_relacao_metrica_pad'],array('class'=>'span-2', 'onKeyPress'=>"return soNumerosComPonto(event)"));
						}
					?>
				</td>

			<?php endif;?>
			</tr>
			<?php
		endforeach;
	} else {
		echo "  <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>";
	}
	?>
	</tbody>
</table>
<div id="pagerMetricaAssociadaContrato" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>

<?php if($this->st_contrato !== "I"): ?>
	<div>
        <label class="bold span-18 right float-l" style="color: red;"><?php echo Base_Util::getTranslator('L_MSG_ALERT_CLIQUE_PARA_REGISTRAR_OPERACAO', $this->escape($this->translate('L_BTN_CONFIRMAR'))) ?></label>
		<div id="btSalvarConfiguracaoFatoresMetrica" class="float-r">
			<?php echo $this->formButton('btn_salvar_config_fator_metrica', $this->escape($this->translate('L_BTN_CONFIRMAR')), array('class' => 'verde float-r')) ?>
		</div>
	</div>
<?php endif; ?>