<?php
    $this->script('scriptFile',array('/profissional-objeto-contrato/index.js'));
?>
<script type="text/javascript">
$(document).ready(function() { 
	$("#config_hidden_profissional_objeto_contrato").val('N');
});

function configAccordionProfissionalObjetoContrato()
{
	if($("#config_hidden_profissional_objeto_contrato").val() === 'N'){
		pesquisaPorObjetoAjax();
		$("#config_hidden_profissional_objeto_contrato").val('S');
	}
}
</script>
<div style="padding: 5px;">
    <label class="span-3 float-l bold clear-l"><?php echo $this->escape($this->translate('L_VIEW_OBJETO')) ?>:</label>
		<?php echo $this->formSelect('cd_objeto_profissional_objeto_contrato', null, array('class'=>'float-l'), $this->objetoContratoCombo); ?>
	

     <?php echo $this->flipFlop(array('name'=>'cd_profissional_objeto_contrato_1',
                                      'label'=>$this->escape($this->translate('L_VIEW_PROFISSIONAIS')),
                                      'value'=>$this->profissionais),
                                array('name'=>'cd_profissional_objeto_contrato_2',
                                      'label'=>$this->escape($this->translate('L_VIEW_PROFISSIONAIS_ASSOCIADOS')),
                                      'value'=>$this->profissionais2),
                                'add_profissional_objeto_contrato',
                                'remove_profissional_objeto_contrato',8);
     ?>
	<div id="gridProfissionalAssociado" class="float-l clear-l span-20"></div>
</div>


