<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableFaleConoscoMensagemPendente").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableFaleConoscoMensagemPendente").tablesorterPager({container: $("#pager-fale-conosco-mensagem-pendente")});
});
</script>
<?php  echo $this->formHidden('mesAnoFaleConoscoMensagemPendente',$this->mesAno) ?>
<table id="tableFaleConoscoMensagemPendente" cellspacing="1"
	class="tablesorter">
	<thead>
		<tr>
            <th class="span-1"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA'   )) ?></th>
			<th class="span-1"><?php echo $this->escape($this->translate('L_VIEW_GRID_NOME'   )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_ASSUNTO')) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_ACAO'   )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr>
			<td><?php echo date('d/m/Y H:i:s',strtotime($res['dt_registro'])) ?></td>
			<td><?php echo $res['tx_nome'] ?></td>
			<td><?php echo $res['tx_assunto'] ?></td>
			<td class="center">
				<button class="verde"
					onClick="respondeMensagem('<?php echo $res['cd_fale_conosco'] ?>', 2)"
					id="button_responder_<?php echo $res['cd_fale_conosco']?>"><?php echo $this->escape($this->translate('L_BTN_SANAR_PENDENCIA')) ?></button>
			</td>
		</tr>
	<?php
		endforeach;
	} else {
		echo "  <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	}
	?>
	</tbody>
</table>
<div id="pager-fale-conosco-mensagem-pendente" class="pager">
<form><img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png"
	class="first" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png"
	class="prev" /> <input type="text" class="pagedisplay" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png"
	class="next" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png"
	class="last" /> <select class="pagesize">
	<option selected="selected" value="10">10</option>
	<option value="20">20</option>
	<option value="30">30</option>
	<option value="40">40</option>
</select></form>
</div>