<div id="tabFaleConoscoMensagemAberta" class="boxTab">
    <label class="float-l" style="margin-top:2px; font-size:20px;" id="mesAnoFaleConoscoMensagemAberta"><?php echo $this->mesAno ?></label>
    <label class="float-r" style="margin-top:2px;"><?php echo $this->anoCombo('anoFaleConoscoMensagemAberta',null,null,1) ?></label>
    <label class="float-r" style="margin-top:2px;"><?php echo $this->mesCombo('mesFaleConoscoMensagemAberta') ?></label>
</div>
<div id="gridFaleConoscoMensagemAberta" class="float-l clear-l span-21"></div>
