<?php
//criando o objeto
$objPdf = new Base_Tcpdf_Pdf();

$arrKeywords = array(K_CREATOR_SYSTEM,
                     Base_Util::getTranslator('L_TIT_REL_QUESTIONARIO'),
                     Base_Util::getTranslator('L_VIEW_QUESTIONARIO'),
                     Base_Util::getTranslator('L_VIEW_RELATORIO')
                    );

//Inicia cabeçalho do relatório
$objPdf->iniciaRelatorio(Base_Util::getTranslator('L_TIT_REL_QUESTIONARIO'), $arrKeywords);

$objPdf->SetDisplayMode("real");
// add a page
$objPdf->AddPage();

$fontSize = 9;

if( count($this->arrProjeto) >0 ){
	$objPdf->SetFont('helvetica', 'B', $fontSize);
	$objPdf->Cell(180, 6, Base_Util::getTranslator('L_VIEW_INFORMACOES_PROJETO'), 'LRTB', 1, 'L');
	
	$objPdf->SetFont('helvetica', 'B', $fontSize);
	$objPdf->Cell(180, 6, Base_Util::getTranslator('L_VIEW_PROJETO'), 'LR', 0, 'L');
	$objPdf->Ln(4);
	$objPdf->SetFont('helvetica', '', $fontSize);
	$objPdf->Cell(180, 6, $this->arrProjeto['tx_projeto'], 'LR', 1, 'L');
	
	$objPdf->SetFont('helvetica', 'B', $fontSize);
	$objPdf->Cell(100, 6, Base_Util::getTranslator('L_VIEW_SIGLA'), 'L', 0, 'L');
	$objPdf->Cell(80, 6, Base_Util::getTranslator('L_VIEW_NR_PROPOSTA'), 'R', 0, 'L');
	$objPdf->Ln(4);
	$objPdf->SetFont('helvetica', '', $fontSize);
	$objPdf->Cell(100, 6, $this->arrProjeto['tx_sigla_projeto'], 'L', 0, 'L');
	$objPdf->Cell(80, 6, $this->cd_proposta, 'R', 1, 'L');
	
	$objPdf->SetFont('helvetica', 'B', $fontSize);
	$objPdf->Cell(100, 6, Base_Util::getTranslator('L_VIEW_GESTOR'), 'L', 0, 'L');
	$objPdf->Cell(80, 6, Base_Util::getTranslator('L_VIEW_UNIDADE_GESTORA'), 'R', 0, 'L');
	$objPdf->Ln(4);
	$objPdf->SetFont('helvetica', '', $fontSize);
	$objPdf->Cell(100, 6, $this->arrProjeto['tx_gestor_projeto'], 'L', 0, 'L');
	$objPdf->Cell(80, 6, $this->arrProjeto['tx_sigla_unidade'], 'R', 1, 'L');

	$objPdf->SetFont('helvetica', 'B', $fontSize);
	$objPdf->Cell(180, 6, Base_Util::getTranslator('L_VIEW_CONTEXTO_GERAL'), 'LR', 0, 'L');
	$objPdf->Ln(4);
	$objPdf->SetFont('helvetica', '', $fontSize);
	$objPdf->MultiCell(180,6,$this->arrProjeto['tx_contexto_geral_projeto'].PHP_EOL,'LRB','J',0,1,'','',true,0,true);
	$objPdf->Ln(5);
	
	if(count($this->arrGrupoFator) > 0){
		montaTableHtml($this->arrGrupoFator,$this->arrGrupoFatorItem,$objPdf);
	}
}

//Close and output PDF document
$objPdf->Output('relatorio_parecer_proposta.pdf', 'I');

function montaTableHtml($arrGrupoFator,$arrItemGrupoFator,$objPdf)
{
	$strHtml  = '';
	$strHtml .= '<table border="1" style="border-collapse: collapse; border: 1px solid #54BDCD; margin-left: 6px; width:810px;">
					<tbody>
						<tr>
							<td style="font-weight: bold; width: 360px;text-align: center;">'.Base_Util::getTranslator('L_VIEW_DESCRICAO').'</td>
							<td style="font-weight: bold; width: 30px; text-align: center;">(1)</td>
							<td style="font-weight: bold; width: 30px; text-align: center;">(2)</td>
							<td style="font-weight: bold; width: 30px; text-align: center;">(3)</td>
							<td style="font-weight: bold; width: 30px; text-align: center;">(4)</td>
							<td style="font-weight: bold; width: 30px; text-align: center;">(5)</td>
						</tr>';
	if(count($arrGrupoFator)>0){
		foreach($arrGrupoFator as $conteudo){
			$strHtml .= '<tr> <td colspan="6" style="font-weight: bold; width: 510px;">'.$conteudo['ni_ordem_grupo_fator'].' - '.$conteudo['tx_grupo_fator'].'</td></tr>';
			if(count($arrItemGrupoFator) > 0){
				foreach($arrItemGrupoFator[$conteudo['cd_grupo_fator']] as $key=>$value){
					$strHtml .= '	<tr>
										<td style="width: 360px;">&nbsp;&nbsp;&nbsp;&nbsp; '.$conteudo['ni_ordem_grupo_fator'].'.'.$value['ni_ordem_item_grupo_fator'].' - '.$value['tx_item_grupo_fator'].'</td>
										<td style="width: 30px; text-align: center;">(  )</td>
										<td style="width: 30px; text-align: center;">(  )</td>
										<td style="width: 30px; text-align: center;">(  )</td>
										<td style="width: 30px; text-align: center;">(  )</td>
										<td style="width: 30px; text-align: center;">(  )</td>
									</tr>';
				}
			} else {
				$strHtml .= '<tr> <td colspan="6" style="font-weight: bold; width: 510px;">'.Base_Util::getTranslator('L_VIEW_SEM_ITEM_CADASTRDO').'</td> </tr>';
			}
		}
	} else {
		$strHtml .= '<tr> <td colspan="6" style="font-weight: bold; width: 510px;"><i>'.Base_Util::getTranslator('L_VIEW_SEM_GRUPO_FATOR_ITEM_CADASTRDO').'</i></td> </tr>';
	}
	
    $strHtml .= '<tr>
                    <td style="width: 510px; text-align: center;" colspan="6"></td>
                </tr>';
    $strHtml .= '<tr>
                    <td style="width: 510px;" colspan="6"><b>'.Base_Util::getTranslator('L_VIEW_LEGENDA'      ).':</b> <b>(1)</b> '.
                                                               Base_Util::getTranslator('L_VIEW_MUITO_SATISFEITO'  ).' <b>(2)</b> '.
                                                               Base_Util::getTranslator('L_VIEW_SATISFEITO'        ).' <b>(3)</b> '.
                                                               Base_Util::getTranslator('L_VIEW_A_CONTENTO'        ).' <b>(4)</b> '.
                                                               Base_Util::getTranslator('L_VIEW_INSATISFEITO'      ).' <b>(5)</b> '.
                                                               Base_Util::getTranslator('L_VIEW_MUITO_INSATISFEITO').'</td>
					</tr>';
	$strHtml .= '	</tbody>
				</table><br />';
	
	$strHtml .= '<table border="1" style="border-collapse: collapse; border: 1px solid #54BDCD; margin-left: 6px; width:810px;">
					<tr>
						<td style="width: 510px;">'.Base_Util::getTranslator('L_MSG_ALERT_DESCRICAO_MOTIVO_INSATISFACAO').'</td>
					</tr>
				</table>';

	$objPdf->writeHTML($strHtml);
}
?>