<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableMudancaRegraNegocio").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableMudancaRegraNegocio").tablesorterPager({container: $("#tableMudancaRegraNegocioPager")}); 
});
</script>
<table id="tableMudancaRegraNegocio" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-7"><?php echo $this->escape($this->translate('L_VIEW_GRID_REGRA_DE_NEGOCIO')) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_VERSAO'       )) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_SITUACAO'     )) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_ACAO'         )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res):
		foreach ($this->res as $res):

			$fim = "";
			if(strlen($res['tx_regra_negocio']) >= 75):
				$fim = "...";
			endif;
			$tx_regra_negocio = substr($res['tx_regra_negocio'],0,75).$fim; 
	?>
		<tr>
			<td ><?php echo $tx_regra_negocio;					?></td>
			<td ><?php echo $res['ni_versao_regra_negocio'];	?></td>
			<td ><?php echo $res['st_fechamento_regra_negocio'];?></td>
			<td style="text-align: center;">
				<?php
					if( $res['st_fechamento_regra_negocio'] === 'Fechada'):
						if (array_key_exists('possui_pedido', $res) && ($res["possui_pedido"] == "S")) :
							echo $this->escape($this->translate('L_VIEW_PEDIDO_MUDANCA_SOLICITADO'));
						else:
							$click = "cadastrarMudancaRegraNegocio( '{$tx_regra_negocio}', {$res['cd_regra_negocio']}, '{$res['dt_regra_negocio']}')";
							echo $this->formButton('btn_pedir_mudanca_regra_negocio',$this->escape($this->translate('L_BTN_PEDIR_MUDANCA')),array('class'=>'verde','onclick'=>"{$click}"));
						endif;
					endif;
				?>
			</td>
		</tr>
	<?php
		endforeach;
	else:
		echo " <tr>
				<td colspan='4' style='text-align: center;'>".$this->escape($this->translate('L_VIEW_SEM_REGISTRO'))."</td>
			  </tr>";
	endif;
	?>
	</tbody>
</table>
<div id="tableMudancaRegraNegocioPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
