<?php
    $this->script('scriptFile',array('/associar-requisito-caso-de-uso/index.js'));
?>
<div style="margin-left: 17px;">
    <label class="span-3 float-l"><?php echo $this->escape($this->translate('L_VIEW_NOME_PROJETO')) ?>:</label>
        <p class="float-l clear-r bold"><?php echo $this->nomeProjeto; ?></p>
	
    <label class="span-3 float-l clear-l"><?php echo $this->escape($this->translate('L_VIEW_PROPOSTA')) ?>:</label>
        <p class="float-l clear-r bold"><?php echo $this->cd_proposta; ?></p>

	<hr class="span-20" style="border-top: 1px solid rgb(84, 189, 205); visibility: visible; height: 6px;"/>
	
	<label class="bold float-l span-3 required" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_REQUISITO')) ?>:</label>
	<?php 
	    echo $this->formSelect( 'cmb_requisitos_associar_requisito_caso_de_uso', null ,array('class'=>'span-6 float-l'), $this->arrRequisitosCasoDeUso );
	    echo $this->formButton('btn_associar_caso_de_uso_versao_anterior', mb_strtoupper($this->escape($this->translate('L_BTN_ATUALIZAR_VERSAO_CASO_DE_USO')),'utf-8'), array('class'=>'azul float-l push-2'));
	?>

	<?php
		echo $this->flipFlop(array('name'=>'caso_de_uso_1', 'label'=>$this->escape($this->translate('L_VIEW_CASOS_DE_USO'))),
							 array('name'=>'caso_de_uso_2', 'label'=>$this->escape($this->translate('L_VIEW_CASOS_DE_USO_ASSOCIADO'))),
							 'add_associacao_requisito_caso_de_uso',
							 'remove_associacao_requisito_caso_de_uso',8); ?>
</div>