<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl(); ?>/public/js/modules/default/perfil-menu/treeview-perfil-menu.js"></script>

<hr class="span-20" style="border-top: 1px solid rgb(84, 189, 205); visibility: visible; height: 6px;"/>
<?php
$menu = $this->treeviewMenu("red", $this->data, true, $this->menuPerfis);
$possuiPermissoesParaOPerfil  = $this->possuiPermissoesParaOPerfil;
?>
<script type="text/javascript">
    var possuiPermissoesParaPerfil    = '<?php echo $possuiPermissoesParaOPerfil; ?>';
</script>