<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tablePainelContrato").tablesorter({widthFixed: true, widgets: ['zebra']}) 
    $("#tablePainelContrato").tablesorterPager({container: $("#tablePainelContratoPager")}); 
});
</script>
<table id="tablePainelContrato" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th><?php echo $this->escape($this->translate('L_VIEW_GRID_NR_CONTRATO')) ?></th>
			<th><?php echo $this->escape($this->translate('L_VIEW_GRID_EMPRESA'    )) ?></th>
			<th><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_INICIO')) ?></th>
			<th><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_FIM'   )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr onclick="recuperaContrato(<?php echo $res['cd_contrato'] ?>)" style="cursor: pointer;">
			<td><?php echo $res['tx_numero_contrato'] ?></td>
			<td><?php echo $res['tx_empresa'] ?></td>
			<td><?php echo $res['dt_inicio_contrato'] ?></td>
			<td><?php echo $res['dt_fim_contrato'] ?></td>
		</tr>
	<?php
		endforeach;
	} else {
		echo "<tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
			  </tr> ";
	}
	?>
	</tbody>
</table>
<div id="tablePainelContratoPager" class="pager">
<form><img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png"
	class="first" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png"
	class="prev" /> <input type="text" class="pagedisplay" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png"
	class="next" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png"
	class="last" /> 
	<select class="pagesize">
		<option selected="selected" value="10">10</option>
		<option value="20">20</option>
		<option value="30">30</option>
		<option value="40">40</option>
		</select>
	</form>
</div>
