<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableCustoContratoMetrica").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableCustoContratoMetrica").tablesorterPager({container: $("#pager")}); 
});
</script>
<div id="formCustoContratoMetrica">
<table id="tableCustoContratoMetrica" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th><?php echo $this->escape($this->translate('L_VIEW_GRID_PROJETO')) ?></th>
			<th><?php echo $this->escape($this->translate('L_VIEW_GRID_QTD_UNIDADE_METRICA')) ?></th>
		</tr>
  </thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $key=>$res):
	?>
		<tr>
			<td class="span-5"><label class="float-l clear-l left">
				<?php echo $res['tx_sigla_projeto'] ?></label>
			</td>
			<td class="span-5">
				<?php
					echo $res['nf_qtd_unidade_metrica'];
				 ?>
			</td>
		</tr>
	<?php
		endforeach;
	} else {
		echo "	<tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	}
	?>
	</tbody>
</table>
</div>
<!--   precisar de botões para paginador -->
<div id="tableCustoContratoMetricaPager" class="pager">
	<form >
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
