<?php
    $this->script('validaForm');
    $this->script('scriptFile',array('/pedido-dependencia/index.js'))
?>

<div id="div_dependencia_pergunta" class="float-l clear-l span-21">
    <label class="float-l clear-l span-2 required" for="cd_pergunta"><?php echo $this->escape($this->translate('L_VIEW_PERGUNTA')) ?>:</label>
    <?php echo $this->formSelect('cd_pergunta', null, array('class'=>'float-l span-9'),$this->arrPergunta); ?>

    <label class="float-l clear-l span-2 required" for="cd_resposta"><?php echo $this->escape($this->translate('L_VIEW_RESPOSTA')) ?>:</label>
    <?php echo $this->formSelect('cd_resposta', null, array('class'=>'float-l span-9'),array('0'=>$this->escape($this->translate('L_VIEW_COMBO_SELECIONE')))); ?>

    <div class="float-l clear-l height-1 span-21"></div>

    <?php echo $this->flipFlop(array('name'=>'cd_pergunta_1', 'label'=>$this->escape($this->translate('L_VIEW_PERGUNTAS'))),
							   array('name'=>'cd_pergunta_2', 'label'=>$this->escape($this->translate('L_VIEW_PERGUNTAS_DEPENDENTES'))),
							   'add_pergunta',
							   'remove_pergunta',8); ?>
</div>