<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableEmpresa").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableEmpresa").tablesorterPager({container: $("#tableEmpresaPager")}); 
});
</script>
<table id="tableEmpresa" cellspacing="1" class="tablesorter" style="border-collapse: collapse;">
	<thead>
		<tr>
			<th class="{sorter: false}" width="15">&nbsp;</th>
			<th class="span-15"><?php echo $this->translate('L_VIEW_GRID_EMPRESA'); ?></th>
		</tr>
  </thead>
	<tbody>
	<?php
	if($this->res):
		foreach ($this->res as $res):
	?>
		<tr>
			<td><img id="imgExcluir" 
                     height="13"
                     width="13"
                     style="cursor:pointer;"
                     onclick="excluirEmpresa(<?php echo $res['cd_empresa'] ?>);"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->translate('L_VIEW_EXCLUIR'); ?>"/></td>
			<td onclick="recuperarEmpresa(<?php echo $res['cd_empresa'] ?>)" style="cursor: pointer;"><?php echo $res['tx_empresa'] ?></td>
		</tr>
	<?php
		endforeach;
	 else:
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	endif;
	?>
	</tbody>
</table>
<div id="tableEmpresaPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>