<?php
$this->script('scriptFile',array('/pre-demanda-andamento/index.js'));
?>
<div id="tabDemandaAndamento" class="divTab">
	<div class="boxTab ">
		<label class="float-l bold" style="margin-top:2px; font-size:16px;" id="mesAnoDemandaAndamento"><?php echo $this->mesAno ?></label>	
		 <div class="float-r campoBoxTab">
             <button id="nova_pre_demanda" class="azul" style="margin-top:5px;"><?php echo mb_strtoupper($this->escape($this->translate('L_BTN_NOVA_PRE_DEMANDA')), 'utf-8') ?></button>
		</div>	 
		<label class="float-r" style="margin-top:2px;"><?php echo $this->anoCombo('anoAnd', null,null,1) ?></label>
		<label class="float-r" style="margin-top:2px;"><?php echo $this->mesCombo('mesAnd') ?></label>
		<label class="float-r" style="margin-top:2px;"><?php echo $this->formSelect('cd_objeto_receptor', null, array('class' => 'span-5 float-l', 'style' => 'margin-right: 10px;'), $this->objetoCombo) ?></label>
	</div>
	<div id="gridPreDemandaAndamento"></div>
</div>