<script type="text/javascript">
$(document).ready(function() {
	// call the tablesorter plugin
    $("#tableAnaliseDispServico").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableAnaliseDispServico").tablesorterPager({container: $("#tableAnaliseDispServicoPager")});
});
</script>
<table id="tableAnaliseDispServico" cellspacing="1" class="tablesorter" >
	<thead>
		<tr>
			<th style="width: 10px;">&nbsp;</th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_OBJETO'      )) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_PERIODO'     )) ?></th>
			<th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_ANALISE'     )) ?></th>
			<th class="span-6"><?php echo $this->escape($this->translate('L_VIEW_GRID_PARECER'     )) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_INDICE'      )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_DOCUMENTACAO')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res):
		foreach ($this->res as $res):
	?>
		<tr>
			<td><img id="imgExcluir" 
                     height="13"
                     width="13"
                     style="cursor:pointer; text-align: center;"
                     onclick="excluiAnaliseDispServico('<?php echo $res['cd_objeto']; ?>','<?php echo $res['cd_disponibilidade_servico']; ?>');"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/></td>
			
			<?php
				$fimObjeto		 = "";
				if( strlen(strip_tags($res['tx_objeto'])) >= 10 ){
					$fimObjeto = "...";
				}
				$tx_objeto = substr(strip_tags($res['tx_objeto']),0,10);
			?>
			<td title="<?php echo $res['tx_objeto'] ?>" style="cursor: pointer;" onClick="recuperaDadosAnaliseDispServico('<?php echo $res['cd_objeto']; ?>','<?php echo $res['cd_disponibilidade_servico']; ?>')"><?php echo $tx_objeto.$fimObjeto; ?></td>

			<?php $periodo = date('d/m/Y', strtotime($res['dt_inicio_analise_disp_servico'])).'<br />'.date('d/m/Y', strtotime($res['dt_fim_analise_disp_servico'])); ?>
			<td title="<?php echo $this->escape($this->translate('L_VIEW_PERIODO_ANALISE')) ?>" style="cursor: pointer;" onClick="recuperaDadosAnaliseDispServico('<?php echo $res['cd_objeto']; ?>','<?php echo $res['cd_disponibilidade_servico']; ?>')"><?php echo $periodo; ?></td>

			<?php
				$fimTitleAnalise = "";
				$fimAnalise		 = "";
				if( strlen(strip_tags($res['tx_analise_disp_servico'])) >= 120 ){
					$fimTitleAnalise = "...";
				}
				if( strlen(strip_tags($res['tx_analise_disp_servico'])) >= 80 ){
					$fimAnalise = "...";
				}
				$titleAnalise	= substr(strip_tags($res['tx_analise_disp_servico']),0,120);
				$tx_analise		= substr(strip_tags($res['tx_analise_disp_servico']),0,80);
			?>
			<td title="<?php echo $titleAnalise.$fimTitleAnalise; ?>" style="cursor: pointer;" onClick="recuperaDadosAnaliseDispServico('<?php echo $res['cd_objeto']; ?>','<?php echo $res['cd_disponibilidade_servico']; ?>')"><?php echo $tx_analise.$fimAnalise; ?></td>

			<?php
				$fimTitleParecer = "";
				$fimParecer		 = "";
				if( strlen(strip_tags($res['tx_parecer_disp_servico'])) >= 120 ){
					$fimTitleParecer = "...";
				}
				if( strlen(strip_tags($res['tx_parecer_disp_servico'])) >= 100 ){
					$fimParecer = "...";
				}
				$titleParecer	= substr(strip_tags($res['tx_parecer_disp_servico']),0,120);
				$tx_parecer		= substr(strip_tags($res['tx_parecer_disp_servico']),0,100);
			?>
			<td title="<?php echo $titleParecer.$fimTitleParecer; ?>" style="cursor: pointer;" onClick="recuperaDadosAnaliseDispServico('<?php echo $res['cd_objeto']; ?>','<?php echo $res['cd_disponibilidade_servico']; ?>')"><?php echo $tx_parecer.$fimParecer; ?></td>

			<?php $titleIndice = ($res['ni_indice_disp_servico']) ? 'title="'.$this->escape($this->translate('L_VIEW_INDICE_OBTIDO_ANALISE')).'"': ''; ?>
			
			<td <?php echo $titleIndice; ?> style="cursor: pointer;" onClick="recuperaDadosAnaliseDispServico('<?php echo $res['cd_objeto']; ?>','<?php echo $res['cd_disponibilidade_servico']; ?>')"><?php echo $res['ni_indice_disp_servico']; ?></td>
			
			<td>
                <a style="cursor: pointer;" onclick="anexarDocumentacaoAnaliseDispServico('<?php echo $res['cd_objeto']; ?>','<?php echo $res['cd_disponibilidade_servico']; ?>')">
                    <?php echo $this->escape($this->translate('L_VIEW_ANEXAR_VISUALIZAR')) ?>
                </a>
            </td>
		</tr>
	<?php
		endforeach;
	else:
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	endif;
	?>
	</tbody>
</table>
<div id="tableAnaliseDispServicoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>