<div class="clear boxTab">
    <button id="btn_nova_analise_disponibilidade" class="azul float-r" style="margin-top: 2px;"><?php echo mb_strtoupper($this->escape($this->translate('L_BTN_NOVA_ANALISE')), 'utf-8') ?></button>

    <label class="float-l bold" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_OBJETO_CONTRATO')) ?>:</label>
	<?php echo $this->formSelect('cmd_objeto_disponibilidade_servico', null, array('class'=>'float-l span-4'), $this->arrObjetoContratoDemandaServico); ?>
</div>
<div id="grid_analise_disponibilidade" class="float-l clear-l"></div>
