<div class="divTab">
	<div class="clear boxTab">
        <label class="bold float-l span-5 right" for="cd_contrato_analise_execucao" style="margin-top:2px;"><?php echo $this->translate('L_VIEW_CONTRATO') ?>:</label>
			<?php echo $this->formSelect('cd_contrato_analise_execucao',null,array('class'=>'float-l'),$this->arrContratoAnaliseExecucao);?>

        <label class="bold float-l right clear-l span-5" for="cd_projeto_execucao" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_PROJETO_EXECUCAO')) ?>:</label>
			<?php  echo $this->formSelect('cd_projeto_execucao',null,array('class'=>'float-l'), array("0"=>$this->escape($this->translate('L_VIEW_COMBO_SELECIONE')))); ?>
		
		<button id="btn_nova_analise_execucao_projeto"
                class="azul float-r"
                style="margin: 0 5px 5px 5px;"
                onclick="habilitaAbaAnaliseExecucaoProjeto(true)">
            <?php echo mb_strtoupper($this->escape($this->translate('L_BTN_NOVA_ANALISE_EXECUCAO')),'utf-8') ?>
        </button>
    </div>
	<div id="gridAnaliseExecucaoProjeto"></div>
</div>