<?php
    $this->script('scriptFile',array('/perfil-box-inicio/index.js'));
?>
<div id="div_associacao_perfil_box_inicio" class="span-21">
    <label for="cd_perfil_box_inicio" class="float-l span-2 right required"><?php echo $this->escape($this->translate('L_VIEW_PERFIL')) ?>:</label>
	<?php echo $this->formSelect('cd_perfil_box_inicio', null, array('class'=>'span-7 float-l'), $this->perfilCombo);?>
	<label for="cd_objeto_box_inicio" class="float-l clear-l span-2 right required"><?php echo $this->escape($this->translate('L_VIEW_OBJETO')) ?>:</label>
	<?php echo $this->formSelect('cd_objeto_box_inicio', null, array('class'=>'span-7 float-l'), $this->objetoCombo);?>
	<hr />

	<div style="margin-left: 10px;">
		<?php echo $this->flipFlop(array('name'=>'cd_box_inicio_combo',
                                         'label'=>$this->escape($this->translate('L_VIEW_BOXES')),
                                         'value'=>$this->boxInicial),
								   array('name'=>'cd_box_inicio2',
                                         'label'=>$this->escape($this->translate('L_VIEW_BOXES_ASSOCIADOS')),
                                         'value'=>$this->boxInicial2),
								   'add_box_inicio',
								   'remove_box_inicio',8); ?>
	</div>
</div>
