<?php
    $this->script('scriptFile',array('/fechamento-extrato-mensal/index.js'));
?>
<div id="tabelaFechamentoExtratoMensal" class="divTab boxTab">
	<label class="span-2 float-l bold right" style="margin-top: 3px;"><?php echo $this->translate('L_VIEW_CONTRATO') ?>:</label>
	<p class="float-l" style="margin-top: 3px;"><?php echo $this->formSelect('cd_contrato', null, null, null) ?></p>
</div>
<div id="gridFechamentoExtratoMensal"></div>