<?php
    $this->script('scriptFile',array('/gerenciamento-mudanca/analise-mudanca-proposta.js'));
?>
<div class="clear boxTab">
	<label class="float-l bold" style="margin-top:2px; font-size:16px;" id="mesAnoAnaliseMudancaProposta"><?php echo $this->mesAno ?></label>
	<label class="float-r" style="margin-top:2px;"><?php echo $this->anoCombo('anoAnaliseMudancaProposta', $this->anoComboValue,null,1) ?></label>
	<label class="float-r" style="margin-top:2px;"><?php echo $this->mesCombo('mesAnaliseMudancaProposta', $this->mesComboValue) ?></label>
</div>
<div id="gridGerenciamentoMudancaProposta"></div>
