<?php
    $this->script('scriptFile',array('/medicao/analise-medicao.js'));
?>
<div id="conteiner_analise" class="divTab">
	<div class="clear boxTab">
        <button id="btn_nova_analise_medicao" class="azul float-r" style="margin-top:2px; margin-bottom: 6px;">
            <?php echo $this->escape($this->translate('L_BTN_NOVA_ANALISE_MEDICAO')) ?>
        </button>
	</div>
	<div id="gridAnaliseMedicao"></div>
</div>