<?php 
    $this->script('validaForm') ;
    $this->script('scriptFile',array('/inventario/index.js'));
?>
<form id="formRelatorioInventario">
    <label class="span-4 float-l clear-l right required" for="cd_area_atuacao_ti"><?php echo $this->translate('L_VIEW_AREA_ATUACAO_TI') ?>:</label>
    	<?php echo $this->formSelect("cd_area_atuacao_ti",null,array('class'=>'float-l'),$this->comboAreaAtuacaoTI); ?>
    <label class="float-l span-4 right clear-l required" for="cd_inventario"><?php echo $this->escape($this->translate('L_VIEW_NOME_INVENTARIO')) ?>:</label>
	<?php echo $this->formSelect('cd_inventario', null, array('class'=>'float-l span-4'), null); ?>
	<button class="buttonBar verde" id="btn_gerar" name="btn_gerar" type="button"><?php echo $this->translate('L_BTN_GERAR') ?></button>
</form>