<?php
    $this->script('scriptFile',array('/gerenciar-projetos-execucao-proposta/index.js'));
?>
<div id="tabelaExecucao" class="divTab">
	<div class="clear boxTab">
		<label class="float-l bold" style="margin-top:2px; font-size:16px;" id="mesAnoProjetoExecucao"><?php echo $this->mesAno ?></label>
		<label class="float-r" style="margin-top:2px;"><?php echo $this->anoCombo('anoExec', $this->anoComboValue,null,1) ?></label>
		<label class="float-r" style="margin-top:2px;"><?php echo $this->mesCombo('mesExec', $this->mesComboValue) ?></label>
	</div>
	<div id="gridExecucaoProposta"></div>
</div>