<script type="text/javascript">
    $(document).ready(function() {
        $("#tablePedidoComite").tablesorter({widthFixed: true, widgets: ['zebra']});
        $("#tablePedidoComite").tablesorterPager({container: $("#tablePedidoComitePager")});
    });
</script>
<table cellspacing="1" id="tablePedidoComite" class="tablesorter" >
    <thead>
        <tr>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_SOLICITACAO')) ?></th>
            <th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_SOLICITANTE')) ?></th>
            <th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_UNIDADE_SOLICITANTE')) ?></th>
            <th class="span-8"><?php echo $this->escape($this->translate('L_VIEW_GRID_OBSERVACAO_PEDIDO')) ?></th>
        </tr>
    </thead>
    <tbody>
	<?php if(count($this->pedidos)): ?>
        <?php foreach($this->pedidos as $rs):?>
            <tr>
                <td style="cursor: pointer;" onclick="recuperaHistoricoPedido(<?php echo $rs->cd_solicitacao_pedido ?>)" ><?php echo date('d/m/Y', strtotime($rs->dt_solicitacao_pedido)) ?></td>
                <td style="cursor: pointer;" onclick="recuperaHistoricoPedido(<?php echo $rs->cd_solicitacao_pedido ?>)" ><?php echo $rs->tx_nome_usuario ?></td>
                <td style="cursor: pointer;" onclick="recuperaHistoricoPedido(<?php echo $rs->cd_solicitacao_pedido ?>)" ><?php echo $rs->tx_sigla_unidade ?></td>
                <td style="cursor: pointer;" onclick="recuperaHistoricoPedido(<?php echo $rs->cd_solicitacao_pedido ?>)" ><?php echo $rs->tx_observacao_pedido ?></td>
            </tr>
        <?php endforeach; ?>
	<?php else:
            echo " <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                  </tr>";
        endif; ?>
    </tbody>
</table>
<div id="tablePedidoComitePager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
		</select>
	</form>
</div>