<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/aceite-proposta.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        Essa tela é cadastrado o Aceite da Proposta.<br>
        1, Aceite (campo obrigatório): selecione Sim se o cliente aceitou a  proposta (plano de projeto) ou Não caso contrário.<br>
        2. Observações: transcreva as observações registrada no aceite.<br><br>
        Tecle "Salvar" para gravar o aceite.
    </p>
</div>
