<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/aceite-parcela.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        Essa tela é cadastrado o Aceite da Parcela. <br>
        1, Aceite (campo obrigatório): selecione sim se o cliente aceitou os produtos da parcela ou não caso contrário.<br>
        2. Observações: transcreva as observações registrada no aceite.<br><br>
        Tecle "Salvar" para gravar o aceite.
        </p>
</div>
