<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/acompanhamento-interno/documentacao-acompanhamento.png" alt="Tela Ajuda" />
	<p style="text-align: left;">
        A tela Documentação de acompanhamento permite anexar documentos eletrônicos referentes ao acompanhamento.<br>
        1) Documentação (campo obrigatório): selecione qual documentação está sendo anexada.<br>
        2) Arquivo: selecione o arquivo.<br>
        Para anexar o arquivo tecle o botão "Anexar Arquivo".<br>
        </p>
</div>
