<div class="divConteudoAjuda">
	<div align="center">
		<img src="<?php echo $this->baseUrl();?>/public/img/ajuda/projeto/acrescentar-produtos.png" alt="Tela Ajuda" />
	</div>
	<p style="text-align: center; ">
		A tela de Acréscimo de Produtos possibilita a inclusão dos produtos a serem
		executado durante determinada parcela.<br>
	
		Os Produtos são adicionados às parcelas durante a fase de elaboração da proposta.
	</p>
</div>
