<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/administracao.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">O Painel de Administração permite que o administrador possa
		definir os perfis e menus de acesso ao sistema,
		definir as métricas para medição de custo de projetos,
		definir os boxes de informações estatísticas que aparecerão na tela de início do sistema,
		visualizar e responder as mensagens enviadas ao Fale Conosco e
		visualizar as informações do registro de log.</p>
</div>
