<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/login/login.png" alt="Tela Ajuda" />
<p>
	Tela de acesso ao sistema. Caso seja seu primeiro acesso, digite apenas o login fornecido pelo Administrador e tecle "Enter" ou clique em "Acessar"
	para ser direcionado à página de cadastro de senha que é apresentada abaixo.
</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/login/login-nova-senha.png" alt="Tela Ajuda" />
<p>
	Tela de cadastre de nova senha. Digite a senha deseja e clique em "Salvar".
	Em seguida você será direcionado novamente para a página de acesso ao sistema.
<p>