<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/alocacao-recurso-proposta.png" alt="Tela Ajuda" />
	<p style="text-align: left; ">
        Essa tela tem a finalidade de alocar os recursos (valores em unidade de métrica) de uma proposta.
        Os valores apresentados no início refere-se:
        a)[unidade de métrica] da Proposta : indica a quantidade de unidade de métrica estabelecida na proposta.<br>
        b)[unidade de métrica] a Serem Alocadas dentro do Período do Contrato: indica a quantidade de unidade de métrica a serem alocadas da proposta no periodo do contrato.<br>
        c)[unidade de métrica] já Alocado para a Proposta: indica a quantidade de unidade de métrica já alocada à proposta.<br>
        d)[unidade de métrica] já Alocado dentro do Período do Contrato: indica a quantidade de unidade de métrica já alocada no período do contrato.<br>
        e)Diferença [unidade de métrica] a Serem Alocadas dentro do Período do Contrato X Recurso Alocado: indica a quantidade de [unidade de métrica] a ser alocado para a proposta.<br>
        f)Diferença [unidade de métrica] a Serem Alocadas Módulo Proposa X Recursos Alocados: indica a quantidade de [unidade de métrica] a serem alocadas referente ao módulo proposta, isto é, no caso de se optar por pagamento de pelo plano de projeto de projetos novos.<br><br>
        A lista que aparece trata-se dos projetos previstos cadastrados para o contrato com os respectivos valores de [unidade de métrica] .<br>
        Às colunas Créditos e Débitos indica a quantidade de [unidades de métrica] creditadas ou debitadas respectivamente. <br>
        A coluna Saldo indica a quantidade de [unidade de métrica] sobrando daquele projeto previsto.<br>
        A coluna [unidade de métrica] Alocação contem um campo texto para colocar o valor a ser alocado. O valor em vermelho é o necessário para a alocação. Se possuir mais de um projeto previsto, pode-se optar em usar saldos de outros projetos, restringindo à soma de todos ao valor em vermelho.<br>
        A coluna [unidade de métrica] Módulo Proposta refere-se à quantidade de [unidade de métrica] a ser pago para elaboração da proposta.<br>
        Para gravar os valores estabelecidos clique no botão "Salvar".<br>

        </p>
</div>
