<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/alocacao-recurso-proposta-contrato-anterior-lista.png" alt="Tela Ajuda" />
	<p style="text-align: center;">Essa funcionalidade permite que planos de projetos (propostas) <br>
                                   não concluídos possa ser alocados no novo contrato dando continuidade ao projeto. <br>
                                   Ao clicar o botão Alocar Recurso a tela abaixo aparece para realizar a alocação.</p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/alocacao-recurso-proposta-contrato-anterior-alocar.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">Normalmente, quando se aloca recurso para uma plano de projeto (proposta), o OASIS aloca somente<br>
                                    até o mês de encerramento daquele contrato. Se o plano de projeto ultrapassa o mês de encerramento<br>
                                    o restante deverá ser alocado no próximo contrato. Utiliza-se dessa funcionalidade para realizar essa alocação.<br>
                                    <b>IMPORTANTE:</b> Antes de utilizar essa função desaloque tudo que ficou pendente do contrato anterior.
    </p>
</div>