<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/analise-execucao-projeto.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Analise de Execução relaciona as analise de execução realizadas para um projeto de um contrato.<br>
        1) Contrato: selecione o contrato.<br>
        2) Projeto em Execução: selecione o projeto.<br><br>
        Para realizar uma nova análise clique no Botão Nova Análise de Execução".<br>
        Enquanto estiver realizando a análise, pode-se reedita-la. Para isso clique no botão "Alterar Análise".<br>
        Quando finalizar a análise esta pode ser fechada clicando no botão "Fechar Análise".<br>

        </p>
</div>
