<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/area-conhecimento.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
   A tela de Cadastro de Área de Conhecimento permite que se cadatre as áreas de conhecimeto que serão incluídas na Base de Conhecimento.
   1) Área Conhecimento (campo obrigatório): escreva a área de conhecimento.<br><br>
   Para salvar uma área de conhecimento tecle no botão "Salvar".<br>
   Para atualizar uma área de conhecimento tecle sobre a área desejada, preencha os dados e clique no botão "Salvar".<br>
   </p>
</div>
