<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/associar-projeto-contrato.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite associar projetos a um contrato.<br><br>
		1. Contrato : contratos com objeto do contrato do tipo "Projeto".<br>
		2. Projetos : projetos não associados ao contrato.<br>
		3. Projetos Vinculados ao Contrato : projetos associados ao contrato.<br><br>
		Para associar um projeto ao contrato, selecione um contrato,
		selecione o(s) projeto(s) na lista "Projetos" e clique no botão ">>".<br>
		Para desassociar um projeto do contrato, selecione um contrato,
		selecione o(s) projeto(s) na lista "Projetos Vinculados ao Contrato" e clique no botão "<<".<br>
	</p>
</div>

