<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/associar-rotina-objeto-contrato.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        Essas telas permitem associar as rotinas a um objeto do contrato..<br>
        Após escolher o objeto de contrato e a área de atuação de TI desejado, selecione a rotina.<br>
        Aparecerá a lista de rotinas cadastradas. Associe as rotinas movendo as rotinas desejadas de uma caixa para a outra caixa.<br>
        
    </p>
</div>