<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/associar-perfil-papel-objeto-contrato.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        Essas telas permitem associar os perfis e os papeis a um objeto do contrato..<br>
        Após escolher o objeto de contrato e a área de atuação de TI desejado, selecione o perfil.<br>
        Aparecerá a lista de perfis cadastrados. Associe os perfis movendo os perfis desejados de uma caixa para a outra caixa.<br>
        Idem para o papel profissional.<br>
    </p>
</div>