<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/associar-atividade.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        Essa tela permite associar as atividades para um objeto de contrato.<br>
        Após escolher a área de atuação de TI equivalente ao objeto de contrato desejado, selecione o objeto e a etapa desejada.<br>
        Aparecerá a lista de atividades cadastradas para aquela etapa. Associe a atividade movendo as atividades desejadas de uma caixa para a outra caixa.<br>
    </p>
</div>