<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/associar-requisito-regra-negocio.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
         A tela Requisitos e Regra de Negócio permite associar as Regras de Negócio com os requisitos para desenhar a matriz de rastreabilidade.<br>
        1) Requisito (campo obrigatório): selecione o requisito.<br>
        2) Regras de Negócio: selecione as regras de negócio e clique no botão ">>".<br>
        Para atualizar a versão das regras de negócio clique no botão "Atualizar Versão das Regras de Negócio".<br>
        </p>
</div>
