<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/associar-requisito-caso-de-uso.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Requisitos e Caso de Uso permite associar os Casos de usos com os requisitos para desenhar a matriz de rastreabilidade.<br>
        1) Requisito (campo obrigatório): selecione o requisito.<br>
        2) Casos de Uso: selecione os casos de uso e clique no botão ">>".<br>
        Para atualizar a versão dos caso de uso clique no botão "Atualizar Versão dos Casos de Uso".<br>
        </p>
</div>
