<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/atividade.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite cadastrar uma atividade para uma etapa de ciclo de vida de projeto.<br><br>
		1. Objeto : objetos de contrato.<br>
		2. Etapa : etapa de ciclo de vida de projeto.<br>
		3. Atividade : nome da atividade de ciclo de vida de projeto.<br>
		4. Ordem : ordem em que a atividade será executada.<br>
		5. Descrição : descrição da atividade de ciclo de vida de projeto.<br><br>
		Para cadastrar uma atividade, preencha os campos e clique no botão "Salvar".<br>
		Para alterar uma atividade, clique no nome da atividade na tabela, preencha os campos e clique no botão "Salvar".<br>
		Para excluir uma atividade, clique no nome da atividade na tabela e clique no botão "Excluir".<br>
	</p>
</div>

