<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/autorizacao-parcela.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
          Essa tela tem a finalidade de autorizar a Parcela a ser executada.
          1) Observações: coloque as observações, caso necessário, referente a parcela a ser autorizada.<br>
          Clique no botão "Salvar" para autorizar a parcela a ser executada.
        </p>
</div>
