<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/baseline.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Baseline lista as datas das baselines geradas para um projeto.<br>
        1) Projeto: selecione o projeto.<br><br>
        Para gerar uma nova baseline clique o botão "Gerar Nova Baseline".<br><br>
        OBS: As baselines registram a proposta, rquisitos, regras de negócio e caso de uso. Ainda não existe interface com o SVN para registrar código.<br>

        </p>
</div>
