<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/box-inicio.png" alt="Tela Cadastro de Box para a tela de início" />
	<p style="text-align: justify;">
		Esta tela permite que se cadatre os boxes de informações estatísticas que são mostrados na tela inicial do sistema.<br><br>
		1. Nome (campo obrigatório): nome do box.<br>
		2. Título (campo obrigatório) : título do box.<br>
		3. Tipo (campo obrigatório): tipo da informação do box. O tipo pode ser "Projeto", "Demanda" ou "Ambos".<br><br>
		Para cadastrar o box, preencha os campos e clique no botão "Salvar".
	</p>
</div>

