<div class="divConteudoAjuda">
    <div align="center">
        <img src="<?php echo $this->baseUrl();?>/public/img/ajuda/projeto/caso-de-uso-definicao.png" alt="Tela Ajuda" />
    </div>
	<p style="text-align: center; ">
        A tela de definição de Caso de Uso possibilita a descrição dos casos de uso
        do sistema. <br>
   
        Para a definição de um Caso de Uso é necessário a escolha do módulo ao qual
        o caso de uso faz parte. Todos os item são obrigatórios para o cadastro.
    </p>
</div>
