<div class="divConteudoAjuda">
    <div align="center">
        <img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/caso-de-uso-complemento.png" alt="Tela Ajuda" />
    </div>
	<p style="text-align: center; ">
        Esta tela possibilita o cadastramento dos complementos de cada caso de uso.
        os complementos estão classificados em três tipos:
  
    <ul>
        <li>Exceção</li>
        <li>Regra</li>
        <li>Fluxo Alternativo</li>
    </ul>
  
        Ao selecionar um módulo e um caso de uso será apresentado três listagem
        com os complementos de acordo com os tipos já cadastrados.
    </p>
</div>
