<div class="divConteudoAjuda">
	<div align="center">
        <img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/caso-de-uso-interacao.png" alt="Tela Ajuda" />
    </div>
	<p style="text-align: center; ">
        As interações são definidas entre o sistema e os atores do sistema.<br>
    
        É necessário a escolha do módulo, do caso de uso e do ator que irá interagir
        com o sistema para poder definir as interações.
    </p>

</div>
