<div class="divConteudoAjuda">
	<div align="center">
        <img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/caso-de-uso.png" alt="Tela Ajuda" />
    </div>
	<p style="text-align: center; ">
        Aqui são cadastrados os casos de uso referentes ao projeto, seus atores,
        suas iterações e complementetos.
        Assim como é possível efetuar o fechamento das versões de cada caso de uso.<br>
    
        Ao final de todas as etapas do cadastramento dos casos de uso é necessário
        que se efetue a confirmação das informações prestadas para que o fluxo
        possa ser seguido.
    </p>
</div>
