<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/condicao-sub-item-metrica.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite o cadastro de condições para um subitem de métrica.<br><br>
		1. Métrica (campo obrigatório): métrica de custo de projeto.<br>
		2. Item de Métrica (campo obrigatório) : item da métrica de custo de projeto.<br>
		3. Subitem de Métrica (campo obrigatório) : subitem da métrica de custo de projeto.<br>
		4. Condição (campo obrigatório) : condição para o subitem da métrica de custo de projeto.<br>
		5. Valor (campo obrigatório) : valor que substituíra o subitem na fórmula caso a condição seja satisfeita.<br>
	</p>
</div>
