<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/profissional/conhecimento-profissional.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Associar Conhecimento ao Profissional permite associar os conhecimentos que o profissional tem proficiência.<br>
        1) Profissional: selecione o profissional.<br>
        2) Tipo de Conhecimento: selecione o tipo de conhecimento.<br>
        3) Conhecimneto: selecione os conhecimentos e tecle o botão ">>".<br>
</div>
