<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/conhecimento.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
    A tela de Cadastro de Conhecimento permite que se cadatre os conhecimentos específicos para um tipo de conhecimento.<br>
   1) Tipo de COnhecimento (campo obrigatório): selecione um tipo de conhecimento.<br>
   2) Conhecimento (campo obrigatório): escreva o conhecimento.<br><br>
   Para salvar um conhecimento clique no botão "Salvar".<br>
   Para atualizar um conhecimento clique sobre o desejado, preencha os dados e clique no botão "Salvar".<br>

</p>
</div>
