
<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/controle.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
    O Painel de Controle permite manipular os processos de controle e fiscalização das
		propostas e parcelas,
                aplicar Penalizações,
		aplicar o Questionário de Avaliação ao usuário de um projeto,
                aplicar as Ocorrências Administrativas,
                incluir Documentações de Projetos,e
                incluir informações de disponibilidade de serviços.

</p>
</div>
