<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/contrato.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite cadastrar um contrato de terceirização de serviços de tecnologia da informação.<br><br>
		1. Empresa (campo obrigatório) : empresa contratada.<br>
		2. Preposto (campo obrigatório): nome da pessoa que será o contato com a empresa.<br>
		3. Número do Contrato (campo obrigatório): número gerado para o contrato. Deve ter o formato NN/AAAA. Ex: 45/2008.<br>
		4. Número do Processo (campo obrigatório) : número do protocolo registrado para o contrato.<br>
		5. Data de Início (campo obrigatório): data de início de vigência do contrato.<br>
		6. Data de Fim (campo obrigatório): data final de vigência do contrato.<br>
		7. Valor do Contrato (campo obrigatório): valor do contrato em moeda corrente.<br>
		8. Gestor do Contrato (campo obrigatório): nome do gestor do contrato.<br>
		9. CPF do Gestor (campo obrigatório): número do CPF do gestor do contrato.<br>
		10. Objeto (campo obrigatório): objeto do contrato de acordo com o definido no texto do contrato.<br><br>
		Para cadastrar um contrato, preencha os campos e clique no botão "Salvar".<br>
		Para alterar um contrato, clique na linha da tabela da aba Lista com o número do contrato, preencha os campos e clique no botão "Salvar".<br>
		Para excluir um contrato, clique na linha da tabela da aba Lista com o número do contrato, e clique no botão "Excluir".<br>
	</p>
</div>

