<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/contrato-definicao-metrica.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite associar métricas de cálculo de custo de projeto a um contrato
		com objeto do contrato do tipo "Projeto".<br><br>
		1. Contrato : contratos com objeto do contrato do tipo "Projeto" .<br>
		2. Definições de Métrica : lista de métricas de cálculo de custo de projeto não associadas ao contrato.<br>
		3. Definições de Métrica Associadas : lista de métricas de cálculo de custo de projeto associadas ao contrato.<br><br>
		Para associar uma métrica ao contrato, selecione um contrato,
		selecione a(s) métrica(s) na lista "Definições de Métrica" e clique no botão ">>".<br>
		Para desassociar uma métrica do contrato, selecione um contrato,
		selecione a(s) métrica(s) na lista "Definições de Métrica Associadas" e clique no botão "<<".
	</p>
</div>

