<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/controle-parcela.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
    O Painel de Controle de Parcelas permite que o controle e fiscalização realize os processos de autorização, fiscalização e homologação de uma parcelas.<br>
    1) Todo o início de mês deve-se autorizar a parcela do mês para que a empresa realize os seus produtos definidos.<br>
       Para isso clique no ícone "Autorização" autorizando a execução da parcela.
    2) Quando a empresa termina o produto, é realizado o fechamento que aparecendo o tick verde informando o fechamento.<br>
    3) Após o fechamento será liberado o ícone de Parecer Técnico para sua realização. Para isso clique no ícone do parecer técnico da parcela desejada e registre o parecer.<br>
    4) Ao registrar o parecer técnico será liberado o ícone de Aceite. Após reunião com o usuário gestor do projeto, registre o aceite da parcela clicando no ícone Aceite.<br>
    5) Após o registro do aceite, é liberado a homologação que concluirá o processo de controle e liberará a parcela para pagamento.<br><br>
    OBS: Caso seja a última parcela da proposta é necessário realizar o encerramento da proposta para liberação da parcela para pagamento.

    </p>
</div>
