<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/controle-encerramento-proposta.png" alt="Tela Ajda" />
<p style="text-align: center; ">
  A tela Encerramento Proposta permite finalizar uma proposta. <br>
  Para encerrar uma proposta deve-se clicar no botão "Encerrar" relativo à proposta desejada.<br><br>

  Esse procedimento será necessário sempre que a última parcela de uma proposta seja realizada.<br>
  Nessa situação o controle ou fiscalização deverá verificar se todos os artefatos e documentações estão concluídos antes do encerramento<br>
  A última parcela somente será fechada para pagamento após realização desse procedimento..

  </p>
</div>
