<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/controle-proposta.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">

       O Painel de Controle de Proposta permite que o controle e fiscalização realize os processos de fiscalização, homologação e alocação de uma proposta.<br>
    1) Quando a empresa termina de elaborar uma proposta, é realizado o fechamento que aparecendo um tick verde informando o fechamento.<br>
    2) Após o fechamento será liberado o ícone de Parecer Técnico para sua realização. Para isso clique no ícone de parecer técnico referente a proposta desejada e registre o parecer.<br>
    3) Ao registrar o parecer técnico será liberado o ícone de Aceite. Após reunião com o usuário gestor do projeto, registre o aceite da proposta clicando no ícone Aceite.<br>
    4) Após o registro do aceite é liberado a homologação que deve ser clicado para realizar a homologação.<br>
    5) Após o registro da homologação é liberado a alocação que concluirá o processo de controle e aprovará a proposta para ser realizada.<br><br>
        </p>
</div>
