<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/contato-empresa.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite cadastrar um contato de empresa. Os contatos cadastrados podem ser utilizados
		como preposto da empresa em um contrato.<br><br>
		1. Empresa : empresa a qual pertence o contato.<br>
		2. Contato : nome da pessoa que será o contato com a empresa.<br>
		3. Telefone : telefone do contato da empresa.<br>
		4. E-mail : e-mail do contato da empresa.<br>
		5. Observação : observações sobre o contato da empresa.<br><br>
		Para cadastrar um contato de empresa, preencha os campos e clique no botão "Salvar".<br>
		Para alterar um contato de empresa, clique no nome do contato de empresa, preencha os campos e clique no botão "Salvar".<br>
		Para excluir um contato de empresa, clique na imagem de lixeira ao lado do nome do contato de empresa.<br><br>
		Obs: o e-mail cadastrado para o contato da empresa indicado no cadastro de um contrato com a empresa como preposto
		será utilizado para notificação de sanções. Portanto, deve ser um e-mail existente e constantemente acessado.<br>
	</p>
</div>

