<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/controle-alteracao-proposta.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
    A tela para Alteração de Proposta permite que se libere uma proposta em execução para ser alterada.<br>
    1) Contrato: selecione o contrato <br>
    2) Projeto: selecione o projeto a ter a proposta alterada <br><br>
    Clique no botão "Abrir Proposta" para liberar a proposta para alteração.<br>
    Após esse procedimento a proposta deverá ser novamente fiscalizada e aprovada.
 </p>
</div>
