<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/pre-demanda-coordenador/coordenador-pre-demanda-lista.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        
        A tela relaciona as pré-demandas enviadas para a coordenação para serem encaminhadas. </p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/pre-demanda-coordenador/coordenador-pre-demanda-executada.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela lista as pré-demandas já executadas. </p>
</div>