<div class="divConteudoAjuda">
	<div align="center">
		<img src="<?php echo $this->baseUrl();?>/public/img/ajuda/projeto/criacao-parcelas.png" alt="Tela Ajuda" />
	</div>
	<p style="text-align: center; ">
		Na tela de Criação das Parcelas é possível definir as parcelas a serem
		executadas durante a execução da proposta de acordo com o saldo disponível
		de unidades de métrica para o projeto.<br>
	
		É possível também alterar as parcelas já criadas para ajustar a quantidade
		de unidade de métrica definidadas para a parcela.
	</p>
</div>
