<div class="divConteudoAjuda">
    <div align="center">
        <img src="<?php echo $this->baseUrl();?>/public/img/ajuda/projeto/criacao-parcelas.png" alt="Tela Ajuda" />
    </div>
	<p style="text-align: center; ">
        As parcelas são mensais e criadas de acordo com o cronograma de execução do projeto.
        Cada parcela deve conter a quantidade de unidades de métrica previstas para
        a sua execução.
    </p>
</div>