<div class="divConteudoAjuda">
    <div align="center">
        <img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/dados-tecnicos.png" alt="Tela Ajuda" />
    </div>
   <p style="text-align: center; ">
        Nesta tela são definidos os conhecimentos que serão utilizado para o desenvolvimento
        do sistema em questão.<br>
    
        Para isso é necessário selecionar o tipo de conhecimento a ser utilizado
        para o preenchimentos dos possíveis conhecimentos cadastrados. Em seguida
        basta selecionar os conhecimentos que deseja associar a proposta (painel da esquerda)
        e clicar no botão de associação ">>". Caso necessite remover algum conhecimento já
        definido para a proposta basta selecionar o conhecimento (painel da direita) e
        clicar no botão de remoção da associação "<<".
    </p>
</div>
