<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/definicao-metrica.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite o cadastro de métricas para cálculo de custo de projetos.<br><br>
		1. Nome (campo obrigatório): nome da métrica.<br>
		2. Sigla (campo obrigatório) : sigla da métrica.<br>
		3. Descrição (campo obrigatório) : descrição da métrica.<br>
		4. Fórmula (campo obrigatório) : fórmula de cálculo da métrica.<br>
		5. Sigla da Unidade de Medida (campo obrigatório) : sigla da unidade de medida da métrica.<br>
		6. Unidade de Medida (campo obrigatório) : descrição da unidade de medida da métrica.<br>
		7. Com justificativa : indicador de que a métrica necessita de justificativa para sua utilização no projeto.<br>
	</p>
</div>
