<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/executar-demanda/demanda-executor-demanda-solicitada.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela listas as demandas para execução.</p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/executar-demanda/demanda-executor-demanda-executada.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela lista as demandas executadas. </p>
</div>
