<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/demanda/demanda.png" alt="Tela Ajuda" />
<p style="text-align: center; "> 
    A tela de Cadastramento de Demanda permite que o usuário cadastre uma demanda.
    1) Solicitante (campo obrigatório): nome do solicitante.<br>
    2) Unidade Solicitante (campo obrigatório): selecione a unidade.<br>
    3) Descrição (campo obrigatório): descreva o pedido da demanda.<br>
    4) Nivel de Serviço (campo obrigatório): selecione o nível de serviço para a demanda.<br>
    5) Profissional a Executar (campo obrigatório): selecione o profissional que irá realizar a demanda.<br>
    6) Prioridade (campo obrigatório): selecione a prioridade da demanda.<br>
    7) observações: se necessário escreva as observações relacionadas à demanda.<br><br>
    Para registrar a demanda e enviar para o profissional designado clique o botão "Designar Profissional".<br>
    Caso deseje designar outro profissional para realizar a demanda basta preencher novos detalhes de execução e designar outro profissional.<br>
</p>
</div>
