<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/desalocacao-recurso-proposta-lista.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
                    Quando um contrato acaba e os recursos alocados não são concluídos, é necessário realizar essa funcionalidade.<br>
                    Essa funcionalidade desaloca recurso não realizado para que o projeto possa alocar os recursos faltantes <br>
                    para o novo contrato.<br>
                    <b>IMPORTANTE:</b> Após passar um ano, o contrato pode ser continuano. Nesse caso é necessário estabelecer <br>
                    um novo contrato para dar continuidade nos projetos.
    </p>
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/desalocacao-recurso-proposta-desalocar.png" alt="Tela Ajuda" />
	<p style="text-align: center;">Essa funcionalidade permite desalocar recursos alocados não realizados. </p>
</div>