<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/logo4.png" alt="Tela Ajuda Indisponível" />
	<p style="text-align: center; ">
        A tela Dicionário de Dados - Configurações do Banco de Dados permite estabelecer os dados de conexão ao banco do projeto.<br>
        1) Banco de dados: selecione o adapter do banco de dados utilizado.<br>
        2) Servidor: endereço do servidor de banco de dados.<br>
        3) Nome do Banco de Dados: nome do banco de dados do projeto.<br>
        4) Schema: nome do schema do projeto.<br>
        5) Usuário de Acesso: nome do usuário de acesso.<br>
        6) Senha de acesso: senha de acesso ao banco de dados.<br>
        Para salvar os dados clique no botão "Salvar".<br>
        Todos os campos são obrigatórios.
        </p>
</div>
