<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/logo4.png" alt="Tela Ajuda Indisponível" />
	<p style="text-align: center; ">
        A tela Dicionário de dados  - Documentar permite documentar as tabelas e campos do projeto.<br>
        Os nomes das tabelas e dos campos serão trazidos pelo Oasis e as definições são entradas pelo usuário.<br>
        Para salavr as informações clique o botão "Salvar".<br><br>
        OBS: Se as tabelas e campos tiverem sido comentadas diretamente no banco, os dados serão trazidos.<br>
        </p>
</div>
