<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/disponibilidade-servico.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">

        A tela de Análise de Disponibilidade permite que seja registrado as análises de disponibilidade de serviço.
        1) Objeto do Contrato: selecione o objeto de contrato desejado para análise.<br>
        2) Aparecerá uma relaçào de análise que poderá ser visualizada e aceita.<br>
        3) Caso deseje realizar outra análise, clique no botão "Nova Análise".<br>

        </p>


</div>
