<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/disponibilidade-servico-analise.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite cadastrar uma analise de disponibilidade de serviço de um objeto de contrato.<br><br>
		1. Objeto (campo obrigatório): selecione o objeto de contrato.<br>
		2. Início da Análise (campo obrigatório): selecione a data de início do período da análise.<br>
		3. Fim da Análise (campo obrigatório): selecione a data de fim do período da análise.<br>
		4. Análise (campo obrigatório): registre a análise.<br>
		5. Indice obtido: registre o ídice obtido conforme o especificado no contrato.<br>
		6. Parecer (campo obrigatório): registre o parecer reerente à análise.<br>
		Para cadastrar uma analise, preencha os campos e clique no botão "Salvar".<br>
	</p>
</div>

