<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/documentacao-contrato.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela Documentação de Contrato permite anexar documentos eletrônicos ao contrato.<br>
        1) Documentação (campo obrigatório): selecione qual documentação está sendo anexada.<br>
        2) Arquivo: selecione o arquivo.<br>
        Para anexar o arquivo tecle o botão "Anexar Arquivo".<br>
        </p>
</div>
