<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/profissional/documentacao-profissional.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Anexar Ducumentação de Profissional permite que anexe os documentos em meio magnéticos do profissional.
        1) Profissional (campo obrigatório): selecione o profissional.<br>
        2) Documentação (campo obrigatório): selecione a documentação.<br<
        3) Arquivo (campo obrigatório): selecione o arquivo para arquivar.<br>
        Para anexar o arquivo preencha os dados e clique no botão "Anexar Arquivo".<br>
        </p>
</div>
