<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/documentacao-projeto-controle.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        Esta tela permite arquivar documentos em meio magnéticos relativo a um determinado projeto de um contrato.<br><br>
		1. Contrato (campo obrigatório) : selecione o contrato.<br>
		2. Projeto (campo obrigatório): selecione o projeto.<br>
		3. Documentação (campo obrigatório): tipo de documento de controle. Esse tipo deve estar préviamente cadastrado pelo administrador.<br>
		4. Arquivo (campo obrigatório): selecione o arquivo que deseja enviar clicando o botão Enviar Arquivo.<br>
		Para enviar o arquivo tecle no botão "Anexar Arquivo".<br>
		Para abrir o conteudo de um arquivo localize o mesmo na tabela e clique em "Abrir".<br>
        </p>
</div>
