<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto-continuo/documentacao-projeto-continuo.png" alt="Tela Ajuda" />
	<p style="text-align: left;">
        A tela Documentação de Projeto Continuo permite anexar documentos eletrônicos ao projeto continuo.<br>
        1) Documentação (campo obrigatório): selecione qual documentação está sendo anexada.<br>
        2) Arquivo: selecione o arquivo.<br>
        Para anexar o arquivo tecle o botão "Anexar Arquivo".<br>
        </p>
</div>
