<div class="divConteudoAjuda">
	<div align="center">
		<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/elaboracao-proposta.png" alt="Tela Ajuda" />
	</div>
	<p>
		A tela de Elaboração de Proposta possui um resumo da solicitação de serviço
		que originou a proposta, um campo de possicionamento atual do projeto, que
		deve ser preenchido mensalmente pelo gerente do projeto colocando um posicionamento
		gerencial sobre o andamento do projeto, e possui abas deslizantes para
		fazer a Descrição, Alocar profissional, Realizar a aplicação da métrica,
		Gerenciar Módulos, Criar Parcelas, Acrescentar Produtos a parcela, e arquivar
		Arquivos refententes ao projeto selecionado.
	</p>
	<p>
		Todas as informações prestadas são obrigatórias para que o fechamento
		da proposta possa ser efetuado exeto as informações referente aos Arquivos
		da Proposta.
	</p>
	<p>
		Nas aba deslizante em que as informações são obrigatórias existe um botão
		no canto inferior direito para a confirmação dos dados informados. Este
		botão deve ser acionado ao término dos registros das informações para confirmação
		das mesmas, caso contrário não é possível fechar a proposta.
	</p>
</div>
