<div class="divConteudoAjuda" >
	<img src="<?php echo $this->baseUrl();?>/public/img/ajuda/solicitacao-tipo-demanda/encaminhar-solicitacao-tipo-demanda.png" alt="Tela Ajuda" />

	<p>
		A tela de encaminhamento de solicitação permite a designação de profissional
		para a execução da solicitação. Para o encaminhamento é necessário informar
		os campos obrigatórios descritos a seguir:
	</p>
	<ul>
		<li>Nível de Serviço : nível do servição a ser executado</li>
		<li>Profissional a executar : profissional a ser designado para execução da solicitação</li>
		<li>Prioridade : prioridade da execução da solicitação</li>
	</ul>
	<p>
		Após a designação do profissíonal é necessário a confirmação da designação
		para efetivar a operação.
	</p>

</div>
