<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/etapa.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite cadastrar uma empresa para contratação de serviços de Tecnologia da Informação.<br><br>
		1. Empresa (campo obrigatório) : empresa contratada.<br>
		2. CNPJ (campo obrigatório): número do CNPJ da empresa contratada.<br>
		3. Endereço : endereço da empresa para correspondência.<br>
		4. E-mail  : e-mail da empresa para contato.<br>
		5. Telefone : telefone de contato da empresa.<br>
		6. Fax : número do fax para contato.<br><br>
		Para cadastrar uma empresa, preencha os campos e clique no botão "Salvar".<br>
		Para alterar uma empresa, clique na linha da tabela com o nome da empresa, preencha os campos e clique no botão "Salvar".<br>
		Para excluir uma empresa, clique na imagem de lixeira ao lado do nome da empresa.<br>
	</p>
</div>

