<div class="divConteudoAjuda">
	<div align="center">
        <img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/execucao-proposta.png" alt="Tela Ajuda" />
    </div>
    <p style="text-align: center; ">
        A tela de Execução da Proposta possui um Resumo das informações da proposta
        e possui quatro faixas deslisantes para fazer o Histórico de Atividades,
        construir os Caso de Uso, definir o Dicionário de Dados e cadastrar os dados
        técnicos. Importante salientar que no Dicionário de Dados as informações básicas
        são obtidas diretamente do banco de dados e para isso é necessário  que se cadastre
        as informações de acesso ao Banco de Dados antes de realizar as descrições das
        tabelas e dos campos.
    </p>
</div>
