<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/executadas.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
         A tela Solicitações de Serviço Executada lista as solicitações de um mês.<br>
         Para visualizar a solicitaçào clique no número da solicitação.<br>
         Para Reencaminhar uma solicitação clique o botão "Reencaminhar".<br>
         Para indicar a conclusão da solicitação clique no botão "Concluir".<br>
        </p>
</div>
