<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/fechamento-extrato-mensal.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">

          Essa tela tem como finalidade permitir que o controle ou fiscalização realize o fechamento do extrato mensal do contrato.<br><br>
          Para realizar o fechamento clique no botão "Fechar Extrato".<br>
          Para visualizar um extrato fechado, localize o mês desejado e clique no botão "Ver Extrato".<br><br>

          OBS:<br> a) Antes de realizar o fechamento do extrato, verifique se todas as parcelas do mês foram concluídas e/ou encerradas.<br>
                   b) Para facilitar a conferência verifique se no relatório de previsão mensal o valor total corresponde com o valor do extrato mensal.

         </p>
</div>
