<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/acompanhar-proposta/fiscalizacao-proposta.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
           Essa tela tem por finalidade mostrar as propostas que estão sendo
           realizadas no mês estabelecido, indicando a existência ou falta dos principais artefatos. <br><br>
           É possível, também, verificar as propostas e parcelas do mês. 
        </p>
</div>
