<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/funcionalidade.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite o cadastro das funcionalidades.<br><br>
	</p>
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/funcionalidade-menu.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite o cadastro dos menus para a funcionalidade.<br><br>
	</p>
</div>
