<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/gerenciamento-teste-regra-negocio-analise.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
         A tela Teste - Relato do Teste lista os itens de testes pré-cadastrados e permite registrar os relatos de teste.<br>
         Para anexar imagem sobre o relato clique no botão "Anexar Imagem".<br>
         Para encaminhar a solução do problema clique o botão "Solucionar".<br>

        </p>
</div>
