<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/gerenciar-projetos-consulta-solicitacao.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
          A tela de Consulta de Solicitaçòes de Serviço permite selecionar as solicitações encaminhadas.<br>
          Para realizar a consulta preencha o(s) dado(s) desejado(s) e clique o botão "Consulta".<br>
        </p>
</div>
