<div class="divConteudoAjuda">
	<div align="center">
		<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/gerenciar-projetos.png" alt="Tela Ajuda" />
	</div>
	<p>
		O painel Projetos permite ao usuário acompanhar as solicitações
		de Serviço recebidas, abrir propostas, elaborar propostas, executar propostas
		e cadastrar pré-projetos. Importante salientar da necessidade de tomar
		conhecimento de uma solicitação de serviço no prazo estabelecido pelo contrato.
		Caso isso não ocorra é necessário justificar o ocorrido.
	</p>

	<div align="center">
		<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/gerenciar-projetos-consulta-solicitacao.png" alt="Tela Ajuda" />
	</div>
	<p>
		A consulta possibilita a localização de uma determinada solicitação de serviço
		de acordo com os parâmetros da busca.
	</p>
</div>
