<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/gerenciar-projetos-elaboracao.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela de elaboração de Proposta lista as propostas abertas no mês e mostra os artefatos que estão feitos.<br>
        Para elaborar uma proposta de um projeto clique na proposta desejada.<br>
        </p>
</div>
