<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/gerenciamento-teste-caso-uso-homologacao.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Teste - Homologação lista os itens de teste já solucionados e permite que o gerente homologue a solução.<br>
        Para homologar registre no espaço Homologação e clique no botão "Homologado".<br>
        Para não homologar registre no espaço Homologação e clique o botão "Não Homologado". Nesse caso o processo de teste retornará para ser solucionado.<br>

        </p>
</div>
