<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/gerenciamento-risco.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela de Risco - Proposta em Andamento lista os projetos que tem proposta em andamento indicando, graficamente o risco do projeto.<br>
        Os riscos são divididos em quatgro tipos de impacto: Projeto, Técnico, Custo e Cronograma.<br><br>
        OBS: as cores possíveis são:
             Verde - sem risco<br>
             Amarelo - Risco médio<br>
             Vermelho - Risco alto<br>
             Branco - Não definido<br>

        </p>
</div>
