<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/gerenciamento-teste-regra-negocio.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tele Teste-Regra de Negócio listas as regras de negócio cadastradas para o projeto.<br>
        São registrados os relatos, suas soluções e realizado a homologação.<br>
        Para realizar os registros clique no icone corespondente.<br>
         </p>
</div>
