<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/gerenciar-projetos-pre-projeto.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Pré-projeto lista os pré-projetos novos ou evolutivos.<br>
        Para cadastrar um pré-projeto novo clique no botão "Novo Pré-projeto".<br>
        Para cadastrar um pré-projeto evolutivo clique no botão "Novo Pré-projeto Evolutivo".<br>

        </p>
</div>
