<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/gerenciamento-teste.png" alt="Tela Ajuda" />
	<p style="text-align: left;">
         A tela de Teste - Projetos em Execução lista os projetos em execução.<br>
         1) Contrato: selecione o contrato.<br><br>
         Os testes devem seguir os requisitos, as regras de negócio e os casos de uso.<br>
         Ao clicar no ícone referente a um projeto é chamado a tela de teste para cada uma das situações.
        </p>
</div>
