<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/gerenciamento-projeto.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Gerenciar Projetos mostra todas as opções para gerenciar o projeto comc,
        gerenciar Risco, gerenciar testes, registrar Pedidos de mudança, realizar analises de mudança,
        gerenciar medições, gerar baselines, analisar execução de projeto, realizar planejamento,
        gerenciar matriz de rastreabilidade e cronogramar auditoria de qualidade.
        </p>
</div>
