<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/gerencia-qualidade.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
           A tela Cronograma de Auditoria de Qualidade permite estabelecer o cronograma para realizaçào da auditoria de qualidade, específica de CMMI ou MPS-BR.<br>
           1) Projeto (campo obrigatório): selecione o projeto.<br>
           2) Proposta (campo obrigatório): selecione a proposta (plano de projeto).<br>
           3) Fase (campo obrigatório): escreva a fase da Auditoria de Qualidade. <br>
           4) Data (campo obrigatório): selecione a data.<br>
           5) Quem Faz (campo obrigatório): selecione quem vai fazer.<br><br>
           Para salvar preencha os campos e clique no botão "Salvar".<br>
        </p>
</div>
