<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/gerenciamento-mudanca-proposta.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
         A tela Analise de Mudança - Proposta lista os projetos em execução que foram solicitados mudanças nas propostas.<br>
        Para realizar a análise clique o botão "Analisar Pedido" referente ao projeto desejado.<br>
        </p>
</div>
