<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/gerenciar-projetos-execucao-proposta.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela de Execução de Proposta lista as propostas como parcelas autorizadas no mês e mostra os artefatos que estão feitos.<br>
        Para executar uma parcela da proposta de um projeto clique na proposta desejada.<br>
        Quando os produtos da parcelas estiverem concluídos clique no botão "Fechar Parcela".<br>
        </p>
</div>
