<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/gerenciamento-teste-caso-uso-solucao.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela Teste - Solução lista os itens de teste e permite que o técnico registre a solução do problema relatado.<br>
        Para registrar escreva na espaço Solução do item e clique o botão "Solucionado".<br>
        </p>
</div>
