<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/grupo-fator-item.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela Item Grupo Fator permite cadastrar os  itens de grupos fatores referentes ao questionário de qualidade.<br>
         1) Grupo Fator (campo obrigatório): selecione um grupo fator.<br>
         2) Item (campo obrigatório): escreva o item <br>
         3) No. de Ordem (campo obrigatório): ordem de sequencia do item de grupo fator para aparecer na tela.<br><br>
         Para gravar um item gupo fator deve-se preencher os dados e clicar no botão "Salvar".<br>
         Para atualizar um item grupo fator deve-se clicar sobre ele na tabela, preencher os dados e clicar no botão "Salvar".<br>
         Para exluir um item grupo fator deve-se clicar na lixeira ao lado do grupo fator na tabela.<br>
        </p>
</div>
