<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/grupo-fator.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
         A tela Grupo Fator permite cadastrar os  grupos fatores referentes ao questionário de qualidade.<br>
         1) Grupo Fator (campo obrigatório): grupo fator.<br>
         2) Peso (campo obrigatório): peso do frupo fator.<br>
         3) No. de Ordem (campo obrigatório): ordem de sequencia do grupo fator para aparecer na tela.<br><br>
         Para gravar um gupo fator deve-se preencher os dados e clicar no botão "Salvar".<br>
         Para atualizar um grupo fator deve-se clicar sobre ele na tabela, preencher os dados e clicar no botão "Salvar".<br>
         Para exluir um grupo fator deve-se clicar na lixeira ao lado do grupo fator na tabela.<br>
        </p>
</div>
