<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto-continuo/historico-projeto-continuado.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Histórico de Projeto Continuado permite cadastrar as atividades realizadas para o projeto continuado.<br>
        1) Objeto: selecione o objeto de contrato.<br>
        2) Projeto Continuado: selecione o projeto.<br>
        3) Módulo Continuado: selecione o módulo.<br>
        4) Etapa: selecione a etapa.<br>
        5) Atividade: selecione a atividade.<br>
        6) Data Inicial: informe a data inicial da atividade.<br>
        7) Data Final: informe a data final da atividade.<br>
        8) Histórico: registre o histórico da atividade.<br.
        Para salvar um histórico clique no botão "Salvar".<br>
        Para alterar um histórico clique-o na tabela, preencha os dados e clique no botão "Salvar".<br>
        Para excluir um histórico clique na lixeira ao lado do histórico desejado na tabela.<br>
        </p>
</div>
