<div class="divConteudoAjuda" >
    <img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/registro-atividade/historico.png" alt="Tela Ajuda" />
    <p style="text-align: center; ">
        O registro de histórico documenta a criação e alteração de funcionalidades desenvolvidas pelo técnico envolvido no projeto.</p>
    <ul>
        <li>Projeto (Campo Obrigatório): Projeto referente às atividades realizadas.</li>
        <li>Proposta (Campo Obrigatório): Proposta referente às atividades realizadas.</li>
        <li>Modulo (Campo Obrigatório): Modulo de execução do projeto.</li>
        <li>Etapa (Campo Obrigatório): Etapa desenvolvido no projeto</li>
        <li>Atividade (Campo Obrigatório): Atividade de execução da etapa do projeto</li>
        <li>Data Inicial (Campo Obrigatório):Data de inicialização da atividade executada</li>
        <li>Data Final (Campo Obrigatório):Data de finalização da atividade executada.</li>
        <li>Histórico (Campo Obrigatório):Registro da criação ou alteração de uma funcionalidade desenvolvida.</li>
    </ul>
</div>
