<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/homologacao-parcela.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        Essa tela é cadastrado a Homologação da Parcela.<br>
        1, Homologação (campo obrigatório): selecione Sim para homologar a parcela ou Não caso contrário.<br>
        2. Observações: escreva as observações, se desejado, para a homologação.<br><br>
        Tecle "Salvar" para gravar a homologação.
        </p>
</div>
