<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/homologacao-proposta.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        Essa tela é cadastrado Homologação da Proposta.<br>
        1, Homologação (campo obrigatório): selecione Sim para homologar a  proposta (plano de projeto) ou Não caso contrário.<br>
        2. Observações: escreva as observações desejadas.<br><br>
        Tecle "Salvar" para gravar a homologação.


        </p>
</div>
