<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <meta http-equiv="cache-control" content="no-cache" />
        <title><?php echo $this->escape($this->titulo); ?></title>
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/css/dialog.css" type="text/css" media="screen, projection" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/css/oasisImport.css" type="text/css" media="screen, projection" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/css/print.css" type="text/css" media="print" />
        <!--[if IE]><link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/css/ie.css" type="text/css" media="screen, projection" /><![endif]-->

        <!-- CSS da TreeView -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/js/lib/jquery/treeview/jquery.treeview.css" type="text/css" media="screen, projection" />

        <script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/lib/jquery/jquery-1.3.1.min.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/lib/jquery/ui/jquery-ui-1.7.2.custom.min.js"></script>

		<!-- Scripts TreeView -->
        <script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/lib/jquery/jquery.cookie.js"></script>
        <script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/lib/jquery/treeview/jquery.treeview.js"></script>

        <script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/oasis.js"></script>
		<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/oasis.msg.js"></script>

        <script language="javascript" type="text/javascript">
            $(document).ready(function(){
                $('.buttonBarLeft').css('display','');
            });
			
			var welcome          = <?php if( isset($_SESSION['oasis_logged']) ) {echo "true";}else {echo "false";} ?>;
            var systemName		 = '<?php echo $this->baseUrl();?>';
			
            loadShortcutIcon( systemName + '/public/img/favicon.gif' );
        </script>
    </head>
    <body>
        <div id="cabeca" class="container">
            <img id="logo" alt="Oasis" src="<?php echo $this->baseUrl();?>/public/img/logo4.png"/>
			<div class="float-r span-10 bold">
				<p style="font-size: 45px; margin-top: 25px;">Ajuda</p>
			</div>
        </div>
        <div class="corpo">
            <div id="content" class="container containerAjuda">

				<?php if( $this->pagina === 'index' ): ?>
					<div class="span-25 border center" style="padding: 10px; height: 580px; overflow: auto;">
						<?php echo $this->render('ajuda/ajuda-tela-login.phtml') ?>
					</div>
					<div class="span-21" style="height: 23px;"></div>
				<?php else: ?>
					<div id="treeEstrutura" class="float-l span-5 border" style="overflow-y:auto; height: 580px; padding: 5px;">
						<img src="<?php echo $this->baseUrl()?>/public/img/treeview.gif" alt="Ajuda" />
						<?php $this->treeviewAjuda( "treeview_ajuda", $this->dataMenu ); ?>
					</div>

					<div id="img_da_ajuda" class="float-l span-19 border" style="margin-left: 10px; overflow: auto; height: 580px; padding: 5px;"></div>

					<div class="buttonBarLeft" style="display: none;">
						<div class="buttonBarRight">
							<div class="buttonBarMiddle"></div>
						</div>
					</div>
				<?php endif; ?>
            </div>
        </div>
        <div id="rodapeContainer">
            <div id="rodape" class="container">
                <address>
                    <?php echo K_ADDRES_ORGAO; ?>
                </address>
            </div>
        </div>
		<script type="text/javascript">
            <!--
            $(document).ajaxStart(function(){
                ajaxLoading('Aguarde...');
            });
            $(document).ajaxStop(function(){
                ajaxLoaded();
            });
            //-->
        </script>
    </body>
</html>
<script language="javascript" type="text/javascript">
	loadScript("<?php echo $this->baseUrl();?>/public/js/modules/default/ajuda/index.js");
</script>
