<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/inicio/inicio.png" alt="Tela de Início" />
<p style="text-align: center; ">
	Ao entrar no Sistema OASIS aparecerá a tela de iníco que permitirá que o usuário navegar
	no sistema. Existem dois menus importantes, o menu superior, contendo opções de uso gerais
	para todos os usários do sistema, e o menu do sistema, contendo as funcionalidades do sistema
	que aparecem de forma dinâmica conforme o perfil designado para o usuário. Possui a informação
	de quem está acessando o sistema e a data de último acesso realizado. Existe uma opção de
	acessibilidade - Tamanho da fonte - que permite ao usuário aumentar ou diminuir o tamanho da
	fonte do sistema. Para isso basta clicar na letra A do tamanho desejado. Essas funcionalidades
	estaram disponíveis em todas as telas do sistema.
	<br>
	No corpo da página de início está disponível caixas de informações rápidas, estabelecidas para
	cada perfil de profissional. Estas caixas de informações podem ser possicionadas conforme o
	desejo do usuário, para isso basta clicar na caixa e arrastar para a posição desejada. Clicando
	no ícone ao lado do título da caixa aparecerá uma tela com as caixas de informações disponível
	para o usuário. Marcando as caixas desejadas e salvando, essas ficaram disponíveis na tela inicial.
</p>
</div>
