<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/item-teste.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Item de Teste permite cadastrar o itens para um tipo de teste.<br>
        1) Tipo de Teste (campo obrigatório): selecione um tipo de teste.<br>
        2) Ordem do item de teste (campo obrigatório): numero da ordem que aparecerá na tela.<br>
        3) Item de Teste (campo obrigatório): item de teste.<br>
        4) Marcar se o campo é obrigatório e/ou se o item tornou-se inativo.<br>
        Para salvar um item de teste preencha os dados e clique no botão "Salvar".<br>
        </p>
</div>
