<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/item-parecer-tecnico.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
  A tela Ítem Parecer Técnico permite cadastrar ítens a serem analisados no parecer técnico.<br>
  1) Item de Parecer Técnico (campo obrigatório): escreva o item.<br>
  2) Marque se o item será para parecer técnico de proposta ou de parcela ou de ambos.<br><br>
  Para salvar um item de parecer técnico preencha os dados e clique no botão "Salvar".<br>
  Para atualizar um item de parecer técnico clique sobre ele na tabela, preencha os dados e clique no botão "Salvar".<br>
</p>
</div>
