<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/item-controle-baseline.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Item de Controle de Baseline permite cadastrar os artefatos que serão base para a Baseline.<br>
        1) Item de Controle de Baseline (campo obrigatório): escreva o item.<br>
        Para salvar um item de controle de baseline clique no botão "Salvar".<br>
        Para atualizar um item de controle de baseline clique sobre o mesmo na tabela, preencha os dados eclique no botão "Salvar".<br>
        Para exluir um item de controle de baseline clique na lixeira ao lado co item na tabela.<br>
        </p>
</div>
