<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/item-risco.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        Esta tela permite cadastrar os Itens de Risco.<br><br>
		1. Objeto Contratato (campo obrigatório) : objeto contratado.<br>
		2. Etapa (campo obrigatório): etapa ao qual o Item de Risco será relacionado.<br>
		3. Atividade (campo obrigatório): atividade ao qual o Item de Risco será relacionado.<br>
		4. Item de Risco (campo obrigatório): item de risco resumido.<br>
		5. Descrição do Item: descrição do item de risco. Deve-se explicar a finalidade do item.<br>
		Para cadastrar um item de risco, preencha os campos e clique no botão "Salvar".<br>
		Para alterar um item de risco, clique na linha da tabela com o nome do item de risco, preencha os campos e clique no botão "Salvar".<br>
		Para excluir um item de risco, clique na imagem de lixeira ao lado do nome do um item de risco.<br>
        </p>
</div>
