<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/item-metrica.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite o cadastro de itens de métrica.<br><br>
		1. Métrica (campo obrigatório): métrica de cálculo de custo de projeto.<br>
		2. Nome (campo obrigatório) : nome do item de métrica.<br>
		3. Fórmula (campo obrigatório) : fórmula de cálculo do item de métrica.<br>
		4. Variável (campo obrigatório) : váriável que receberá o resultado do cálculo da fórmula do item de métrica.<br>
		5. Nr. Ordem : ordem de cálculo do item de métrica.<br>
	</p>
</div>
