<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/justificativa-solicitacao.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela justificativa de solicitação de Serviço permite cadastrar a justificativa de não leitura no tempo estipulado do contrato.<br>
        Para salvar a justificativa preencha os dados e clique no botão "Salvar".<br>
        </p>
</div>
