<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/executar-demanda/justificativa-demanda.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela de Justificativa de Demanda permite que se registre a justificativa de não leitura no tempo determinado.<br>
        Para gravar a justificativa clique no botão "Salvar".<br><br>
        OBS: Caso seja optado para o objeto de contrato de não ter tempo limite para leitura da demanda essa tela não existirá.<br>
        </p>
</div>
