<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/log.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite visualizar os dados registrados no log.<br><br>
		1. Profissional : profissional que realizou a operação gravada no log.<br>
		2. Data Inicial (campo obrigatório) : data inicial do período de busca dos dados no log.<br>
		3. Data Final (campo obrigatório) : data final do período de busca dos dados no log.<br>
		4. Tabela : tabela do sistema na qual foi realizada a operação gravada no log.<br>
		5. IP : IP da máquina na qual foi realizada a operação gravada no log.<br><br>
		Para visualizar os dados registrados no log, informe os parâmetros para pesquisa
		e clique no botão "Pesquisar".
	</p>
</div>

