<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/matriz-rastreabilidade-caso-de-uso.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela de Matriz de Ratreabilidade - Caso de Uso permite verificar quais requisitos influenciam os casos de uso de um projeto.<br>
        1) Contrato (campo obrigatório): selecione o contrato.<br>
        2) Projeto (campo obrigatório): selecione o projeto.<br>
        3) Análise (campo obrigatório): escrever análise.<br><br>
        Para salvar uma análise clique no botão "Salvar".<br>
        Para fechar uma análise clique no botão "Fechar Análise"<br>


        </p>
</div>
