<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/matriz-rastreabilidade-requisito.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
         A tela de Matriz de Ratreabilidade - Requisito permite verificar quais requisitos influenciam os outros requisitos de um projeto.<br>
        1) Contrato (campo obrigatório): selecione o contrato.<br>
        2) Projeto (campo obrigatório): selecione o projeto.<br>
        3) Análise (campo obrigatório): escrever análise.<br><br>
        Para salvar uma análise clique o botão "Salvar".
        Para fechar uma análise clique o botão "Fechar Análise".
        </p>
</div>
