<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/medicao-medicao.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">Mostra a lista das midições cadastradas </p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/medicao-analise.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">Mostra a lista das analises de uma medição. </p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/medicao-decisao.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">Mostra a listas das decisões estabelecidas para uma medição. </p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/medicao-medicao-medida.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">Associa as medições as medidas existentes. </p>
</div>
