<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/logo4.png" alt="Tela Ajuda Indisponível" />
	<p style="text-align: center; ">
        Na tela de Medição - Análise lista as análises realizadas nas mediçoes existentes.<br>
        Após a análise clique o botão "Decisão" para registrar as decisões a serem tomadas sobre aquela análise.<br><br>
        Para uma nova análise clique o botão "Nova Análise de Medição".<br>

        </p>
</div>
