<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/medida.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Medida permite cadastrar uma medida para uso nas análise de medição.<br>
        1) Medida (campo obrigatório): nome da media.<br>
        2) Objetivo da medida (campo obrigatório): descrever o objetivo da medida,<br>
        Para salvar uma medida preencha os dados e clique no botão "Salvar".<br>
        Para atualizar uma medida clique sobre ela na tabela, preencha os dados e clique no botão "Salvar".<br>

        </p>
</div>
