<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/medicao-medica.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Medição - Medição lista as medições e o nível que se enquadra a medição (operacional, técnico ou estratégico).<br>
        Para entrar em alguma medição clique sobre a mesma.<br>
        Para criar uma nova medição clique no botão "Nova Medição".<br>
        </p>
</div>
