<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/logo4.png" alt="Tela Ajuda Indisponível" />
	<p style="text-align: center;">
        A tela Medição - Decisão lista as mediçòes realizadas e permite acompanhar a execução da decisão.<br>
        Para registrar execução clique no botão "Execução de Decisão".<br>
        Se desejar ver a execução clique no botão "Visualizar a Execução".<br>
        </p>
</div>
