<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/medicao-medicao-medida.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Medição - Mediçào e Medida permite associar uma medição às medidas pré cadastradas.<br>
        1) Medição: selecione a medição.<br>
        2) Medida: selecione as medidas e clique no botão ">>" para associar.<br>
        Após associar deve-se estabelecer a prioridade.<br>
        Para desassociar alguma media selecione em Medida Associada e clique o botão "<<".<br>
        </p>
</div>
