<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/menu-contrato.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
        O Painel de Contrato permite que o administrador possa
		definir as empresas,
		definir os contratos,
		definir a associação da métrica a um contrato,
		definir a associação dos projetos existentes a um contrato,
		definir perfis profissionais e papeis profissionais,
		definir a associação dos perfis do sistema ao objeto do contrato,
                definir as etapas e atividades e
		definir os itens e questões de análise de risco.
</p>
</div>
