<div class="divConteudoAjuda">
	<div align="center">
		<img  src="<?php echo $this->baseUrl();?>/public/img/logo4.png" alt="Tela Ajuda" />
	</div>
	<p>
		A Registro Atividade permite cadastrar as atividades desenvolvidas de um projeto.
	</p>
	<p>
		É importante que o profissional esteja designado para o projeto selecionado
		e que a proposta tenha parcela para o mês de cadastro.
	</p>
</div>
