<div style="text-align: center;">
	<p style="text-align: left">O OASIS permite que se cadastre métricas desde que exista a fórmula para que seje definida.<br><br>
        Para estabelecer a métrica no OASIS utilize a funcionalidade Definir Métrica, no item de menu Administração:<br>
        1) Definir a métrica. Nessa definição estabelece o nome, sigla, descrição e fórmula;<br>
        2) Estabelecer os itens de métrica. Uma métrica pode ter mais de um item de métrica. Esse item de métrica deve ter o nome e a fórmula desse item;<br>
        3) Estabelecer os subitens de métrica. Os subitens de métrica são as variáveis que serão utilizadas na fórmula do item de mátricas; <br>
        4) Os subitens podem ser internos ou externos. Os internos devem ser estabelecidos condições. Os externos serão variáveis que serão colocadas na funcionalidade de métrica para entrada de dados.<br>
    </p>
</div>