<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/modulo-criacao-associacao.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela permite cadastrar um módulo para o projeto e associar os módulos para a proposta. </p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/modulo-associacao.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela mostra os módulos existentes e os módulos que estão associados à proposta.</p>
</div>
