<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto-continuo/modulo-continuado.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Módulo Continuado  permite cadastrar um módulo de um projeto continuado.<br>
        1) Objeto: selecione o objeto.<br>
        2) Projeto Continuado: selecione o projeto continuado.<br>
        3) Módulo Continuado: escreva o módulo continuado.<br>
        Para salvar um módulo continuado preencha os dados e clique no botão "Salvar".<br>
        Para alterar um módulo continuado clique-o na tabela, preencha os dados e clique no botão "Salvar".<br>
        Para excluir um módulo continuado clique na lixeira ao lado do módulo na tabela.<br>
        </p>
</div>
