<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/modulo-criacao-associacao.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela Gerenciar Módulos permite cadastrar e associar os módulos do sistema à proposta que está sendo elaborada.<br>
        Para criar um novo módulo preencha os dados clique o botão "Adicionar".<br>
        Para associar os módulos a proposta selecione os em módulos disponíveis e clique o botão ">>".<br>
        </p>
</div>
