<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/nivel-servico.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
                Esta tela permite cadastrar os Níveis de Serviço.<br><br>
		1. Objeto Contratato (campo obrigatório) : objeto contratado.<br>
		2. Nivel de Serviço (campo obrigatório): nivel de serviço a ser cadastrado.<br>
		3. Prazo de Execução (campo obrigatório): prazo limite de execução em horas.<br>
		Para cadastrar um nível de serviço, preencha os campos e clique no botão "Salvar".<br>
		Para alterar um nível de serviço, clique na linha da tabela com o nome do nível de serviço, preencha os campos e clique no botão "Salvar".<br>
		Para excluir um nível de serviço, clique na imagem de lixeira ao lado do nome do nível de serviço.<br>
 </p>
</div>
