<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/objeto-contrato.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
                Esta tela permite cadastrar o Objeto do Contrato.<br><br>
		1. Contrato (campo obrigatório) : contrato contratado.<br>
		1. Objeto Contratato (campo obrigatório) : objeto contratado.<br>
		2. Tipo:  o tipo do objeto de contrato pode ser:<br>
                          a) projeto (quando se tratar de de contratação por resultados);<br>
                          b) demanda (quando se tratar de de contratação por demanda e disponibilidade de serviço);<br>
                          a) serviço (quando se tratar de de contratação por disponibilidade de serviço);<br>
		Para cadastrar um objeto do contrato, preencha os campos e clique no botão "Salvar".<br>
		Para alterar um objeto do contrato, selecione o contrato, preencha os campos e clique no botão "Salvar".<br>
		Para excluir um objeto do contrato, selecione o contrato, e clique no botão "Excluir".<br>
 </p>
