<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/profissional/objeto-perfil-profissional.png" alt="Tela Ajdua" />
<p style="text-align: center; "> 
    A tela de Associar Permissão ao Profissional permite que se cadastre as permissões que o profissional
	irá utilizar no OASIS. Selecionando o objeo do contrato, o perfil que o profissional terá e o nome do
	profissional, aparecerá uma lista dos menus disponíveis e os menus que estiverem marcados o profissional
	terá acesso. Importante salientar que somente marcar o menu, automaticamente será gravado no banco a permissão.
</p>
</div>
