<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ocorrencia-administrativa-lista.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
         Essa tela aparece a lista de Ocorrências Administrativas registradas.<br>
         1) Para registrar nova ocorrência clique no botão "Nova Ocorrência".<br>
         2) Para apagar um registro de ocorrência clique na lixeira referente a ocorrência que se deseje apagar.<br>
         </p>
</div>
