<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/ocorrencia-administrativa-lista.png" alt="Tela Ajuda" />
<p style="text-align: center; "> A tela Ocorrência Administrativa permite listar ocorrências administrativas registradas.</p> 

<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/ocorrencia-administrativa-nova.png" alt="Tela Ajuda" />
<p style="text-align: center; ">Essa tela permite registrar a ocorrência administrativa.<br>
                                Os Eventos administrativos devem ser pré cadastrados.
</p>

<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/ocorrencia-administrativa-associa.png" alt="Tela Ajuda" />
<p style="text-align: center; ">Essa tela permite realizar a associação dos eventos administrativos existentes ao contrato. </p>
