<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ocorrencia-administrativa-nova.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        Essa tela permite registrar uma Ocorrência Administrativa.<br>
        1) Contrato (campo obrigatório): selecione o contrato.<br>
        2) Evento (campo obrigatório): selecione o evento. Esse evento é pré-cadastrado pelo administrador.<br>
        3) Data da Ocorrência (campo obrigatório): coloque a data da ocorrência.<br>
        4) Ocorrência: escreva a ocorrência.<br><br>
        Para salvar a ocorrência, preencha os campos e clique no botão "Salvar".<br>

        </p>
</div>
