<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ocorrencia-administrativa-associa.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        Essa tela permite associar os eventos a serem controlados por um contrato.<br>
        1) Contrato : selecione um contrato.<br>
        2) Eventos Administrativos: selecione os eventos administrativos e clique o botão ">>" para associar ao contrato.<br>
        3) Eventos Administrativos Associados ao Contrato: selecione os eventos administrativos e clique o botão "<<" para desassociar do contrato.<br>

        </p>
</div>
