<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/painel-demanda-executada.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
         A tela Demanda Executada lista as demanda executadas pelos profissionais para que o gerente possa concluí-las.<br>
         Para ver uma demanda localize-a na tabela e clique sobre ela.<br>
         Para concluir a demanda, clique no botão "Concluir" referente à demanda desejada.<br>
         Caso deseje reencaminhar a demanda para nova execução, clique no botão "Reencaminhar".<br>
        </p>
</div>
