<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/painel-demanda-andamento.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Demanda em Andamento relaciona as demandas em execução.<br>
        Para ver a demanda ache a demanda na tabela e clique emcima.<br>
        Para criar uma nova demanda clique no botão "Nova Demanda".<br>

        </p>
</div>
