<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/demanda/painel-demanda-andamento.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela lista as demandas em andamento e chamar o cadastramento de uma demanda.</p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/demanda/painel-demanda-executada.png" alt="Tela Ajuda" />
	<p style="text-align: center;">A tela lista as demandas executadas. </p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/demanda/painel-demanda-concluida.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela lista as demandas concluidas pelo gerente da área. </p>
</div>
