<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/painel-contrato.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite visualizar os contratos cadastrados.<br><br>
		1. Status : filtra a lista de contratos pelo status selecionado.<br>
		2. Empresa : filtra a lista de contratos pela empresa contratada.<br>
		3. Lista : lista de contratos.<br>
		4. Novo Contrato : botão que abre uma tela para cadastro de um contrato.<br><br>
		Para visualizar os dados de um contrato, clique na linha da tabela com o número do contrato.<br>
	</p>
</div>

