<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/papel-profissional.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
                Esta tela permite cadastrar os Papeis Profissionais.<br><br>
		1. Contrato (campo obrigatório) : contrato contratado.<br>
		2. Objeto Contratato (campo obrigatório) : objeto contratado.<br>
		2. Papel Profissional (campo obrigatório): papel profissional.<br>
		Para cadastrar um papel profissional, preencha os campos e clique no botão "Salvar".<br>
		Para alterar um papel profissional, clique na linha da tabela com o nome do papel profissional, preencha os campos e clique no botão "Salvar".<br>
		Para excluir um papel profissional, clique na imagem de lixeira ao lado do nome do papel profissional.<br>
 </p>
</div>
