<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/parecer-tecnico-proposta.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        Essa tela permite cadastrar o parecer Técnico.<br>
        1) [Opções cadastradas para analise] (campo obrigatório): selecione OK ou Não OK ou Não Aplica conforme analisado para o parecer.<br>
        2) Observações (campo obrigatório): escreva as observações referente ao parecer técnico da proposta.<br>
        3) Tipo de Avaliação (campo obrigatório): selecione :<br>
            a) Atendido - no caso de estar em conformidade <br>
            b) Não atendido - no caso de não ter atendido a conformidade. Nesse caso o fluxo retornará para a empresa para realizar a correção.
        Tecle "Salvar" para gravar o parecer técnico.


        </p>
</div>
