<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/parecer-tecnico-parcela.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        Essa tela permite cadastrar o parecer Técnico.<br>
        1) [Opções cadastradas para analise] (campo obrigatório): selecione OK ou Não OK ou Não Aplica conforme analisado para o parecer.<br>
        2) Observações (campo obrigatório): escreva as observações referente ao p arecer técnico da parcela.<br>
        3) Tipo de Avaliação (campo obrigatório): selecione :<br>
            a) Atendido - no caso de estar em conformidade <br>
            b) Não atendido - no caso de não ter atendido a conformidade. Nesse caso o fluxo retornará para a empresa para realizar a correção.
            c) Pendente - nesse caso o parecer fica suspenso até que retorne e Atenda ou Não Atenda a conformidade. <br><br>
        Tecle "Salvar" para gravar o parecer técnico.

        </p>
</div>
