<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/pedido-mudanca-proposta.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela Pedido de Mudança - Proposta lista as propostas e permite que realise um pedido de mudança para a proposta fechada.<br><br>
        1) Projeto: selecione o projeto.<br>
        Para realizar o pedido de mudança clique no botão "Pedir Mudança".<br>
        </p>
</div>
