<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/pedido-mudanca-caso-de-uso.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Pedido de Mudança - Caso de Uso lista os caso de usos e permite que realise um pedido de mudança para caso de uso fechado.<br><br>
        1) Projeto: selecione o projeto.<br>
        2) Módulo: selecione o módulo.<br><br>
        Para realizar o pedido de mudança clique no botão "Pedir Mudança".<br>

        </p>
</div>
