<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/pedido-mudanca-regra-de-negocio.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Pedido de Mudança - Regra de Negócio lista as regras de negócio e permite que realise um pedido de mudança para regra de negócio fechada.<br><br>
        1) Projeto: selecione o projeto.<br>
        Para realizar o pedido de mudança clique no botão "Pedir Mudança".<br>
        </p>
</div>
