<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/pedido/pedido-admin.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela Pedido estabelecer as opções para administrar um pedido de um usuário requisitante.<br><br>
        A administração dos pedidos solicitados através da página do OASIS - http://[servidor]/oasis/pedido.<br>

        </p>
</div>
