<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/pedido-mudanca-requisito.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela Pedido de Mudança - Requisito lista os requisitos e permite que realise um pedido de mudança para requisito fechado.<br><br>
        1) Projeto: selecione o projeto.<br>
        Para realizar o pedido de mudança clique no botão "Pedir Mudança".<br>
        </p>
</div>
