<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/penalizacao-registro.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela permite cadastrar uma ou mais ocorrencias de penalização. <br>'
                                   Pode-se registrar diariamente. </p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/penalizacao-ocorrencia-mensal.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">Essa tela lista todas as penalizações do mes registradas para os contratos. </p>
</div>
