<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/penalidade.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
 	Esta tela permite cadastrar as Penalidades estabelecidas no contrato.<br><br>
		1. Contrato (campo obrigatório) : selecione o contrato.<br>
		2. Número da Penalidade (campo obrigatório): número da penalidade (geralmente referencia do contrato).<br>
		3. Descrição Resumida (campo obrigatório): escreva uma frase resumida que identifique a penalidade.<br>
		4. Penalidade (campo obrigatório): escreva a penalidade conforme o contrato.<br>
		5. Penalidade(%) (campo obrigatório): porcentagem referente à penalidade.<br>
		6. Por Ocorrência: clique no quadrado no caso que a penalidade seja realizada por ocorrência.<br><br>
		Para cadastrar uma penalidade, preencha os campos e clique no botão "Salvar".<br>
		Para alterar uma penalidade, clique na linha da tabela com o nome da penalidade, preencha os campos e clique no botão "Salvar".<br>
		Para excluir uma penalidade, clique na imagem de lixeira ao lado do nome da penalidade.<br>

</p>
</div>
