<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/logo4.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
         Essa tela permite cadastrar as penalidades de um objeto de contrato.<br>
         1) Objeto: selecione o objeto de contrato.<br>
         2) Data: data da ocorrência.<br>
         3) Infração: esses campos são dinâmicos e são cadastrados quando o contrato é cadastrado.<br><br>
         Para salvar a penalização clique no botão "Salvar".<br>
         Para apagar um registro de penalização clique na lixeira ao lado da infração que se deseje apagar.<br>


        </p>
</div>
