<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/perfil-profissional.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        Esta tela permite cadastrar os Perfis Profissionais.<br>
		1. Objeto (campo obrigatório): objeto do contrato.<br>
		2. Perfil Profissional (campo obrigatório) : perfil profissional<br>
		3. Descrição(campo obrigatório): descrição do perfil profissional<br><br>
		Para cadastrar um perfil profissional, preencha os campos e clique no botão "Salvar".<br>
		Para alterar um perfil profissional, clique no nome do perfil profissional na tabela, preencha os campos e clique no botão "Salvar".<br>
		Para excluir um perfil profissional, clique no nome do perfil profissional na tabela e clique no botão "Excluir".<br>
         </p>
</div>
