<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/perfil-profissional-papel-profissional.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite associar papéis profissionais a um perfil profissional.<br><br>
		1. Objeto : objetos do contrato do tipo "Projeto".<br>
		2. Perfil Profissional : perfis profissionais do objeto do contrato selecionado.<br>
		3. Papéis Profissionais : lista de papéis profissionais não associados ao perfil profissional.<br>
		4. Papéis Profissionais Associados : lista de papéis profissionais associados ao perfil profissional.<br><br>
		Para associar um papel profissional ao perfil profissional, selecione um perfil profissional,
		selecione o(s) papel(éis) na lista "Papéis Profissionais" e clique no botão ">>".<br>
		Para desassociar um papel profissional do perfil profissional, selecione um perfil profissional,
		selecione o(s) papel(éis) na lista "Papéis Profissionais Associados" e clique no botão "<<".<br>
	</p>
</div>

