<div style="text-align: center;" >
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/perfil-menu.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite associar menus de funcionalidade a um perfil de acesso ao sistema, por tipo de menu.<br><br>
		1. Perfil (campo obrigatório): perfil de acesso ao sistema.<br>
		2. Tipo de Menu (campo obrigatório) : tipo de funcionalidade do menu. Tipos: Projeto ou Demanda<br>
		3. Treeview de Menus : árvore de menus disponíveis para associação ao perfil de acesso ao sistema.<br><br>
		Para associar um menu a um perfil de acesso ao sistema, selecione o perfil, selecione o tipo de menu 
		e clique no checkbox ao lado do menu que se deseja associar.
	</p>
</div>
