<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/perfil.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite cadastrar um perfil de acesso ao sistema.<br><br>
		1. Perfil (campo obrigatório): nome do perfil de acesso ao sistema.<br><br>
		Para cadastrar o perfil, preencha os campos e clique no botão "Salvar".<br>
		Para alterar o perfil, clique no nome do perfil na tabela de perfis, preencha os campos e clique no botão "Salvar".<br>
		Para excluir o perfil, clique na imagem de lixeira ao lado do nome do perfil.<br>
	</p>
</div>

