<div style="text-align: center;">
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/perfil-box-inicio.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite associar boxes de estatísticas a um perfil de acesso ao sistema, por objeto do contrato.<br><br>
		1. Perfil (campo obrigatório): perfil de acesso ao sistema.<br>
		2. Objeto (campo obrigatório) : objeto do contrato.<br>
		3. Box : lista de boxes de estatísticas não associados ao perfil e ao objeto do contrato.<br>
		4. Box Associado : lista de boxes de estatísticas associados ao perfil e ao objeto do contrato.<br>
	</p>
</div>
