<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/planejamento-planejamento.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela permite estabelecer o planejamento das etapas e atividades para um modulo. </p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/gerenciar-projeto/planejamento-grafico-gantt.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela permite chamar um gráfico de Gantt a partir das informações do planejamento.</p>
</div>
