<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/planejamento-planejamento.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Planejamento - Planejamento permite cadastrar o plenejamento de execução de um projeto.<br><br>
        1) Projeto: selecione um projeto.<br>
        2) Módulo: selecione um módulo.<br>
        3) Etapa: selecione uma etapa.<br><br>
        Serão listadas as atividades referentes a etapa selecionada. Estabeleça as informações pedidas para cada atividade.<br>


        </p>
</div>
