<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/planejamento-grafico-gantt.phtml.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela Planejamento - Gráfico de Gantt permite visualizar o gráfico de gantt dde um projeto.<br>
        1) Projeto (campo obrigatório): selecione um projeto.<br>
        2) Módulo (campo obrigatório): selecione um módulo.<br>
        3) Filtro: selecione o filtro desejado.<br>
        </p>
</div>
