<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/pre-demanda-painel/pre-demanda.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
         A tela Pré-demanda - Cadastro permite cadastrar uma pré-demanda.<br>
         1) Unidade Solicitante (campo obrigatório): selecione uma unidade.<br>
         2) Objeto executor (campo obrigatório): selecione qual o objeto de contrato receberá a pré-demanda.<br>
         3) Descrição (campo obrigatório): descreva, bem explicado, o que deve ser realizado.<br>
         Para salvar a pré-demanda prencha os dados e clique no botão "Salvar".<br>
         </p>
</div>
