<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/pre-demanda-painel/pre-demanda-andamento.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Pré-Demanda em Adamento lista as demandas não executadas e permite abrir uma nova pré-demanda.<br>
        Para criar uma nova pré-demanda clique no botão "Nova Pré-Demanda".<br>
        </p>
</div>
