<div class="divConteudoAjuda">
	<div align="center">
		<img src="<?php echo $this->baseUrl();?>/public/img/ajuda/projeto/produto-parcela.png" alt="Tela Ajuda" />
	</div>
<p style="text-align: center; ">
		A tela de Produtos possibilita a visualização dos produtos cadastrados nas
		diversas parcelas de um projeto. Esta visualização ocorre durante a fase de
		execução da proposta.
	</p>
</div>
