<div class="divConteudoAjuda">
	<div align="center">
		<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/associar-profissional-projeto.png" alt="Tela Ajuda" />
	</div>
	<p>
		A tela de Alocação de Profissionais possibilita informar quais os profissionais
		que irão participar do desenvolvimento do projeto.
	</p>
	<p>
		A alocação dos profissionais se dá durante a fase de elaboração da proposta.
	</p>
</div>
