<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/profissional/profissional-objeto-contrato.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
 A Tela Profissional Objeto Contrato permite designar profissionais para um objeto de contrato.<br>
 1) Objeto: selecione o objeto de contrato.<br>
 2) Perfil Profissional: selecione o perfil profissional.<br>
 3) Profissional: selecione os profissionais que ocuparam o perfil selecionado e clique o botão ">>".<br>
 Ao selecionar o profissional o mesmo aparecerá em uma tabela que deverá ser preenchido o papel profissional, se o usuário receberá e-mail (gerenciais) do sistema e se é o objeto padrão do profissional.<br>

</p>
</div>
