<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/profissional/profissional.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
 A Tela Profissional permite cadastrar profissional.<br>
 1) Empresa (campo origatório): selecione a empresa.<br>
 2) Relação Contratual (campo obrigatório): selecione a relação contratual.<br>
 3) Profissional (campo obrigatório): nome completo do profissional.<br>
 4) Nome Conhecido (campo obrigatório): nome resumido do profissional.<br>
 5) Data de Nascimento: data de nascimento do profissional.<br>
 6) E-mail login (campo obrigatório): email completo do profissional.<br>
 7) Outro e-mail: outro e-mail do profissional.<br>
 8) Telefone Residencial: telefone residencial do profissional.<br>
 9) Telefone celular: telefone celular do profissional.<br>
 10) Ramal: ramal do profissional.<br>
 11) Perfil (campo obrigatório): perfil que o profissional atuará no sistema.<br>
 12) Endereço: endereço do profissional.<br>
 13) Data de Início (campo obrigatório): data de início dos trabalhos no sistema.<br>
 14) Nova Senha: se marcado indica que será pedido nova senha na próxima entrada do sistema.<br>
 15) Data de Saída: data de saída do sistema.<br>
 16) Inativo: se marcado o profissional fica inativo no sistema.<br>
 17) Ver todos os Contratos?: se marcado indica que o profissional poderá ver outros contratos além do que ele é cadastrado.<br><br>
 Para salvar um profissional preencha os dados e clique no botão "Salvar".<br>
 Para alterar dados de um profissional preenchas os dados e clique o botão "Salvar".<br>
 Para excluir um profissional tecle no botão "Excluir".<br>

 </p>
</div>
