<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto-continuo/projeto-continuado.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela Projeto Continuado  permite cadastrar um projeto continuado.<br>
        1) Objeto: selecione o objeto.<br>
        2) Projeto Continuado: escreva o projeto continuado.<br>
        3) Objetivo: escreva o objetivo do projeto continuado.<br>
        4) Observação: escreva observação do projeto continuado.<br>
        5) Prioridade: selecione a prioridade do projeto continuado.<br>
        Para salvar um projeto continuado preencha os dados e clique no botão "Salvar".<br>
        Para alterar um projeto continuado clique-o na tabela, preencha os dados e clique no botão "Salvar".<br>
        Para excluir um projeto continuado clique na lixeira ao lado do projeto na tabela.<br>
        </p>
</div>
