<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/projeto-previsto.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
         Esta tela permite cadastrar os Projetos Previstos listados no contrato.<br>
		1. Contrato (campo obrigatório): selecione o contrato.<br>
		2. Unidade (campo obrigatório) : selecione a unidade sustentará o projeto previsto<br>
		3. Tipo de Projeto(campo obrigatório): selecione o tipo de projeto (novo ou evolutivo)<br>
                4. Projeto Previsto (campo obrigatório): escreva o nome do projeto previsto<br>
                5. Unidade de Métrica Prevista (capo obrigatório): coloque a quantidade de unidade de métrica estimada para o projeto.
                   Selecione a unidade específica (obs: essa unidade deve ser pré-cadastrada pelo administrador)<br>
                6. Descrição : Descrição do projeto previsto.
		Para cadastrar um projeto previsto, preencha os campos e clique no botão "Salvar".<br>
		Para alterar um projeto previsto, clique no nome do projeto previsto na tabela, preencha os campos e clique no botão "Salvar".<br>
		Para excluir um projeto previsto, clique no nome do projeto previsto na tabela e clique no botão "Excluir".<br>

  </p>
  </div>
