<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/proposta.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela Criação de Proposta permite estabelecer uma proposta para um novo projeto ou para um projeto evolutivo.<br>
        Ao selecionar uma Nova proposta, se existir um pré-projeto para a proposta clique nele, senão escolha "Nenhum".<br>
        Ao selecionar Proposta evolutiva selecione de qual projeto ela se refere. Se existir um pré projeto evolutivo, clique nele. Caso contrário n!ao escolha pré projeto.<br>
        </p>
</div>
