<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/controle/questionario.png" alt="Tela Ajuda" />
<p style="text-align: center; "> 
    A tela Questionário de Avaliação permite cadastrar a avaliação do usuário de uma proposta ou plano de projeto.<br>
    1) Contrato: selecione o contrato.<br>
    2) Projeto : selecione o projeto.<br>
    3) Proposta: selecione a proposta.<br><br>
    Para salvar o questionário clique o botão "Salvar".<br><br>
    OBS:<br>
        a)os itens são dinâmicos e cadastrados anteriormente.<br>
        b)existe no menu relatório o questionário em branco para ser submetido ao usuário gestor eposteriormente registrado nessa tela.<br>

</p>
</div>
