<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/questao-analise-risco.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
         Esta tela permite cadastrar as Questões de Análse de Risco.<br>
		1. Objeto Contrato (campo obrigatório): selecione o objeto do contrato.<br>
		2. Etapa (campo obrigatório) : selecione a etapa a qual a questão será associada<br>
		3. Atividade (campo obrigatório) : selecione a atividade a qual a questão será associada<br>
		4. Item de Risco (campo obrigatório) : selecione o item de risco o qual a questão será associada<br>
		5. Questão do Risco de Item(campo obrigatório): registre  a questão de risco. IMPORTANTE: a questão deve ser elaborada de forma a se responder sim ou não, sendo que a respopsta sim indica não haver risco.<br>
                6. Peso (campo obrigatório): escreva o pesso que a questão tem em relação à outras perguntas<br>
                7. Objetivo: escreva o objetivo o qual a questão deseja alcançar.<br>
		Para cadastrar uma questão de risco, preencha os campos e clique no botão "Salvar".<br>
		Para alterar uma questão de risco, clique no nome da questão de risco na tabela, preencha os campos e clique no botão "Salvar".<br>
		Para excluir uma questão de risco, clique no nome da questão de risco na tabela e clique no botão "Excluir".<br>
        </p>
</div>
