<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/solicitacao-tipo-demanda/reencaminhar-solicitacao-tipo-demanda.png" alt="Tela Ajuda" />

	<p>
		A tela de reencaminhamento de solicitação permite a designação de novos profissionais
		para a execução da solicitação, assim como o reencaminhamento de solicitação para
		profissionais já designados.
	</p>
	<p>
		O reencaminhamento é efetuado a partir das solicitações executadas.
	</p>
	

	
</div>
