<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/logo4.png" alt="Tela Ajuda Indisponível" />
	<p style="text-align: center;">
        A tela Regras de Negócio - Fechamento de Versão lista as regras de negócio cadastradas e permite que seja fechada.<br>
        Para fechar uma regra de negócio clique no botão "Fechar Versão" referente a regra de negócio desejada. <br>
        </p>
</div>
