<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/regra-de-negocio-lista.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela lista as regras de negócio do projeto.</p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/regra-de-negocio-nova.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela permite cadastrar a regra de negócio. </p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/regra-de-negocio-fechamento.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">A tela lista as regras de negócio para realização do fechamento da regra. </p>
</div>
