<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioDemanda-comparativo-nivel-de-servico.png" alt="Página Ajuda Relatório" />

	<p style="text-align: center; ">
		O Comparativo de Nível de Serviço visa lista as Solicitações/Demandas para
		verificação, principalmente, do prazo de atendimento das solicitações e os
		profissionais designados para execução.
	</p>
</div>
