<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-analise-medicao.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        O relatório de Análise de Medição é gerado pela escolha por Medição ou por Box.
        Para gerar escolha uma das opções e selecione o desejado e clique o botão "Gerar".<br>
        </p>
</div>
