<div class="divConteudoAjuda" >
	<img src="<?php echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-pagamento-contrato.png" alt="Tela Ajuda" />

	<p>
		O Extrato de Pagamento do Contrato é gerado a partir da escolha de um contrato e
		demonstra os pagamentos realizados mensalmente durante a vigência do contrato.
	</p>
	<p>
		Para que o Extrato seja gerado é necessário que o contrato possua uma Métrica Padrão
		definida. A Métrica padrão é definida no menu Contrato por profissional competente.
	</p>
</div>
