<div class="divConteudoAjuda">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorio-geral.png" alt="Tela Ajuda" />

	<p>
		Os relatórios Gerais demonstram informações gerais que não estão ligadas
		ao contrato ou projetos são mais voltados para a área administrativa do
		OASIS, exceto o relatório de Ata de Reunião que possibilita a impressão de
		ata de reunião em branco para que qualquer profissional possa imprimir para
		eventuais reuniões.
	</p>
	<p>
		Obs: as opções de relatório variam de acordo com o perfil do profissional.
	</p>
</div>
