<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-catalogo-projeto.png" alt="Tela Ajuda" />
	<p>
		O Catálogo de Projetos tem por objetivo mostrar as informações basicas e técnicas do projeto, tais como:
	</p>
	<ul>
		<li>Descrição</li>
		<li>Previsão de Início e Término</li>
		<li>Conhecimentos Utilizados</li>
		<li>Público Alvo</li>
		<li>Etc</li>
	</ul>
</div>