<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorio-controle-acompanhamento.png" alt="Tela Ajuda" />

	<p>
		Os relatórios de Controle e Acompanhamento possibilitam a visualização das
		informações geradas durante as etapas de fiscalização dos produtos desenvolvidos
		na vigência dos contratos.
	</p>
	<p>
		Obs: as opções de relatório variam de acordo com o perfil do profissional.
	</p>
</div>
