<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-extrato-geral-execucao-contrato.png" alt="Tela Ajuda" />
	
	<p>
		O Extrato Geral de Execução Contrato mostra a relação dos projetos desenvolvidos
		no contrato com a quantidade de unides de métrica para cada projeto.
	</p>
	<p>
		Para que o Extrato seja gerado é necessário que o contrato possua uma Métrica padrão
		definida. A Métrica padrão é definida no menu Contrato por profissional competente.
	</p>

</div>