<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-dados-contrato.png" alt="Tela Ajuda" />

	<p>
		Para que seja gerado o relatório é necessário a escolha do contrato. Os dados obtidos a partir do relatório dos Dados do Contrato são:
	</p>
	<ul>
		<li>Empresa a qual o contrato foi firmado</li>
		<li>Vigência do contrato</li>
		<li>Total de unidades de métrica prevista para o contrato</li>
		<li>Lista de projetos a serem desenvolvido no contrato</li>
	</ul>

</div>