<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-plano-de-implantacao.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
		O relatório de Plano de Implantação tem por objetivo mostrar o Plano de 
		Implantação previsto para a proposta do projeto selecionado. O relatório
		mostra a descrição do Plano e as atividades a serem desenvolvidas.
	</p>
</div>
