<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-extrato-geral-execucao-contrato-custo.png" alt="Tela Ajuda" />
	<p>
		O Extrato Geral de Execução Contrato com Custo mostra a relação dos projetos
		desenvolvidos no contrato com os valores pagos para cada projeto.
	</p>
	<p>
		Para que o Extrato seja gerado é necessário que o contrato possua uma Métrica padrão
		definida. A Métrica padrão é definida no menu Contrato por profissional competente.
	</p>
</div>