<div class="divConteudoAjuda">
	<div align="center">
		<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-historico-projeto.png" alt="Tela Ajuda" />
	</div>
	<p style="text-align: center; ">
		O relatório de Histórico Geral do Projeto mostra todos os registros de
		históricos das atividades desenvolvidas no projeto de acordo com os filtros
		selecionados.
	</p>
</div>