<div class="divConteudoAjuda">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-ata-de-reuniao.png" alt="Tela Ajuda" />
	<p>
		O relatorio de Ata de Reunião proporciona a impressão das atas de reunião
		cadastradas para um determinado projeto.
	</p>
	<p>
		Proporciona, ainda, a impressão de ata de reunião em branco para que seja
		utilizada em reuniões para anotação das informações.
	</p>
</div>