<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorio-contrato.png" alt="Página Ajuda Relatório de Contrato" />
	
	<p>
		Os Relatórios de Contrato dizem respeito às informações que podem ser
		extraídas do OASIS referentes aos Contratos gerenciados pelo sistema.
	</p>
	<p>
		Obs: as opções de relatório variam de acordo com o perfil do profissional.
	</p>

</div>
