<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-projeto-desenvolvido-contrato.png" alt="Tela Ajuda" />
	<p>
		O relatório de Projetos Desenvolvido no Contrato mostra todos os projetos
		desenvolvidos efetivamente na vigência do contrato. Os projetos apresentados
		no relatório podem ser filtrados por:
	</p>
	<ul>
		<li>Projetos Interno</li>
		<li>Projetos Externo</li>
		<li>Ambos</li>
	</ul>
	<p>
		No relatório é apresentado dados como o Escopo, o Contexto Geral, o Gestor do Projeto, etc.
	</p>
</div>
