<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-conteudo-baseline.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
		O relatório de Conteúdo de Baseline tem por objetivo mostrar a versão dos
		item constantes na baseline. Os itens são mostrados de acordo com a escolha
		feita nos parâmetros para geração do relatório.
	</p>
</div>