<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioDiverso-penalizacao.png" alt="Tela Ajuda" />

	<p>
		O relatório de penalizações mostra todas as penalizações sofridas no
		contrato durante o período informado.
	</p>
	<p>
		O relatório traz informações referentes as penalizações com justificativas
		aceitas, não aceitas e as penalizações sem justificativas. Traz também,
		informações referentes ao número de vezes em que a penalização ocorreu
		assim como os percentuais das penalidades.
	</p>
</div>
