<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/relacao-contratual.png" alt="Tela Ajuda" />
  <p style="text-align: center; ">
   A Tela Relação Contratual permite cadastrar as relações contratuais dos profissionais que são cadastrados no sistema.<br>
   1) Relação Contratual (campo obrigatório): ralação contratual.<br>
   Para gravar uma relação contratual preencha os dados e clique no botão "Salvar".<br>
   </p>
</div>
