<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-dicionario-de-dados.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
		O relatório de Dicionário de Dados tem por objetivo mostrar as informações
		referentes ao dicionário de dados gerado na Elaboração da Proposta
		do projeto selecionado como parâmetro.
	</p>
</div>