<div class="divConteudoAjuda">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-profissional.png" alt="Tela Ajuda" />
	<p>
		O relatório de Profissional proporciona a impressão dos profissionais
		associados ao objeto escolhido como parâmetro.
	</p>
	<p>
		São apresentados no relatório dados básicos do cadastro dos profissionais,
		a diferença entre os relatórios 'Completo' e 'Resumido' é a quantidade
		de informação apresentadas.
	</p>
</div>
