<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-custo-projeto.png" alt="Tela Ajuda" />
	
	<p>
		O relatório de custo de projeto tem o objetivo de demonstrar o custo dos
		projetos de um de terminado contrato ou o custo dos projetos referentes
		a uma determinada unidade.
	</p>
	<p>
		Caso opte em gerar o relatório "Por Projeto", é necessário a escolha do
		contrato e do projeto. Ao selecionar um projeto específico as informações
		mostradas no relatório serão detalhadas por proposta e parcela. Selecionando
		todos os projetos as informações serão mostradas por projeto.
	</p>
	<p>
		Caso opte em gerar o relatório "Por Unidade", é necessário a escolha de
		uma unidade. Serão mostradas no relatorio, informações referentes ao custo
		dos projetos desenvolvidos para a unidade selecionada.
	</p>
</div>