<div class="divConteudoAjuda">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-documento-proposta.png" alt="Tela Ajuda" />
	<p>
		O relatório de Plano de Projeto descreve as principais informações prestadas
		durante a elaboração da proposta tais como:
	</p>
	<ul>
		<li>Contexto Geral</li>
		<li>Custo do Projeto</li>
		<li>Módulos a serem trabalhados</li>
		<li>Cronograma</li>
		<li>Data de Fechamento da Proposta</li>
		<li>Data de Aceita da Proposta</li>
	</ul>
</div>