<div class="divConteudoAjuda">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-parecer-tecnico-proposta.png" alt="Tela Ajuda" />
	<p>
		O Parecer Técnico da Proposta relata os dados do parecer técnico da proposta
		selecionada realizado pela área competente durante a fase de fiscalização
		e acompanhamento.
	</p>
	<p>
		O relatório mostra os itens avaliados, quem efetuou o parecer.
	</p>
</div>
