<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-alocacao-profissional.png" alt="Tela Ajuda" />
	<p>
		O relatório de Alocação de Profissional tem por objetivo mostrar o profissionais alocados nos projetos.
	</p>
	<p>
		O relatório pode ser gerado de duas maneiras distintas:
	</p>
	<ul>
		<li>Projeto Por Profissional: mostra os profissionais alocado aos projetos</li>
		<li>Profissional Por Projeto: mostra os projetos em que o profissional está alocado</li>
	</ul>
</div>