<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-checklist-proposta.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
		O CheckList de Proposta demonstra o status (OK/Pendente) das etapas de
		controle para cada proposta contida no mês/ano informados para a pesquisa
		juntamente com a quantidade de unidade de métrica prevista para a proposta.
	</p>
</div>