<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-requisito-projeto.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
		O relatório de Requisitos tem por objetivo mostrar os requisitos do projeto
		de acordo com as opções escolhidas. O relatório mostra a descrição do requisito,
		seu status, sua versão e data de versionamento.
	</p>
</div>
