<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-checklist-parcela.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
		O CheckList de Parcelas demonstra o status (OK/Pendente) das etapas de
		controle para cada parcela contida no mês/ano informados para a pesquisa
		juntamente com a quantidade de unidade de métrica prevista para a parcela.
	</p>
</div>