<div class="divConteudoAjuda">
	<img src="<?php echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-parecer-tecnico-parcela.png" alt="Tela Ajuda" />
	<p>
		O Parecer Técnico da Parcela relata os dados do parecer técnico da parcela
		selecionada realizado pela área competente durante a fase de fiscalização
		e acompanhamento.
	</p>
	<p>
		O relatório mostra os itens avaliados, quem efetuou o parecer e os produtos
		realizados na parcela.
	</p>
</div>
