<div class="divConteudoAjuda">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-avaliacao-qualidade.png" alt="Tela Ajuda" />
	<p>
		O relatório de Avaliação de Qualidade tem por objetivo demonstrar a avaliação
		da qualidade de projeto ou de contrato.
	</p>
	<p>
		Caso selecione um projeto específico, será mostrado as avaliações das propostas do projeto
		e a avaliação geral do projeto.
	</p>
	<p>
		Caso opte por 'Totos' os projetos do contrato, será mostrado as avaliações
		global do contrato.
	</p>
</div>
