<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/relatorio/relatorioProjeto-regra-de-negocio.png" alt="Tela Ajuda" />
	<p>
		O relatório de Regras de Negócio tem por objetivo mostrar as regras de 
		negócio do projeto de acordo com as opções escolhidas. O relatório mostra
		a descrição da regra, seu status, sua versão e data de versionamento.
	</p>
</div>
