<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/requisito-proposta-fechamento.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Requisitos - Fechamento de Versão lista os requisitos cadastrados e permite que seja fechado.<br>
        Para fechar um requisito clique no botão "Fechar Versão" referente ao requisito desejado. <br>

        </p>
</div>
