<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/logo4.png" alt="Tela Ajuda Indisponível" />
	<p style="text-align: center; ">
        A tela Dependência de Requisitos permite associar os requisitos a outros requisitos com finalidade de rastreabilidade.<br>
        1) Requisito: selecione o requisito.<br>
        2) Requisitos não associados: selecione os requisitos que se deseje associar e tecle o botão ">>".<br>
        Para atualizar a versão dos requisitos tecle o botão "Atualizar Versão dos Requisitos Dependentes".<br>
        </p>
</div>
