<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/requisito-proposta.png" alt="Tela Ajuda" />
		<p style="text-align: center; ">A tela mostra a lista de requisitos de uma projeto.</p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/requisito-proposta-novo.png" alt="Tela Ajuda" />
		<p style="text-align: center; ">A tela permite cadastrar o requisito </p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/requisito-proposta-dependencia.png" alt="Tela Ajuda" />
		<p style="text-align: center;">A tela permite associar os requisitos dependentes do requisito escolhido.</p>

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/projeto/requisito-proposta-fechamento.png" alt="Tela Ajuda" />
		<p style="text-align: center; ">A tela permite realizar o fechamento do requisito</p>
</div>
