<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/requisito-proposta-novo.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Nov requisito permite cadastrar um requisito do projeto.<br>
        1) Usuário solicitante: nome do usuário que definiu o requisito.<br>
        2) Nivel do Solicitante: cargo do solicitante.<br>
        3) Requisito: requisito resumido.<br>
        4) Prioridade Requisito: selecione a prioridade.<br>
        5) Status do requisito: selecione o status.<br>
        6) Descrição: descrição do requisito.<br>
        7) Caso o requisito seja não funcional marque o campo "Não Funcional".<br>
        Para salvar o requisito preencha todos os dados e clique no botão "Salvar".<br>
        Todos os dados são obrigatórios.
        </p>
</div>
