<div class="divConteudoAjuda" >
    <img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/registro-atividade/reuniao.png" alt="Tela Ajuda" />
    <p>A ata de reunião e criada por um profissional participante de uma reunião, após sua conclusão, realizando o cadastramento das deliberações obtidas.</p>
    <ul>
        <li>Projeto (Campo Obrigatório): Projeto referente a reunião.</li>
        <li>Data (Campo Obrigatório): Data que foi realizada a reunião.</li>
        <li>Local (Campo Obrigatório): Local onde foi realizada a reunião.</li>
        <li>Pauta (Campo Obrigatório): Descrição dos tópicos tratados na reunião.</li>
        <li>Participantes (Campo Obrigatório): Participantes externos ao projeto.</li>
        <li>Ata (Campo Obrigatório):Participantes externos ao projeto.</li>
    </ul>
</div>

