<div class="divConteudoAjuda" >
    <img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/registro-atividade/reuniao-profissional.png" alt="Tela Ajuda" />
    <p>Os demais profissionais participantes do OASIS na reunião, são vinculados a ata através dessa funcionalidade, não necessitando a realização de uma ata para cada profissional.</p>
    <ul>
        <li>Projeto (Campo Obrigatório): Projeto referente a reunião.</li>
        <li>Reunião (Campo Obrigatório): Reunião cadastrada do projeto.</li>
        <li>Profissionais (Campo Obrigatório): Profissionais da equipe de TI que participaram da reunião.</li>
    </ul>
</div>

