<div class="divConteudoAjuda" >
    <img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/contrato/rotina.png" alt="Tela Ajuda" />
    <p>Essa tela permite cadastrar rotinas para uma área de atuação.</p>
    <ul>
        <li>Área de Atuação de TI (Campo Obrigatório): Área de atuação.</li>
        <li>Rotina (Campo Obrigatório): Identificaçãoda rotina.</li>
        <li>Periodicidade (Campo Obrigatório): Periodicidade que a rotina deve ser executada.</li>
        <li>Hora (Campo Obrigatório): Hora que deve ser executada a rotina.</li>
        <li>Prazo de Execução (Hora) (Campo Obrigatório): Quantidade de hora cheia para execução da rotina.</li>
        <li>Inativa: Indicação de que a rotina está inativa.</li>
    </ul>

    OBS: Conforme a indicação de periodicidade será solicitado informação de dia, semana ou hora.s
</div>

