<div class="divConteudoAjuda" >
<!-- AJUDA PARA TELA DE SOLICITAÇÕES -->
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/solicitacao-tipo-demanda/solicitacoes.png" alt="Tela Ajuda" />
	<p>
		Esta tela possibilita a visualização das solicitações abertas. A tela
		possui de uma lista com as informações mínimas das solicitações abertas
		pelos profissionais. Ao acessar a tela, a lista é preenchida com as informações
		referentes ao mês e ano correntes.
	</p>
	<p>
		No momento em que uma solicitação é criada,esta solicitação conterá um
		contador regressivo que demonstra o tempo restante para a leitura da mesma.
	</p>
	<p>
		Para registrar a leitura da solicitação basta selecionar o registro na lista
		clicando no número da solicitação. Esta ação abrirá uma tela com os dados da
		solicitação para leitura. Caso a leitura seja efetuada no prazo, parecerá um
		botão permitindo o encaminhamento da solcitação para execução.
	</p>
	<p>
		Caso a leitura não seja efetuada no prazo, parecerá um botão permitindo
		o cadastramento da justificativa da não leitura da solicitação, para, só então,
		permitir o encaminhamento da solcitação para execução.
	</p>
	<p>
		Caso a solicitação já estiver sido encaminhada, também existe a possibilidade
		de se alterar o encaminhamento a partir do botão aproriado.
	</p>

<!-- AJUDA PARA TELA DE SOLICITAÇÕES EXECUTADAS -->
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/solicitacao-tipo-demanda/executadas.png" alt="Tela Ajuda" />
	<p>
		Esta tela possibilita a visualização das solicitações executadas. A tela
		possui de uma lista com as informações mínimas das solicitações executadas
		pelos profissionais. Ao acessar a tela, a lista é preenchida com as informações
		referentes ao mês e ano correntes.
	</p>
	<p>
		Para visualizar dados de meses ou anos anteriores basta alterar os filtro,
		assim como é possível visualizar as solicitações concluídas por um profissional
		específico.
	</p>
	<p>
		Para visualizar os detalhes da solicitação basta selecionar um dos registros
		da lista. A seleção irá abrir uma nova tela com os detalhes da solicitação.
	</p>
	<p>
		Para visualizar os detalhes da execução da solicitação basta clicar no
		profissional que executou a solicitação.
	</p>
	<p>
		A tela possibilita também o reencaminhamento e a conclusão da solicitação.
		Caso opte pelo reencaminhamento, será aberta uma nova tela para o reencaminhamento da solicitação.
		Caso opte pela conclusão, a solicitação será fechada e passará para lista de solicitações concluídas.
	</p>
	
<!-- AJUDA PARA TELA DE SOLICITAÇÕES CONCLUÍDAS -->
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/solicitacao-tipo-demanda/concluidas.png" alt="Tela Ajuda" />
	<p>
		Esta tela possibilita a visualização das solicitações concluidas. A tela
		possui de uma lista com as informações mínimas das solicitações concluídas
		pelos profissionais. Ao acessar a tela, a lista é preenchida com as informações
		referentes ao mês e ano correntes.
	</p>
	<p>
		Para visualizar dados de meses ou anos anteriores basta alterar os filtro,
		assim como é possível visualizar as solicitações concluídas por um profissional
		específico.
	</p>
	<p>
		Para visualizar os detalhes da solicitação basta selecionar um dos registros
		da lista. A seleção irá abrir uma nova tela com os detalhes da solicitação.
	</p>
	<p>
		Para visualizar os detalhes da execução da solicitação basta clicar no
		profissional que executou a solicitação.
	</p>

<!-- AJUDA PARA TELA DE CONSULTA -->
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/solicitacao-tipo-demanda/consulta.png" alt="Tela Ajuda" />
	<p>
		A consulta de solicitações de Demanda tem por objetivo a visualização de
		solicitações antigas.
	</p>
	<p>
		A consulta pode ser realizada através das diversas opções de filtro
		constantes na tela.
	</p>
	<p>
		O resultado da consulta será montado em uma lista com as principais
		informações de cada solicitação. Para visualizar os detalhes da solicitação
		basta selecionar um dos registros da lista. A seleção irá abrir uma nova
		tela com os detalhes da solicitação.
	</p>

</div>