<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/solicitacao-servico/solicitacao.png" alt="Tela Ajuda" />
	<p>A tela de Cadastro de Solicitação permite o cadatramento das solicitações de serviço, os campos obrigatórios estão descritos a seguir:</p>
	<ul>
    	<li>Objeto : objeto do contrato ao qual a solicitação será criada.</li>
        <li>Tipo : tipo da demanda depende do objeto selecionado.</li>
        <li>Nome : nome do responsável pela solicitação.</li>
        <li>Unidade : unidade do responsável pela solicitação.</li>
        <li>Sala : sala do responsável pela solicitação.</li>
        <li>Telefone : telefone do responsável pela solicitação.</li>
        <li>Descrição da solicitação : objetivo da solicitação.</li>
        <li>Prazo de atendimento : prazo para que a solicitação seja atendido.</li>
    </ul>
</div>
