<div style="text-align: justify; padding: 10px;" >

	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/solicitacao-servico/solicitacao-servico-lista.png" alt="Tela Ajuda" />
	<p>
		O menu 'Solicitação de Serviço' proporciona a visualização das solicitações
		emitidas, a consulta e o cadastramento de solicitações.
	</p>
	<p> O Painel de Solicitação de Serviço permite que o usuário possa emitir uma
		nova solicitação, editar solicitações emitidas e verificar a situação das
		solicitações. No painel é possível filtrar as solicitações pelo Objeto do
		Contrato, pelo Tipo de Solicitação e pelo Período.
	</p>
	<p>
		Obs: a opção de consulta será apresentada de acordo como o perfil.
	</p>
</div>
