<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/solicitacao-servico-lista.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela de Solicitação de Serviço lista as solicitações emitidas.<br>
        Para fazer uma nova solicitação clique no botão "Nova Solicitação".<br>
        Para editar uma solicitação clique no número da solicitação.<br>
        </p>
</div>
