<div class="divConteudoAjuda" >
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/solicitacao-servico/solicitacao-servico-consulta-objeto-projeto.png" alt="Tela Ajuda" />
	<p>
		A consulta de solicitações de serviço do Tipo Projeto tem por objetivo a
		visualização de solicitações antigas.
	</p>
	<p>
		A consulta pode ser realizada através das diversas opções de filtro constantes na tela.
	</p>
	<p>
		O resultado da consulta será montado em uma lista com as principais informações de cada solicitação.
		Para visualizar os detalhes da solicitação basta selecionar um dos registros da lista.
		A seleção irá abrir uma nova aba com os detalhes da solicitação.
	</p>

</div>
