<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/status.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
   A tela de Cadastro de Status permite que se cadatre os status de um projeto. <br>
   Para cadastrar um status coloque o status e clique o botão "Salvar".<br>
   Para atualizar um status clique no status desejado e clique o botão "Salvar".<br>
   </p>
</div>
