<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/status-atendimento.png" alt="Tela Ajuda" />
<p>
   A tela de Cadastro de Status de Atendimento permite que se cadatre os status de atendimento de uma rotina ou demanda. <br>
   Para cadastrar um status coloque o status, escolha se será um status de prioridade ou de tempo de resposta.<br>
   Selecione uma cor de identificação para o status e clique no botão "Salvar".<br>
   Para atualizar um status clique no status desejado e clique o botão "Salvar".<br>
   </p>
</div>
