<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/sub-item-metrica.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite cadastrar um subitem de métrica para uma métrica de cálculo de custo de projeto.<br><br>
		1. Métrica (campo obrigatório): métrica de cálculo de custo de projeto.<br>
		2. Item de Métrica (campo obrigatório) : item de métrica de cálculo de custo de projeto.<br>
		3. Nome (campo obrigatório) : nome do subitem de item de métrica.<br>
		4. Variável (campo obrigatório): variável que receberá o valor indicado no formulário de cálculo de métrica.<br>
		5. Nr. de Ordem (campo obrigatório): ordem em que o subitem de métrica será calculado na fórmula.<br>
		6. Interno : indica que o subitem é apenas para uso interno da fórmula, não terá campo para informação de valor no formulário de cálculo de métrica.<br><br>
		Para cadastrar o subitem de métrica, preencha os campos
		e clique no botão "Salvar".
	</p>
</div>

