<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/tipo-conhecimento.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
  A tela de Cadastro de Tipo de Conhecimento permite que se cadatre os tipos de conhecimentos que podem ser utilizados em um projeto.<br>
  Para cadastrar o tipo de conhecimento coloque o tipo e clique no botõ "Salvar".<br>
  Para alterar um tipo de conhecimento clique sobre ele na tabela, preencha os dados e clique no botõ "Salvar".<br>.
</p>
</div>
