<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/tipo-documentacao.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
   A tela de Cadastro de Tipo de Documentação permite que se cadatre os tipos de documentação que podem ser utilizados em um projeto.<br<
   1) Tipo de Documento (campo obrigatório): tipo de documento.<br>
   2) Extensão do Arquivo (campo obrigatório): coloque a extensão do arquivo separados por virgulas.<br>
   3) Classificação: expecifique se a classificaçào que relaciona esse documento.<br><br>
   Para salvar um tipo de documentação preencha os dados e clique no botão "Salvar".<br>
   Para atualizar um tipo de documentação clique sobre ela na tabela, preencha os dados e clique no botão "Salvar".<br>
   Para excluir um tipo de documentação clique na lixeira ao lado do tipo de documentação.<br>
   </p>
</div>
