<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/tipo-dado-tecnico.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
  A tela de Cadastro de Tipo de Dados Técnicos permite que se cadatre os tipos de dados técnicos que podem ser utilizados em um projeto.<br>
  Para cadastrar um tipo de dados técnicos coloque o tipo e clique o botão "Salvar".<br>
  Para alterar um tipo de dados técnicos cli sobre ele na tabela, preencha os dados e clique no botão "Salvar".<br>
  </p>
</div>
