<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/administracao/tipo-produto.png" alt="Tela Ajuda" />
	<p style="text-align: justify;">
		Esta tela permite cadastrar tipos de produto para a métrica de cálculo de custo de projeto.<br><br>
		1. Métrica (campo obrigatório): métrica de cálculo de custo de projeto.<br>
		2. Tipo de Produto (campo obrigatório) : nome do tipo de produto.<br>
		3. Nº de Ordem (campo obrigatório): ordem em que tipo de produto será mostrado na lista de tipos de produto
		na tela de cadastro de produtos de parcela mensal de projeto.<br><br>
		Para cadastrar o tipo de produto, preencha os campos
		e clique no botão "Salvar".
	</p>
</div>

