<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/treinamento.png" alt="Tela Ajuda" />
	<p style="text-align: center;">
        A tela  de Treinamento permite cadastrar um treinamento.<br>
        Para salvar um treinamento preencha os dados e clique no botão "Salvar".<br>
        Para alterar um treinamento clique sobre ele na tabela, preencha os dados e clique no botão "Salvar".<br>
        Para exluir um treinamento clique na lixeira ao lado do treinamento na tabela.<br>
        </p>
</div>
