<div style="text-align: center;">
	<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/profissional/treinamento-profissional.png" alt="Tela Ajuda" />
	<p style="text-align: center; ">
        A tela Associar Profissional ao treinamento permite associar os profissionais que realizaram o treinamento especificado.<br>
        1) Objeto: selecione o objeto do contrato.<br>
        2) Treinamento: selecione o treinamento realizado.<br>
        3) Profissionais: selecione os profissionais que realizaram o treinamento especificado e clique o botão ">>".<br>
        Ao selecionar o treinamento especificado aparecerá a lisa dos profissionais associados e deve ser colocado a data do treinamento.<br>
        </p>
</div>
