<div>
<img src="<?php  echo $this->baseUrl();?>/public/img/ajuda/informacoes-basicas/unidade.png" alt="Tela Ajuda" />
<p style="text-align: center; ">
   A tela de Cadastro de Unidade permite que se cadatre as unidades.<br>
   Para cadastrar uma unidade coloque a unidade e clique no botão "Salvar".<br>
   Para alterar uma unidade clique sobre ela, preencha os dados e clique no botão "Salvar:.<br>
</p>
</div>
