<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableHistoricoExecucaoRotina").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableHistoricoExecucaoRotina").tablesorterPager({container: $("#pager_execucao_rotina"), size: 5});
});
</script>
<table id="tableHistoricoExecucaoRotina" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
			<th class="{sorter:false} span-1">&nbsp;</th>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_HORA')) ?></th>
			<th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_DESCRICAO')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res->valid()):
		foreach ($this->res as $res):
	?>
		<tr>
			<td>
				<?php if (is_null($res->st_fechamento_execucao_rotina)) { ?>
                <img id="imgExcluir"
                     height="13"
                     width="13"
                     style="cursor:pointer;"
                     onclick="excluirHistorico(
                                '<?php echo $res->dt_historico_execucao_rotina ?>',
                                '<?php echo $res->dt_execucao_rotina ?>',
                                 <?php echo $res->cd_profissional ?>,
                                 <?php echo $res->cd_objeto ?>,
                                 <?php echo $res->cd_rotina ?>
                               );"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/>
                <?}?>
			</td>
			<td style="cursor:pointer;" onclick="recuperaHistoricoRotina(
                                                        '<?php echo $res->dt_historico_execucao_rotina ?>',
                                                        '<?php echo $res->dt_execucao_rotina ?>',
                                                         <?php echo $res->cd_profissional ?>,
                                                         <?php echo $res->cd_objeto ?>,
                                                         <?php echo $res->cd_rotina ?>
                                                 );">
				<?php echo date('d/m/Y H:i:s', strtotime($res->dt_historico_rotina)) ?>
			</td>
			<td style="cursor:pointer;" onclick="recuperaHistoricoRotina(
                                                        '<?php echo $res->dt_historico_execucao_rotina ?>',
                                                        '<?php echo $res->dt_execucao_rotina ?>',
                                                         <?php echo $res->cd_profissional ?>,
                                                         <?php echo $res->cd_objeto ?>,
                                                         <?php echo $res->cd_rotina ?>
                                                 );">
				<?php echo substr($res->tx_historico_execucao_rotina,0,50)."..." ?>
			</td>
		</tr>
	<?php
		endforeach;
	else:
		echo " <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	endif;
	?>
	</tbody>
</table>
<div id="pager_execucao_rotina" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="05">05</option>
			<option value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
		</select>
	</form>
</div>
