<form id="formHomologacaoProposta" style="margin-left: 10px;">

	<?php echo $this->formHidden('cd_projeto_homologacao_proposta',$this->cd_projeto); ?>
	<?php echo $this->formHidden('cd_proposta_homologacao_proposta',$this->cd_proposta); ?>

    <label class="float-l span-3 bold"><?php echo $this->escape($this->translate('L_VIEW_PROJETO')) ?>: </label>
	<span class="float-l span-11 bold"><?php echo $this->tx_projeto." (".$this->escape($this->translate('L_VIEW_PROPOSTA'))." ".$this->cd_proposta.")"; ?></span>

	<label class="float-l clear-l span-3 right required"><?php echo $this->escape($this->translate('L_VIEW_HOMOLOGACAO')) ?>:</label>
		<input class="span-1 float-l" type="radio" id="st_homologacao_proposta_A" name="st_homologacao_proposta" value="A" checked="checked"><label class="span-1 float-l"><?php echo $this->escape($this->translate('L_VIEW_SIM')) ?></label>
		<input class="span-1 float-l" type="radio" id="st_homologacao_proposta_N" name="st_homologacao_proposta" value="N"><label class="span-1 float-l"><?php echo $this->escape($this->translate('L_VIEW_NAO')) ?></label>

	<label id="lb_tx_obs_homologacao_proposta" class="float-l clear-l span-3 right"><?php echo $this->escape($this->translate('L_VIEW_OBSERVACOES')) ?>:</label>
		<?php echo $this->formTextarea('tx_obs_homologacao_proposta', '', array( 'class'=>'float-l span-11' ,'style' => 'width:400px; height:80px;')) ?>
</form>
