<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/default/penalizacao/penalizacaoForm.js"></script>

<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tablePenalizacao").tablesorter({widthFixed: true, widgets: ['zebra']});
});
</script>
<div id="divFormPenalizacao">
	<table id="tablePenalizacao" cellspacing="1" class="tablesorter">
		<thead>
			<tr>
				<th class="{sorter: false} center" style="width: 15px;">&nbsp;</th>
                <th class="{sorter: false} center span-8"><?php echo $this->escape($this->translate('L_VIEW_GRID_INFRACAO'  )) ?></th>
				<th class="{sorter: false} center span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_OCORRENCIA')) ?></th>
				<th class="{sorter: false} center span-6"><?php echo $this->escape($this->translate('L_VIEW_GRID_OBSERVACAO')) ?></th>
			</tr>
		</thead>
		<tbody>
			<?php
				$functionsJs = "";
				if($this->arrPenalidade){
					foreach($this->arrPenalidade as $conteudo):
			?>
			<tr>
				<td>
					<?php if(trim($conteudo['tx_obs_penalizacao']) != ""){?>
						<img 
							id="imgExcluir<?php echo $conteudo['cd_penalidade'] ?>" 
							style="cursor:pointer; height:13px; width:13px;" 
							onclick="excluiPenalizacao('<?php echo $conteudo['dt_penalizacao'] ?>',<?php echo $conteudo['cd_contrato'] ?>,<?php echo $conteudo['cd_penalidade'] ?>)"
							src="<?php echo $this->baseUrl()?>/public/img/del.png" 
							alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/>
					<?php } ?>
				</td>
				<td style="text-align: justify;">
					<?php echo "{$conteudo['ni_penalidade']} - {$conteudo['tx_abreviacao_penalidade']}" ?>
				</td>
				<td class="center">
					<?php
						$idNameTextA = "tx_obs_penalizacao_{$conteudo['cd_penalidade']}"; 
						$idNameInput = "ni_qtd_ocorrencia_{$conteudo['cd_penalidade']}";
						if($conteudo['st_ocorrencia'] == "S"){
							$functionsJs .= "validaPenalidade{$conteudo['cd_penalidade']}();";
							echo " <script type=\"text/javascript\">
									function validaPenalidade{$conteudo['cd_penalidade']}()
									{
										if($('#{$idNameTextA}').val() != \"\" || $('#{$idNameInput}').val() != \"\"){
											if($('#{$idNameTextA}').val() == \"\"){
												showToolTip('".$this->escape($this->translate('L_VIEW_CAMPO_OBRIGATORIO'))."',$('#{$idNameTextA}'));
												$('#{$idNameTextA}').focus();
												return false;
											}
											if($('#{$idNameInput}').val() == \"\"){
												showToolTip('".$this->escape($this->translate('L_VIEW_CAMPO_OBRIGATORIO'))."',$('#{$idNameInput}'));
												$('#{$idNameInput}').focus();
												return false;
											}
										}
										return true;
									}
								</script>";
							echo " <input type=\"text\" 
							             id=\"{$idNameInput}\" 
							             name=\"{$idNameInput}\" 
							             class=\"span-3\" 
							             value=\"{$conteudo['ni_qtd_ocorrencia']}\" 
							             onKeyPress=\"return soNumeros(event);\"
							             onBlur=\"validaPenalidade{$conteudo['cd_penalidade']}();\" />";
						} else {
							echo "<p class=\"vermelho\">".$this->escape($this->translate('L_VIEW_NAO_APLICA'))."</p>";
						}
					?>
				</td>
				<td class="center">
					<?php
					if($conteudo['st_ocorrencia'] == "S"){
						echo "
							<textarea
								class=\"span-7 height-3\" 
								id=\"{$idNameTextA}\" 
								name=\"{$idNameTextA}\"
								onBlur=\"validaPenalidade{$conteudo['cd_penalidade']}();\">{$conteudo['tx_obs_penalizacao']}</textarea> ";
					} else {
						echo "
							<textarea
								class=\"span-7 height-3\" 
								id=\"{$idNameTextA}\" 
								name=\"{$idNameTextA}\">{$conteudo['tx_obs_penalizacao']}</textarea> ";
					}
					?>
				</td>
			</tr>
			<?php 
			endforeach;
			} else {
				echo " <tr>
						 <td>&nbsp;</td>
						 <td>&nbsp;</td>
						 <td>&nbsp;</td>
						 <td>&nbsp;</td>
					   </tr>";
			}
				?>
		</tbody>
	</table>
	<div>
        <button id="btn_salvar_penalizacao" class="float-l verde"><?php echo $this->escape($this->translate('L_BTN_SALVAR')) ?></button>
	</div>
</div>
<script type="text/javascript">

function validaCampos()
{
	<?php 
		$dados = "";
		$arrDados = explode(";",$functionsJs);
		if(count($arrDados) > 0){
			foreach($arrDados as $conteudo){
				if(trim($conteudo) != "")		
					$dados .= "if(!{$conteudo}){return false;} ";
			}
		} 
		echo $dados;
	?>
	return true;
}
</script>