<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableStatus").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableStatus").tablesorterPager({container: $("#tableStatusPager")}); 
});
</script>
<table id="tableStatus" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_STATUS')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res):
		foreach ($this->res as $res):
	?>
		<tr><td onClick="redirecionaStatus(<?php echo $res['cd_status'] ?>)" style="cursor:pointer;"><?php echo $res['tx_status'] ?></td></tr>
	<?php
		endforeach;
	else:
		echo " <tr><td>&nbsp;</td></tr>";
	endif;
	?>
	</tbody>
</table>
<div id="tableStatusPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
