<?php
    $this->script('scriptFile',array('/gerenciar-projetos-solicitacao-detalhes/index.js'));
?>
<input type="hidden" id="cd_objeto" name="cd_objeto" value="<?php echo $this->solicitacao['cd_objeto'] ?>"/>
<input type="hidden" id="ni_solicitacao" name="ni_solicitacao" value="<?php echo $this->solicitacao['ni_solicitacao'] ?>"/>
<input type="hidden" id="ni_ano_solicitacao" name="ni_ano_solicitacao" value="<?php echo $this->solicitacao['ni_ano_solicitacao'] ?>"/>
<input type="hidden" id="st_solicitacao" name="st_solicitacao" value="<?php echo $this->solicitacao['tipo_solicitacao'] ?>"/>

<h2><?php echo $this->escape($this->translate('L_VIEW_GERENCIAR_PROJETO')) ?></h2>
<h3><?php echo $this->escape($this->translate('L_VIEW_SOLICITACAO_SERVICO')) ?></h3>
<div class="box span-21 border gradient">
	<h3 class="highlight tarja-1"><?php echo $this->escape($this->translate('L_VIEW_DETALHE_SOLICITACAO')) ?></h3>

	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_NUMERO')) ?>:</label>
        <p class="span-16"><?php echo "{$this->solicitacao['ni_solicitacao']}/{$this->solicitacao['ni_ano_solicitacao']}" ?></p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_OBJETO_CONTRATO')) ?>:</label>
        <p class="span-16"><?php echo $this->solicitacao['tx_objeto'] ?></p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_DATA_SOLICITACAO')) ?>:</label>
        <p class="span-16"><?php echo $this->solicitacao['dt_solicitacao'] ?></p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_TIPO_SOLICITACAO')) ?>:</label>
        <p class="span-16"><?php echo $this->solicitacao['st_solicitacao'] ?></p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_GESTOR_SOLICITANTE')) ?>:</label>
        <p class="span-16"></p>
	<hr style="width:816px;"/>

	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_NOME')) ?>:</label>
        <p class="span-6"><?php echo $this->solicitacao['tx_solicitante'] ?></p>
	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_UNIDADE')) ?>:</label>
        <p class="span-16"><?php echo $this->solicitacao['tx_sigla_unidade'] ?></p>
	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_SALA')) ?>:</label>
        <p class="span-16"><?php echo $this->solicitacao['tx_sala_solicitante'] ?></p>
	<label class="span-3" style="padding-left:45px;"><?php echo $this->escape($this->translate('L_VIEW_TELEFONE')) ?>:</label>
        <p class="span-16"><?php echo $this->solicitacao['tx_telefone_solicitante'] ?></p>
	<hr style="width:816px;"/>

	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_DESCRICAO_SOLICITACAO')) ?>:</label>
        <p class="span-16" style="text-align: justify;"><?php echo $this->solicitacao['tx_solicitacao'] ?></p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_PRAZO_ATENDIMENTO')) ?> (<?php echo $this->escape($this->translate('L_VIEW_DIAS')) ?>):</label>
        <p class="span-16"><?php echo $this->solicitacao['ni_prazo_atendimento'] ?></p>
	<label class="bold span-4"><?php echo $this->escape($this->translate('L_VIEW_OBSERVACOES')) ?>:</label>
        <p class="span-16" style="text-align: justify;"><?php echo $this->solicitacao['tx_obs_solicitacao'] ?></p>
	<hr style="width:816px;"/>

	<label class="bold span-18 right" style="color: red;">
        <?php echo $this->translate('L_MSG_ALERT_CLIQUE_PARA_REGISTRAR_LEITURA_SOLICITACAO') ?>
    </label>
	<?php echo $this->formButton('bt_ok', $this->escape($this->translate('L_BTN_OK')), array('class' => 'float-r verde'), null)?>
</div>