<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableDefinicaoMetrica").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableDefinicaoMetrica").tablesorterPager({container: $("#tableDefinicaoMetricaPager")});
});
</script>
<table id="tableDefinicaoMetrica" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
			<th class="{sorter:false}" style="width: 10px;">&nbsp;</th>
            <th class="span-6"><?php echo $this->escape($this->translate('L_VIEW_GRID_NOME'     )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_SIGLA'    )) ?></th>
			<th class="span-6"><?php echo $this->escape($this->translate('L_VIEW_GRID_DESCRICAO')) ?></th>
			<th class="span-6"><?php echo $this->escape($this->translate('L_VIEW_GRID_FORMULA'  )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr>
			<td><img id="imgExcluir" 
                     height="13"
                     width="13"
                     style="cursor:pointer; text-align: center;"
                     onclick="excluirDefinicao('<?php echo $res['cd_definicao_metrica'] ?>');"
                     src="<?php echo $this->baseUrl()?>/public/img/del.png"
                     alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/></td>
			<?php 
			    $fimNome = "";
				if(strlen($res['tx_nome_metrica']) >= 40){
					$fimNome = "...";
				}
				$tx_nome_metrica = substr($res['tx_nome_metrica'],0,40)
			?>
			<td onClick="recuperaDefinicao(<?php echo $res['cd_definicao_metrica'] ?>)" style="cursor:pointer;"><?php echo $tx_nome_metrica.$fimNome ?></td>
			<td onClick="recuperaDefinicao(<?php echo $res['cd_definicao_metrica'] ?>)" style="cursor:pointer;"><?php echo $res['tx_sigla_metrica'] ?></td>

			<?php
			    $fimDesc = "";
				if(strlen($res['tx_descricao_metrica']) >= 40){
					$fimDesc = "...";
				}
				$tx_descricao_metrica = substr($res['tx_descricao_metrica'],0,40)
			?>
			<td onClick="recuperaDefinicao(<?php echo $res['cd_definicao_metrica'] ?>)" style="cursor:pointer;"><?php echo $tx_descricao_metrica.$fimDesc ?></td>

			<?php
			    $fimForm = "";
				if(strlen($res['tx_formula_metrica']) >= 47){
					$fimform = "...";
				}
				$tx_formula_metrica = substr($res['tx_formula_metrica'],0,47)
			?>
			<td onClick="recuperaDefinicao(<?php echo $res['cd_definicao_metrica'] ?>)" style="cursor:pointer;"><?php echo $tx_formula_metrica.$fimForm ?></td>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableDefinicaoMetricaPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
