<?php
    $this->script('uploadAjax');
    $this->script('scriptFile',array('/documentacao-contrato/index.js'));
?>
<div style="margin-left: 20px;" id="formDocumentoContrato">
	<label class="span-3 float-l clear-l required"><?php echo $this->escape($this->translate('L_VIEW_CONTRATO')) ?>:</label>
    	<p class="span-3 float-l bold"><?php echo $this->formSelect('cd_contrato_documentacao', null, null, $this->arrContratoCombo); ?></p>
    <div id="divExtensao" style="display: none;">
		<label class="span-3 float-l clear-l "><?php echo $this->escape($this->translate('L_VIEW_EXTENSOES')) ?>:</label>
	    	<span class="span-6 float-l bold" id="extensoes"></span>
	</div>
	<label class="span-3 float-l clear-l required" for="cd_tipo_documentacao" ><?php echo $this->escape($this->translate('L_VIEW_DOCUMENTACAO')) ?>:</label>
		<?php echo $this->formSelect('cd_tipo_documentacao', null, array('class' => 'float-l'), $this->tipoDocumentacaoCombo); ?>
	<label class="span-3 float-l clear-l required" for="tx_arq_documentacao_projeto"><?php echo $this->escape($this->translate('L_VIEW_ARQUIVO')) ?>:</label>
		<?php echo $this->formFile('tx_arq_documentacao_contrato',array('class'=>'float-l span-3','size'=>'50')); ?>
	<img alt="<?php echo $this->escape($this->translate('L_VIEW_AGUARDE')) ?>"
         id="imgLoadDocumentacaoContrato"
         name="imgLoadDocumentacaoContrato"
         src="<?php echo $this->baseUrl()?>/public/img/ajax-loader.gif"
         width="220px"
         height="19px"
         class="float-l clear-l push-3"
         style="display:none;" />
    <button class="float-l verde clear-l push-3" onclick="return _fnUploadDocumentacaoContrato();"><?php echo $this->escape($this->translate('L_BTN_ANEXAR_ARQUIVO')) ?></button>
	<div id="gridDocumentacaoContrato" class="float-l clear-l push-1 span-15"></div>
</div>