<?php $this->script('scriptFile',array('/desalocacao-recurso-proposta/index.js')); ?>

<div id="tabelaDesalocacaoRecursoProposta" class="divTab boxTab">
    <label class=" float-l span-3 bold right" style="margin-top: 3px;"><?php echo $this->escape($this->translate('L_VIEW_CONTRATO_ATIVO')) ?>:</label>
		<p class="float-l" style="margin-top: 3px;">
            <?php echo $this->formSelect('cd_contrato_desalocacao', null, null, $this->arrContratoAtivo) ?>
        </p>
</div>
<div id="gridDesalocacaoRecursoProposta"></div>
