<script type="text/javascript" defer="defer">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableControleEncerramentoProposta").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableControleEncerramentoProposta").tablesorterPager({container: $("#pager_encerramento_proposta")}); 
 
});
</script>
<table id="tableControleEncerramentoProposta" cellspacing="1" class="tablesorter">
	<thead>
	    <tr>
			<th><?php echo $this->escape($this->translate('L_VIEW_GRID_PROJETO')) ?></th>
			<th><?php echo $this->escape($this->translate('L_VIEW_GRID_PROPOSTA')) ?></th>
			<th class="span-4"><?php echo $this->unidadePadraoMetrica; ?></th>
			<th><?php echo $this->escape($this->translate('L_VIEW_GRID_ENCERRAMENTO')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
	<tr>
		<td><?php echo $res['tx_sigla_projeto']?></td>
		<td><?php echo $res['cd_proposta']?></td>
		<td><?php echo $res['ni_horas_proposta']?></td>
		<td style="text-align:center">
			<button onClick="encerraProposta('<?php echo $res['cd_projeto']?>', '<?php echo $res['cd_proposta']?>')" 
                    class="azul"
                    id="bt_encerra_proposta_<?php echo $res['cd_projeto']?>_<?php echo $res['cd_proposta']?>">
                <?php echo $this->escape($this->translate('L_BTN_ENCERRAR_PROPOSTA')) ?>
            </button>
		</td>	
	</tr>
	<?php
		endforeach;
	} else {
		echo "  <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>";
	}
	?>
	</tbody>
</table>
<div id="pager_encerramento_proposta" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>