<?php
    $this->script('grid');
?>

<script type="text/javascript">
$(document).ready(function() {
    $("#pedidoAnaliseAutoridadeCompetente").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#pedidoAnaliseAutoridadeCompetente").tablesorterPager({container: $("#pedidoAnaliseAutoridadeCompetentePager")});
});
</script>

<table cellspacing="1" id="pedidoAnaliseAutoridadeCompetente" class="tablesorter">
    <thead>
        <tr>
            <th class="span-3" ><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_HORA' )) ?></th>
            <th class="span-5" ><?php echo $this->escape($this->translate('L_VIEW_GRID_SITUACAO'  )) ?></th>
            <th class="span-13"><?php echo $this->escape($this->translate('L_VIEW_GRID_OBSERVACAO')) ?></th>
        </tr>
    </thead>
    <tbody>

<?php if($this->pedidosAutorizar->valid()): ?>
		<?php foreach($this->pedidosAutorizar as $rs): ?>
			<tr>
                <td>
                    <a href="<?php echo $this->url(array('module'=>'pedido','controller'=>'pedido-solicitacao', 'action'=>'historico', 'cd_solicitacao_pedido'=>$rs->cd_solicitacao_pedido )) ?>">
                        <?php echo date('d/m/Y H:i:s', strtotime($rs->dt_solicitacao_pedido)) ?>
                    </a>
                </td>
				<td><?php echo $rs->st_situacao_pedido_desc ?></td>
				<td><?php echo nl2br($rs->tx_observacao_pedido) ?></td>
			</tr>
		<?php endforeach; ?>
<?php else:
            echo " <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                  </tr>";
    endif;?>
    </tbody>
</table>
<div id="pedidoAnaliseAutoridadeCompetentePager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
		</select>
	</form>
</div>