<script language="javascript" type="text/javascript">
	$(document).ready(function(){
		var error = '<?php echo $this->error ?>';
		$('#btn_voltar_passo3').click(function(){
			$('#container-install').triggerTab(3);
		});
		$('#btn_avancar_passo5').click(function(){
			if(error == '1'){
				alertMsg(i18n.L_VIEW_SCRIPT_DIRETORIOS_NECESSITAM_PERMISSAO_LEITURA_GRAVACAO,2);
			} else {
				passoCincoConfiguracaoBancoDeDados();
			}
		});
	});
</script>
<h2 class="center">4. <?php echo $this->escape($this->translate('L_MSG_ALERT_VERIFICACAO_PERMISSAO_DIRETORIO')) ?></h2>
<br />
<div class="float-l clear-l span-21">
	<?php echo $this->html ?>
</div>
<!-- Botões da tela -->
<div class="float-l clear-l span-10" style="margin-top:40px;">
	<span class="float-l right"><?php echo $this->formButton('btn_voltar_passo3',$this->escape($this->translate('L_BTN_ANTERIOR')),array('class'=>'verde right')); ?></span>
	<label class="float-l bold right"> <<< <?php echo $this->escape($this->translate('L_VIEW_TERMOS_LICENCA')) ?></label>
</div>
<div class="float-r span-10" style="margin-top:40px;">
	<span class="float-r right"><?php echo $this->formButton('btn_avancar_passo5',$this->escape($this->translate('L_BTN_PROXIMO')),array('class'=>'verde right')); ?></span>
	<label class="float-r bold right"><?php echo $this->escape($this->translate('L_VIEW_CONFIGURACAO_BANCO_DADOS')) ?> >>></label>
</div>