<?php
    $this->script('validaForm');
    $this->script('scriptFile',array('/checklist-projeto/index.js'));
?>
<form id="formRelatorioProjetoChecklistProjeto">
    <label class="span-2 right float-l required" for="cd_contrato"><?php echo $this->translate('L_VIEW_CONTRATO') ?>:</label>
		<?php echo $this->formSelect('cd_contrato',null,array('class'=>'float-l'),$this->arrContrato); ?>

    <button class="buttonBar verde" id="btn_gerar" name="btn_gerar" type="button"><?php echo $this->translate('L_BTN_GERAR') ?></button>
</form>