<?php
    $this->script('scriptFile',array('/reuniao-geral-profissional/index.js'));
?>
<div class="span-21">
	<div id="div_combos_reuniao_geral_profissional" class="float-l">
		<label class="float-l span-3 right required" for="cd_objeto_reuniao_geral_profissional"><?php echo $this->escape($this->translate('L_VIEW_OBJETO')) ?>:</label>
			<?php echo $this->formSelect('cd_objeto_reuniao_geral_profissional', null, array('class'=>'span-6 float-l'), $this->objetoCombo);?>
	
        <label class="float-l clear-l span-3 right required" for="cd_reuniao_geral_profissional" ><?php echo $this->escape($this->translate('L_VIEW_REUNIAO_GERAL')) ?>:</label>
			<?php echo $this->formSelect('cd_reuniao_geral_profissional', null, array('class'=>'span-6 float-l'), array(0=>$this->escape($this->translate('L_VIEW_COMBO_SELECIONE'))));?>
	</div>
	<hr />
</div>
<?php echo $this->flipFlop(array('name'=>'cd_profissional_combo', 'label'=>$this->escape($this->translate('L_VIEW_PROFISSIONAIS')), 'value'=>$this->profissionais),
						   array('name'=>'cd_profissional2', 'label'=>$this->escape($this->translate('L_VIEW_PROFISSIONAIS_ASSOCIADOS')), 'value'=>$this->profissionais2),
						   'add',
						   'remove',8);
?>
