<div id="tabDemandaConcluida" class="divTab">
	<div class="boxTab">
		<label class="float-l bold" style="margin-top:2px; font-size:16px;" id="mesAnoConcluida"><?php echo $this->mesAno ?></label>
		<label class="float-r" style="margin-top:2px;"><?php echo $this->anoCombo('anoDemandaConcluida') ?></label>
		<label class="float-r" style="margin-top:2px;"><?php echo $this->mesCombo('mesDemandaConcluida',null,null,1) ?></label>
		<label class="float-r" style="margin-top:2px;"><?php echo $this->formSelect('cd_profissional_demanda_concluida', null, array('class' => 'span-5 float-l', 'style' => 'margin-right: 10px;'), $this->cd_profissional_combo) ?></label>
        <label class="float-r" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_PROFISSIONAL')) ?>:</label>
	</div>

	<div id="gridDemandaConcluida" class="float-l clear-l span-21"></div>
</div>