<div id="tabDemandaExecutada" class="divTab">
	<div class="boxTab">
		<label class="float-l bold" style="margin-top:2px; font-size:16px;" id="mesAnoExecutada"><?php echo $this->mesAno ?></label>
		<label class="float-r" style="margin-top:2px;"><?php echo $this->anoCombo('anoDemandaExecutada') ?></label>
		<label class="float-r" style="margin-top:2px;"><?php echo $this->mesCombo('mesDemandaExecutada',null,null,1) ?></label>
		<label class="float-r" style="margin-top:2px;"><?php echo $this->formSelect('cd_profissional_demanda_executada', null, array('class' => 'span-5 float-l', 'style' => 'margin-right: 10px;'), $this->cd_profissional_combo) ?></label>	
        <label class="float-r" style="margin-top:2px;"><?php echo $this->escape($this->translate('L_VIEW_PROFISSIONAL')) ?>:</label>
	</div>

	<div id="gridDemandaExecutada" class="float-l clear-l span-21"></div>
</div>