<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableDemandaConcluida").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableDemandaConcluida").tablesorterPager({container: $("#pager-demanda-concluida")}); 
});
</script>
<?php  echo $this->formHidden('mesAnoDemandaConcluida',$this->mesAno) ?>
<table id="tableDemandaConcluida" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-1"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_HORA'            )) ?></th>
			<th class="span-1"><?php echo $this->escape($this->translate('L_VIEW_GRID_NUMERO'               )) ?></th>
			<th class="span-1"><?php echo $this->escape($this->translate('L_VIEW_GRID_UNIDADE'              )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_DESCRICAO_SOLICITACAO')) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_PROFISSIONAIS'        )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res):
		foreach ($this->res as $res):
	?>
		<tr>
			<td><a href="<?php echo $this->baseUrl()?>/painel-demanda/demanda-executada-detalhes/cd_demanda/<?php echo $res['cd_demanda']?>/abaOrigem/demanda-concluida"><?php echo date('d/m/Y H:i:s', strtotime($res['dt_demanda'])) ?></a></td>
			<td><?php echo $res['cd_demanda']       ?></td>
			<td><?php echo $res['tx_sigla_unidade'] ?></td>
			<td><?php echo substr(strip_tags($res['tx_demanda']),0,40)."..." ?></td>
			<td>
				<?php 
					if(count($this->arrProfissionalDemanda[$res['cd_demanda']]) > 0):
						$quant = count($this->arrProfissionalDemanda[$res['cd_demanda']]);
						foreach($this->arrProfissionalDemanda[$res['cd_demanda']] as $key=>$value): ?>
							<a style="cursor:pointer;" onclick="abreTabProfissionalDesignado(<?php echo $res['cd_demanda'] ?>, <?php echo $key ?>, 3)"><?php echo $value ?></a>
							<?php if($quant > 0){ echo "<br />"; } ?>
				<?php 
							$quant--;
						endforeach; 
					endif;
				?>
			</td>
		</tr>
	<?php
		endforeach;
	else:
		echo "  <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	endif;
	?>
	</tbody>
</table>
<div id="pager-demanda-concluida" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>