<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableDemandaAndamento").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableDemandaAndamento").tablesorterPager({container: $("#pager-demanda-andamento")}); 
});
</script>

<?php  echo $this->formHidden('mesAnoDemandaAndamento',$this->mesAno) ?>
<table id="tableDemandaAndamento" cellspacing="1"
	class="tablesorter">
	<thead>
		<tr>
            <th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_DATA_HORA'            )) ?></th>
			<th class="span-1"><?php echo $this->escape($this->translate('L_VIEW_GRID_NUMERO'               )) ?></th>
            <th class="span-1 {sorter:false}">
                <div class="float-l">P</div>
                <div class="float-l" style="margin-left: 18px;">T</div>
            </th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_UNIDADE'              )) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_DESCRICAO_SOLICITACAO')) ?></th>
			<th class="span-1 {sorter:false}"><?php echo $this->escape($this->translate('L_VIEW_GRID_ACAO'  )) ?></th>
			<th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_PROFISSIONAIS'        )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res):
		foreach ($this->res as $res):
	?>
		<tr>
			<td>
				<a href="<?php echo $this->baseUrl()?>/painel-demanda/demanda-executada-detalhes/cd_demanda/<?php echo $res['cd_demanda']?>/abaOrigem/demanda-andamento"><?php echo date('d/m/Y H:i:s', strtotime($res['dt_demanda'])) ?></a>
			</td>
			<td><?php echo $res['cd_demanda'] ?></td>
            <td>
                <!-- rotina para desenhar a bolhinha das prioridades -->
                <?php
                    $prioridade = $this->escape($this->translate('L_VIEW_PRIORIDADE'));
                    $paramsDivPrioridade = ($res['tx_rgb_status_atendimento']) ? " title=\"{$prioridade} {$res['tx_status_atendimento']}\" style=\"background-color: #{$res['tx_rgb_status_atendimento']}\"" : '';
                ?>
                <div class="circleColorPriority float-l" <?php echo $paramsDivPrioridade?>></div>

                <!-- rotina para desenhar a bolhinha do tempo de execução da demanda -->
                <?php if (!is_null($res['cd_demanda'])):
                            $tempo = $this->escape($this->translate('L_VIEW_TEMPO_RESPOSTA'));
                            $paramsDivTempoResposta = " title=\"{$tempo} {$this->arrTempoRespostaDemanda[$res['cd_demanda']]['tempo_resposta']}\" style=\"background-color: #{$this->arrTempoRespostaDemanda[$res['cd_demanda']]['cor']}\"";
                ?>
                        <div class="circleColorTime float-l" <?php echo $paramsDivTempoResposta?>></div>
                <?php endif;?>

            </td>
			<td><?php echo $res['tx_sigla_unidade'] ?></td>
			<td><?php  echo substr(strip_tags($res['tx_demanda']),0,30)."..." ?></td>
			<td class="center">
				<button class="icon alterar_encam"
                        onClick="encaminhaDemandaParaOutroProfissional('<?php echo $res['cd_demanda']?>')"
                        id="button_encaminhar_outro_<?php echo $res['cd_demanda']?>"
                        title="<?php echo $this->escape($this->translate('L_BTN_ALTERAR_ENCAMINHAMENTO')) ?>">
                </button>
			</td>
			<td>
				<?php 
					if(count($this->arrProfissionalDemanda[$res['cd_demanda']]) > 0):
						$quant = count($this->arrProfissionalDemanda[$res['cd_demanda']]);
						foreach($this->arrProfissionalDemanda[$res['cd_demanda']] as $key=>$value): ?>
							<a style="cursor:pointer;" onclick="abreTabProfissionalDesignado(<?php echo $res['cd_demanda'] ?>, <?php echo $key ?>, 1)"><?php echo $value ?></a>
							<?php if($quant > 0): echo "<br />"; endif; ?>
				<?php 
							$quant--;
						endforeach; 
					endif;
				?>
			</td>
		</tr>
	<?php
		endforeach;
	else:
		echo "  <tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr> ";
	endif;
	?>
	</tbody>
</table>
<div id="pager-demanda-andamento" class="pager">
<form><img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png"
	class="first" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png"
	class="prev" /> <input type="text" class="pagedisplay" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png"
	class="next" /> <img
	src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png"
	class="last" /> <select class="pagesize">
	<option selected="selected" value="10">10</option>
	<option value="20">20</option>
	<option value="30">30</option>
	<option value="40">40</option>
</select></form>
</div>