<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tablePenalidade").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tablePenalidade").tablesorterPager({container: $("#tablePenalidadePager"), size:5}); 
});
</script>
<table id="tablePenalidade" cellspacing="1" class="tablesorter" style="border-collapse:collapse">
	<thead>
		<tr>
            <th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_NUMERO')) ?></th>
			<th class="span-9"><?php echo $this->escape($this->translate('L_VIEW_GRID_PENALIDADE_RESUMIDA')) ?></th>
			<th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_PORCENTAGEM')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res):
		foreach ($this->res as $res):
	?>
		<tr>
			<td onClick="recuperaPenalidade(<?php echo $res['cd_penalidade'] ?>)" style="cursor:pointer;">
				<?php echo $res['ni_penalidade'] ?>
			</td>
			<td onClick="recuperaPenalidade(<?php echo $res['cd_penalidade'] ?>)" style="cursor:pointer;">
				<?php echo $res['tx_abreviacao_penalidade'] ?>
			</td>
			<td onClick="recuperaPenalidade(<?php echo $res['cd_penalidade'] ?>)" style="cursor:pointer;">
				<?php echo $res['ni_valor_penalidade']."%" ?>
			</td>
		</tr>
	<?php
		endforeach;
	else:
		echo " <tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			  </tr>";
	endif;
	?>
	</tbody>
</table>
<div id="tablePenalidadePager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="05">05</option>
			<option value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>