<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableTipoConhecimento").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableTipoConhecimento").tablesorterPager({container: $("#tableTipoConhecimentoPager")}); 
});
</script>
<table id="tableTipoConhecimento" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="span-5"><?php echo $this->escape($this->translate('L_VIEW_GRID_TIPO_CONHECIMENTO')) ?></th>
            <th class="span-2"><?php echo $this->escape($this->translate('L_VIEW_GRID_CONHECIMENTO_PROFISSIONAL')) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res):
		foreach ($this->res as $res):
	?>
		<tr>
           <td onClick="redirecionaTipoConhecimento(<?php echo $res['cd_tipo_conhecimento'] ?>)" style="cursor:pointer;">
                <?php echo $res['tx_tipo_conhecimento'] ?></td>
		   <td class="center" onClick="redirecionaTipoConhecimento(<?php echo $res['cd_tipo_conhecimento'] ?>)" style="cursor:pointer;">
                <?php echo ($res['st_para_profissionais'])?"<img src=\"{$this->baseUrl()}/public/img/u42.png\">":""; ?></td>
        </tr>
        
	<?php
		endforeach;
	else:
		echo " <tr>
                  <td>&nbsp;</td>
                  <td>&nbsp;</td>
               </tr>";
	endif;
	?>
	</tbody>
</table>
<div id="tableTipoConhecimentoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>