<?php 
 	$this->script('grid');
 	$this->script('validaForm');
    $this->script('mascara');
    $this->script('calendario');
    $this->script('scriptFile',array('/documento-origem/index.js'));

    echo $this->form;
?>
<hr />
<?php echo $this->formButton('btn_alterar_documento_origem',$this->escape($this->translate('L_BTN_SALVAR')),array('class'=>'buttonBar verde','style'=>'display:none')) ?>
<div id="gridDocumentoOrigem" class="float-l span-16"></div>
