<script type="text/javascript">
$(document).ready(function() { 
	// call the tablesorter plugin 
    $("#tableTipoDocumentacao").tablesorter({widthFixed: true, widgets: ['zebra']});
    $("#tableTipoDocumentacao").tablesorterPager({container: $("#tableTipoDocumentacaoPager"), size:05}); 
});
</script>
<table id="tableTipoDocumentacao" cellspacing="1" class="tablesorter">
	<thead>
		<tr>
            <th class="{sorter: false}" style="width:15px">&nbsp;</th>
            <th class="span-3"><?php echo $this->escape($this->translate('L_VIEW_GRID_TIPO_DOCUMENTO')) ?></th>
			<th class="span-4"><?php echo $this->escape($this->translate('L_VIEW_GRID_EXTENSAO'      )) ?></th>
			<th class="span-4"><?php echo $this->escape($this->translate('L_VIEW_GRID_CLAFISSICACAO' )) ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
	if($this->res){
		foreach ($this->res as $res):
	?>
		<tr>
			<td>
				<img id="imgExcluir" height="13" width="13" style="cursor:pointer;" onclick="excluirTipoDocumentacao('<?php echo $res['cd_tipo_documentacao'] ?>');" src="<?php echo $this->baseUrl()?>/public/img/del.png" alt="<?php echo $this->escape($this->translate('L_BTN_EXCLUIR')) ?>"/>
			</td>
			<td onClick="recuperaTipoDocumentacao(<?php echo $res['cd_tipo_documentacao'] ?>)" style="cursor:pointer;">
				<?php echo $res['tx_tipo_documentacao'] ?>
			</td>
			<td onClick="recuperaTipoDocumentacao(<?php echo $res['cd_tipo_documentacao'] ?>)" style="cursor:pointer;">
				<?php 
					$arrExtensao = explode(".",$res['tx_extensao_documentacao']);
					$extensoes = "";
					foreach($arrExtensao as $conteudo){
						$extensoes .= "*.{$conteudo}, ";
					}
					$extensoes = substr($extensoes,0,-2);
					echo $extensoes; 
				?>
			</td>
			<td onClick="recuperaTipoDocumentacao(<?php echo $res['cd_tipo_documentacao'] ?>)" style="cursor:pointer;">
				<?php echo $res['st_classicficacao_desc'] ?>
			</td>
		</tr>
	<?php
		endforeach;
	} else {
		echo " <tr>
				<td style=\"width:15px\">&nbsp;</td>
				<td class=\"span-3\">&nbsp;</td>
				<td class=\"span-4\">&nbsp;</td>
				<td class=\"span-4\">&nbsp;</td>
			  </tr>";
	}
	?>
	</tbody>
</table>
<div id="tableTipoDocumentacaoPager" class="pager">
	<form>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/first.png" class="first"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/prev.png" class="prev"/>
		<input type="text" class="pagedisplay"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/next.png" class="next"/>
		<img src="<?php echo $this->baseUrl()?>/public/js/lib/jquery/tablesorter/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize">
			<option selected="selected"  value="05">05</option>
			<option value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>